import fs from 'node:fs';
import path from 'node:path';

import type {Compiler, RspackPluginInstance} from '@rspack/core';
import rspack from '@rspack/core';
import {parse as parseYaml} from 'yaml';

const appDir = path.resolve(import.meta.dirname, '../static/app');
const modulePath = 'app/stories/storyManifest.generated.ts';
const PLUGIN_NAME = 'StoryManifestPlugin';
const STORY_GLOB = '**/*.{stories.tsx,mdx}';
const STORY_FILE_PATTERN = /(?:\.stories\.tsx|\.mdx)$/;
const WATCH_DEBOUNCE_MS = 25;

function readFrontmatter(file: string) {
  const block = fs
    .readFileSync(path.join(appDir, file), 'utf8')
    .match(/^---\s*\n([\s\S]*?)\n---/)?.[1];
  const data = block && parseYaml(block);
  return data && typeof data === 'object'
    ? {category: data.category, figma: data.resources?.figma}
    : undefined;
}

function createManifest() {
  const files = fs
    .globSync(STORY_GLOB, {cwd: appDir})
    .map(file => file.replaceAll('\\', '/'))
    .sort();
  const frontmatter = Object.fromEntries(
    files
      .filter(file => file.endsWith('.mdx'))
      .map(file => [`app/${file}`, readFrontmatter(file)])
  );

  const requests = files.map(file => `sentry/${file}`);
  const source = `// Generated by build-utils/story-manifest.ts. Do not edit.
// @ts-nocheck -- Rspack resolves explicit story extensions that TypeScript rejects.
export const storyImports: Record<string, () => Promise<unknown>> = {
${files.map((file, i) => `  ${JSON.stringify(`app/${file}`)}: () => import(${JSON.stringify(requests[i])}),`).join('\n')}
};
export const storyFiles = Object.keys(storyImports);
export const storyFrontmatterIndex = ${JSON.stringify(frontmatter)};
let hmrVersion = 0;
const hmrListeners = new Set<() => void>();
export const subscribeToStoriesHmr = (listener: () => void) => { hmrListeners.add(listener); return () => void hmrListeners.delete(listener); };
export const getStoriesHmrVersion = () => hmrVersion;
if (import.meta.webpackHot) {
  import.meta.webpackHot.accept([${requests.map(request => JSON.stringify(request)).join(',')}], () => { hmrVersion++; hmrListeners.forEach(listener => listener()); });
}
`;
  return {files: new Set(files), source};
}

export class StoryManifestPlugin implements RspackPluginInstance {
  private manifest = createManifest();
  private pending = new Set<string>();
  private timer?: NodeJS.Timeout;
  // Seed the module here because writeModule() is only available after Rspack's
  // Rust compiler is initialized.
  // https://rspack.rs/plugins/rspack/virtual-modules-plugin#dynamic-module-creation
  private readonly virtualModules = new rspack.experiments.VirtualModulesPlugin({
    [modulePath]: this.manifest.source,
  });
  private watcher?: fs.FSWatcher;

  apply(compiler: Compiler) {
    this.virtualModules.apply(compiler);
    compiler.hooks.watchRun.tap(PLUGIN_NAME, () => {
      // rspack.config.ts excludes Story files from Rspack's watcher so the
      // manifest can update first. Debounce the duplicate events emitted by
      // editors that save by replacing a file.
      // https://rspack.rs/config/watch#watchoptionsignored
      if (!this.watcher) {
        this.watcher = fs.watch(appDir, {recursive: true}, (_event, filename) => {
          if (filename && STORY_FILE_PATTERN.test(filename)) {
            const file = path.join(appDir, filename);
            this.pending.add(file);
            clearTimeout(this.timer);
            this.timer = setTimeout(() => {
              try {
                this.flush(compiler);
              } catch (error) {
                compiler
                  .getInfrastructureLogger(PLUGIN_NAME)
                  .error('Failed to update the Story manifest', error);
              }
            }, WATCH_DEBOUNCE_MS);
          }
        });
        this.watcher.on('error', error => {
          compiler
            .getInfrastructureLogger(PLUGIN_NAME)
            .error('Story manifest watcher failed', error);
          this.close();
        });
      }
    });
    compiler.hooks.watchClose.tap(PLUGIN_NAME, () => this.close());
    compiler.hooks.shutdown.tapPromise(PLUGIN_NAME, async () => this.close());
  }

  private flush(compiler: Compiler) {
    const changed = new Set([...this.pending].filter(file => fs.existsSync(file)));
    const removed = new Set([...this.pending].filter(file => !fs.existsSync(file)));
    const changedExistingStory = [...changed].some(file =>
      this.manifest.files.has(path.relative(appDir, file).replaceAll('\\', '/'))
    );
    // Existing TS Stories cannot change the file list or MDX metadata, so avoid
    // rescanning every Story and reparsing every MDX file for that common case.
    const shouldRebuildManifest =
      removed.size > 0 ||
      [...changed].some(file => {
        const relativeFile = path.relative(appDir, file).replaceAll('\\', '/');
        return file.endsWith('.mdx') || !this.manifest.files.has(relativeFile);
      });
    let manifestChanged = false;

    if (shouldRebuildManifest) {
      const next = createManifest();
      manifestChanged = next.source !== this.manifest.source;
      if (manifestChanged) {
        this.manifest = next;
        this.virtualModules.writeModule(modulePath, next.source);
      }
    }
    if (!manifestChanged || changedExistingStory) {
      // Pass exact paths back to Rspack so incremental compilation can
      // distinguish modified modules from removals. This is the Rspack-specific
      // part of our custom watcher integration.
      // https://rspack.rs/api/javascript-api/compiler#watch
      compiler.watching?.invalidateWithChangesAndRemovals(changed, removed);
    }
    this.pending.clear();
  }

  private close() {
    clearTimeout(this.timer);
    this.watcher?.close();
    this.watcher = undefined;
  }
}
