# Generated by Django 5.2.11 on 2026-02-24 19:09

import django.db.models.expressions
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.query import RangeQuerySetWrapper


def remove_action_sentry_app_identifier(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Action = apps.get_model("workflow_engine", "Action")

    for action in RangeQuerySetWrapper(Action.objects.filter(type="sentry_app")):
        config = action.config
        config.pop("sentry_app_identifier", None)
        action.config = config
        action.save()


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("workflow_engine", "0107_fix_email_action_fallthrough_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                models.F("type"),
                django.db.models.expressions.RawSQL("config->>'target_identifier'", []),
                condition=models.Q(("type", "sentry_app")),
                name="sentry_app_lookup_action",
            ),
        ),
        migrations.RemoveIndex(
            model_name="action",
            name="action_sentry_app_lookup",
        ),
        migrations.RunPython(
            code=remove_action_sentry_app_identifier,
            reverse_code=migrations.RunPython.noop,
            hints={"tables": ["workflow_engine_action"]},
        ),
    ]
