# Generated by Django 5.2.12 on 2026-05-01 18:51

import logging

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.query import RangeQuerySetWrapper

logger = logging.getLogger(__name__)


def migrate_data_condition_issue_category(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    DataCondition = apps.get_model("workflow_engine", "DataCondition")
    DataConditionGroup = apps.get_model("workflow_engine", "DataConditionGroup")

    # Cache the original logic_type per group ID to avoid re-fetching a DCG
    dcg_logic_type_cache: dict[int, str] = {}

    for data_condition in RangeQuerySetWrapper(DataCondition.objects.filter(type="issue_category")):
        comparison = dict(data_condition.comparison)

        # handle GroupCategory.METRIC_ISSUE (8) -> GroupCategory.METRIC (11)
        if comparison.get("value") == 8:
            comparison["value"] = 11

            data_condition.comparison = comparison
            data_condition.save()
            continue

        # handle GroupCategory.REPLAY (5) -> GroupCategory.FRONTEND (14)
        elif comparison.get("value") == 5:
            comparison["value"] = 14

            data_condition.comparison = comparison
            data_condition.save()
            continue

        # handle GroupCategory.UPTIME (7) -> issue type Uptime Monitor Detected Downtime
        elif comparison.get("value") == 7:
            data_condition.type = "issue_type"
            comparison["value"] = "uptime_domain_failure"

            data_condition.comparison = comparison
            data_condition.save()
            continue

        # handle GroupCategory.CRON (4) -> issue type Missed or Failed Cron Check-In
        elif comparison.get("value") == 4:
            data_condition.type = "issue_type"
            comparison["value"] = "monitor_check_in_failure"

            data_condition.comparison = comparison
            data_condition.save()
            continue

        # handle GroupCategory.PERFORMANCE (2)
        elif comparison.get("value") == 2:
            group_id = data_condition.condition_group_id

            if group_id not in dcg_logic_type_cache:
                dcg = DataConditionGroup.objects.filter(id=group_id).first()
                if dcg is None:
                    logger.info(
                        "No DataConditionGroup found for DataCondition, skipping",
                        extra={"data_condition_id": data_condition.id},
                    )
                    continue
                dcg_logic_type_cache[group_id] = dcg.logic_type

            logic_type = dcg_logic_type_cache[group_id]

            if logic_type == "all":
                comparison["value"] = 1
                comparison["include"] = False  # Issue category is NOT errors
                data_condition.comparison = comparison
                data_condition.save()
                continue
            else:  # logic type is any, any-short, or none (legacy for does not match all)
                comparison["value"] = 12  # GroupCategory.DB_QUERY
                http_client_comparison: dict[str, object] = {"value": 13}
                front_end_comparison: dict[str, object] = {"value": 14}
                mobile_comparison: dict[str, object] = {"value": 15}

                include = comparison.get("include")
                if include:
                    http_client_comparison["include"] = include
                    front_end_comparison["include"] = include
                    mobile_comparison["include"] = include

                DataCondition.objects.create(
                    type="issue_category",
                    condition_result=True,
                    comparison=http_client_comparison,
                    condition_group_id=data_condition.condition_group_id,
                )
                DataCondition.objects.create(
                    type="issue_category",
                    condition_result=True,
                    comparison=front_end_comparison,
                    condition_group_id=data_condition.condition_group_id,
                )
                DataCondition.objects.create(
                    type="issue_category",
                    condition_result=True,
                    comparison=mobile_comparison,
                    condition_group_id=data_condition.condition_group_id,
                )

                data_condition.comparison = comparison
                data_condition.save()


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("workflow_engine", "0112_drop_redundant_error_detector_workflows"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_data_condition_issue_category,
            reverse_code=migrations.RunPython.noop,
            hints={"tables": ["workflow_engine_data_condition"]},
        ),
    ]
