# Generated by Django 5.2.15 on 2026-09-14 18:00

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.iterators import chunked
from sentry.utils.query import RangeQuerySetWrapperWithProgressBar

BATCH_SIZE = 1000


def replace_boolean_deescalation_comparisons(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    DataCondition = apps.get_model("workflow_engine", "DataCondition")
    conditions = DataCondition.objects.filter(
        type="issue_priority_deescalating",
        comparison=True,
    ).values_list("id", flat=True)

    for condition_ids in chunked(
        RangeQuerySetWrapperWithProgressBar(conditions, step=BATCH_SIZE),
        BATCH_SIZE,
    ):
        DataCondition.objects.filter(id__in=condition_ids).update(comparison=75)


class Migration(CheckedMigration):
    is_post_deployment = True

    dependencies = [
        ("workflow_engine", "0119_add_index_for_all_project_detectors"),
    ]

    operations = [
        migrations.RunPython(
            replace_boolean_deescalation_comparisons,
            reverse_code=migrations.RunPython.noop,
            hints={"tables": ["workflow_engine_datacondition"]},
        ),
    ]
