import {useEffect, useMemo} from 'react';
import {useMatches} from 'react-router';
import {useQuery} from '@tanstack/react-query';

import {usePageFilters} from 'sentry/components/pageFilters/usePageFilters';
import type {Project} from 'sentry/types/project';
import {trackAnalytics} from 'sentry/utils/analytics';
import {getApiUrl} from 'sentry/utils/api/getApiUrl';
import {getRouteStringFromRoutes} from 'sentry/utils/getRouteStringFromRoutes';
import {fetchMutation} from 'sentry/utils/queryClient';
import {useOrganization} from 'sentry/utils/useOrganization';
import {useParams} from 'sentry/utils/useParams';
import {useProjects} from 'sentry/utils/useProjects';
import {usePageContextCapture} from 'sentry/views/seerExplorer/hooks/usePageContextCapture';
import {
  getFallbackSuggestions,
  LEGACY_SUGGESTIONS,
} from 'sentry/views/seerExplorer/suggestionFallbacks';
import type {ChatSuggestion} from 'sentry/views/seerExplorer/types';
import {getSelectedProjectsForLLMContext} from 'sentry/views/seerExplorer/utils/selectedProjectsForLLMContext';

const SUGGESTIONS_TIMEOUT_MS = 4000;
const MAX_PAGE_CONTEXT_LENGTH = 50_000;
const MAX_PROJECTS = 10;

const PROJECT_SENDS_FLAGS = {
  db: 'hasInsightsDb',
  http: 'hasInsightsHttp',
  caches: 'hasInsightsCaches',
  queues: 'hasInsightsQueues',
  vitals: 'hasInsightsVitals',
  app_start: 'hasInsightsAppStart',
  screen_load: 'hasInsightsScreenLoad',
  agent_monitoring: 'hasInsightsAgentMonitoring',
  sessions: 'hasSessions',
  cron_monitors: 'hasMonitors',
  replays: 'hasReplays',
  logs: 'hasLogs',
  profiles: 'hasProfiles',
} as const satisfies Record<string, keyof Project>;

class SuggestionsTimeoutError extends Error {
  constructor() {
    super('Timed out generating suggestions');
    this.name = 'SuggestionsTimeoutError';
  }
}

export type ChatSuggestionsState =
  | {isLoading: true}
  | {
      isLoading: false;
      source: 'generated' | 'fallback' | 'legacy'; // for analytics purposes
      suggestions: ChatSuggestion[];
    };

function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T> {
  return new Promise((resolve, reject) => {
    const timer = window.setTimeout(() => reject(new SuggestionsTimeoutError()), ms);
    promise.then(resolve, reject).finally(() => window.clearTimeout(timer));
  });
}

/**
 * Suggestions for the chat's empty state, generated by Seer from the page the
 * user is on. Falls back to fixed suggestions on timeout, error, or no result.
 */
export function useChatSuggestions({
  enabled,
  allowStructuredContext,
}: {
  allowStructuredContext: boolean;
  enabled: boolean;
}): ChatSuggestionsState {
  const organization = useOrganization({allowNull: true});
  const hasFlag = !!organization?.features.includes('seer-chat-suggestions');
  const route = getRouteStringFromRoutes({matches: useMatches()});
  const params = useParams();
  const {selection} = usePageFilters();
  const {projects} = useProjects();
  const capturePageContext = usePageContextCapture();

  const selectedProjects = useMemo(() => {
    const {selectionMode, projectSlugs} = getSelectedProjectsForLLMContext(
      selection.projects,
      projects
    );
    const slugs = new Set(projectSlugs);
    return selectionMode === 'explicit'
      ? projects.filter(project => slugs.has(project.slug))
      : projects.filter(project => project.isMember).slice(0, MAX_PROJECTS);
  }, [selection.projects, projects]);

  const query = useQuery({
    queryKey: [
      'seer-chat-suggestions',
      organization?.slug,
      route,
      params,
      selectedProjects.map(project => project.slug),
      allowStructuredContext,
    ],
    queryFn: () => {
      const {screenshot: pageContext} = capturePageContext({
        route,
        allowStructured: allowStructuredContext,
      });
      return withTimeout(
        fetchMutation<{suggestions: ChatSuggestion[]}>({
          method: 'POST',
          url: getApiUrl('/organizations/$organizationIdOrSlug/seer/chat-suggestions/', {
            path: {organizationIdOrSlug: organization?.slug ?? ''},
          }),
          data: {
            route,
            route_params: params,
            page_context: (pageContext ?? '').slice(0, MAX_PAGE_CONTEXT_LENGTH),
            projects: selectedProjects.map(project => ({
              slug: project.slug,
              platform: project.platform ?? null,
              sends: Object.entries(PROJECT_SENDS_FLAGS).flatMap(([name, flag]) =>
                project[flag] ? [name] : []
              ),
            })),
          },
        }),
        SUGGESTIONS_TIMEOUT_MS
      );
    },
    enabled: enabled && hasFlag,
    staleTime: 10 * 60 * 1000,
    retry: false,
  });

  const state = useMemo((): ChatSuggestionsState => {
    if (!hasFlag) {
      return {isLoading: false, source: 'legacy', suggestions: LEGACY_SUGGESTIONS};
    }
    if (query.isPending) {
      return {isLoading: true};
    }
    const generated = query.data?.suggestions ?? [];
    if (generated.length > 0) {
      return {isLoading: false, source: 'generated', suggestions: generated};
    }
    return {
      isLoading: false,
      source: 'fallback',
      suggestions: getFallbackSuggestions(route, selectedProjects),
    };
  }, [hasFlag, query.isPending, query.data, route, selectedProjects]);

  useEffect(() => {
    if (!enabled || state.isLoading) {
      return;
    }
    trackAnalytics('seer.explorer.suggestions_shown', {
      organization,
      referrer: route,
      source: state.source,
      fallback_reason:
        state.source === 'fallback'
          ? query.error instanceof SuggestionsTimeoutError
            ? 'timeout'
            : query.isError
              ? 'error'
              : 'empty'
          : undefined,
      count: state.suggestions.length,
      action_types: state.suggestions.flatMap(suggestion =>
        suggestion.action_type ? [suggestion.action_type] : []
      ),
    });
  }, [enabled, state, organization, route, query.error, query.isError]);

  return state;
}
