import {useEffect, useMemo} from 'react';
import {useMatches} from 'react-router';
import {useQuery} from '@tanstack/react-query';

import {ALL_ACCESS_PROJECTS} from 'sentry/components/pageFilters/constants';
import {usePageFilters} from 'sentry/components/pageFilters/usePageFilters';
import {trackAnalytics} from 'sentry/utils/analytics';
import {getApiUrl} from 'sentry/utils/api/getApiUrl';
import {getRouteStringFromRoutes} from 'sentry/utils/getRouteStringFromRoutes';
import {fetchMutation} from 'sentry/utils/queryClient';
import {useOrganization} from 'sentry/utils/useOrganization';
import {useParams} from 'sentry/utils/useParams';
import {useProjects} from 'sentry/utils/useProjects';
import {usePageContextCapture} from 'sentry/views/seerExplorer/hooks/usePageContextCapture';
import {
  getFallbackSuggestions,
  LEGACY_SUGGESTIONS,
} from 'sentry/views/seerExplorer/suggestionFallbacks';
import type {ChatSuggestion} from 'sentry/views/seerExplorer/types';

const SUGGESTIONS_TIMEOUT_MS = 4000;

class SuggestionsTimeoutError extends Error {
  constructor() {
    super('Timed out generating suggestions');
    this.name = 'SuggestionsTimeoutError';
  }
}

export type ChatSuggestionsState =
  | {isLoading: true}
  | {
      isLoading: false;
      source: 'generated' | 'fallback' | 'legacy'; // for analytics purposes
      suggestions: ChatSuggestion[];
    };

function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T> {
  return new Promise((resolve, reject) => {
    const timer = window.setTimeout(() => reject(new SuggestionsTimeoutError()), ms);
    promise.then(resolve, reject).finally(() => window.clearTimeout(timer));
  });
}

/**
 * Suggestions for the chat's empty state, generated by Seer from the page the
 * user is on. Falls back to fixed suggestions on timeout, error, or no result.
 */
export function useChatSuggestions({
  enabled,
  allowStructuredContext,
}: {
  allowStructuredContext: boolean;
  enabled: boolean;
}): ChatSuggestionsState {
  const organization = useOrganization({allowNull: true});
  const hasFlag = !!organization?.features.includes('seer-chat-suggestions');
  const route = getRouteStringFromRoutes({matches: useMatches()});
  const params = useParams();
  const {selection} = usePageFilters();
  const {projects} = useProjects();
  const capturePageContext = usePageContextCapture();

  // For the fallback suggestions: do any pinned projects (or member projects, if none are pinned) send DB data?
  const isProjectSelectionExplicit =
    selection.projects.length > 0 && !selection.projects.includes(ALL_ACCESS_PROJECTS);
  const hasDbData = projects.some(
    project =>
      project.hasInsightsDb &&
      (isProjectSelectionExplicit
        ? selection.projects.includes(Number(project.id))
        : project.isMember)
  );

  const query = useQuery({
    queryKey: [
      'seer-chat-suggestions',
      organization?.slug,
      route,
      params,
      selection.projects,
      allowStructuredContext,
    ],
    queryFn: () => {
      const {screenshot: pageContext} = capturePageContext({
        route,
        allowStructured: allowStructuredContext,
      });
      return withTimeout(
        fetchMutation<{suggestions: ChatSuggestion[]}>({
          method: 'POST',
          url: getApiUrl('/organizations/$organizationIdOrSlug/seer/chat-suggestions/', {
            path: {organizationIdOrSlug: organization?.slug ?? ''},
          }),
          data: {
            route,
            route_params: params,
            page_context: pageContext ?? '',
            project_ids: selection.projects,
          },
        }),
        SUGGESTIONS_TIMEOUT_MS
      );
    },
    enabled: enabled && hasFlag,
    staleTime: 10 * 60 * 1000,
    retry: false,
  });

  const state = useMemo((): ChatSuggestionsState => {
    if (!hasFlag) {
      return {isLoading: false, source: 'legacy', suggestions: LEGACY_SUGGESTIONS};
    }
    if (query.isPending) {
      return {isLoading: true};
    }
    const generated = query.data?.suggestions ?? [];
    if (generated.length > 0) {
      return {isLoading: false, source: 'generated', suggestions: generated};
    }
    return {
      isLoading: false,
      source: 'fallback',
      suggestions: getFallbackSuggestions(route, hasDbData),
    };
  }, [hasFlag, query.isPending, query.data, route, hasDbData]);

  useEffect(() => {
    if (!enabled || state.isLoading) {
      return;
    }
    trackAnalytics('seer.explorer.suggestions_shown', {
      organization,
      referrer: route,
      source: state.source,
      fallback_reason:
        state.source === 'fallback'
          ? query.error instanceof SuggestionsTimeoutError
            ? 'timeout'
            : query.isError
              ? 'error'
              : 'empty'
          : undefined,
      count: state.suggestions.length,
      action_types: state.suggestions.flatMap(suggestion =>
        suggestion.action_type ? [suggestion.action_type] : []
      ),
    });
  }, [enabled, state, organization, route, query.error, query.isError]);

  return state;
}
