ORGANIZATION_RELEASE_DETAILS_SCHEMA = {
    "type": "object",
    "required": [
        "id",
        "version",
        "dateCreated",
        "dateFinished",
        "status",
        "lastDeploy",
        "deployCount",
        "commitCount",
        "data",
        "newGroups",
        "versionInfo",
        "projects",
        "owner",
        "authors",
        "commitAuthors",
        "commitAuthorStats",
        "commitFilesChanged",
        "commitCountTrend",
        "deployments",
        "sessions",
        "adoptionStages",
        "prevReleaseVersion",
        "nextReleaseVersion",
        "firstReleaseVersion",
        "lastReleaseVersion",
    ],
    "properties": {
        "id": {"type": "integer"},
        "version": {"type": "string"},
        "url": {"type": "string", "nullable": True},
        "dateCreated": {"type": "string", "format": "date-time"},
        "dateReleased": {"type": "string", "format": "date-time", "nullable": True},
        "dateStarted": {"type": "string", "format": "date-time", "nullable": True},
        "dateFinished": {"type": "string", "format": "date-time"},
        "ref": {"type": "string", "nullable": True},
        "status": {"type": "string"},
        "lastDeploy": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "environment": {"type": "string"},
                "dateStarted": {"type": "string", "format": "date-time", "nullable": True},
                "dateFinished": {"type": "string", "format": "date-time"},
                "name": {"type": "string"},
                "url": {"type": "string", "nullable": True},
            },
        },
        "deployCount": {"type": "integer"},
        "commitCount": {"type": "integer"},
        "data": {"type": "object"},
        "newGroups": {"type": "integer"},
        "versionInfo": {
            "type": "object",
            "properties": {
                "package": {"type": "string"},
                "version": {"type": "object", "properties": {"raw": {"type": "string"}}},
                "description": {"type": "string"},
                "buildHash": {"type": "string"},
            },
        },
        "projects": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "integer"},
                    "slug": {"type": "string"},
                    "name": {"type": "string"},
                    "newGroups": {"type": "integer"},
                    "platform": {"type": "string"},
                    "platforms": {"type": "array", "items": {"type": "string"}},
                    "hasHealthData": {"type": "boolean"},
                    "healthData": {
                        "type": "object",
                        "properties": {
                            "durationP50": {"type": "number", "nullable": True},
                            "durationP90": {"type": "number", "nullable": True},
                            "crashFreeUsers": {"type": "number", "nullable": True},
                            "crashFreeSessions": {"type": "number", "nullable": True},
                            "sessionsCrashed": {"type": "integer"},
                            "sessionsErrored": {"type": "integer"},
                            "totalUsers": {"type": "integer", "nullable": True},
                            "totalUsers24h": {"type": "integer", "nullable": True},
                            "totalProjectUsers24h": {"type": "integer", "nullable": True},
                            "totalSessions": {"type": "integer", "nullable": True},
                            "totalSessions24h": {"type": "integer", "nullable": True},
                            "totalProjectSessions24h": {"type": "integer", "nullable": True},
                            "adoption": {"type": "number", "nullable": True},
                            "sessionsAdoption": {"type": "number", "nullable": True},
                            "stats": {
                                "type": "object",
                            },
                        },
                    },
                    "firstEvent": {"type": "string", "nullable": True},
                    "lastEvent": {"type": "string", "nullable": True},
                    "currentProjectMeta": {"type": "object"},
                },
            },
        },
        "owner": {"type": "string", "nullable": True},
        "authors": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "integer"},
                    "name": {"type": "string"},
                    "username": {"type": "string"},
                    "email": {"type": "string"},
                    "avatarUrl": {"type": "string"},
                    "isActive": {"type": "boolean"},
                    "hasPasswordAuth": {"type": "boolean"},
                    "isManaged": {"type": "boolean"},
                    "dateJoined": {"type": "string", "format": "date-time"},
                    "lastLogin": {"type": "string", "format": "date-time"},
                    "has2fa": {"type": "boolean"},
                    "lastActive": {"type": "string", "format": "date-time"},
                    "isSuperuser": {"type": "boolean"},
                    "isStaff": {"type": "boolean"},
                    "experiments": {"type": "object"},
                    "emails": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {"type": "integer"},
                                "email": {"type": "string"},
                                "is_verified": {"type": "boolean"},
                            },
                        },
                    },
                    "avatar": {
                        "type": "object",
                        "properties": {
                            "avatarType": {"type": "string"},
                            "avatarUuid": {"type": "string"},
                            "avatarUrl": {"type": "string"},
                        },
                    },
                },
            },
        },
        "commitAuthors": {"type": "array", "items": {"type": "string"}},
        "commitAuthorStats": {"type": "array", "items": {"type": "object"}},
        "commitFilesChanged": {"type": "array", "items": {"type": "object"}},
        "commitCountTrend": {"type": "array", "items": {"type": "object"}},
        "deployments": {"type": "array", "items": {"type": "object"}},
        "firstEvent": {"type": "string", "nullable": True},
        "lastEvent": {"type": "string", "nullable": True},
        "sessions": {"type": "object"},
        "adoptionStages": {
            "type": "object",
            "properties": {
                "sentry": {
                    "type": "object",
                    "properties": {
                        "stage": {"type": "string"},
                        "adopted": {"type": "integer", "nullable": True},
                        "unadopted": {"type": "integer", "nullable": True},
                    },
                }
            },
        },
        "prevReleaseVersion": {"type": "string", "nullable": True},
        "nextReleaseVersion": {"type": "string", "nullable": True},
        "firstReleaseVersion": {"type": "string", "nullable": True},
        "lastReleaseVersion": {"type": "string", "nullable": True},
    },
}
