from typing import Literal

from pydantic import BaseModel, Field


class SolutionStep(BaseModel):
    """A single step in the solution plan."""

    title: str = Field(description="Short, concrete title for this step")
    description: str = Field(
        description="One line description of what specifically needs to be done"
    )


class ImpactItem(BaseModel):
    """An item describing impact of the issue."""

    label: str = Field(
        description="What specific thing is impacted (e.g., 'User Authentication', 'Payment Flow')"
    )
    rating: Literal["low", "medium", "high"] = Field(
        description="Rating of the impact. High is an urgent incident, medium is a significant but non-urgent problem, low is a minor issue or no impact at all."
    )
    impact_description: str = Field(description="One line describing the impact under 20 words")
    evidence: str = Field(description="Evidence for this impact assessment under 20 words")


class SuspectCommit(BaseModel):
    """A commit that may have introduced the issue."""

    sha: str = Field(description="Git commit SHA (7+ characters)")
    repo_name: str = Field(description="Full repository name, e.g. 'getsentry/sentry'")
    message: str = Field(description="Commit message/title")
    author_name: str = Field(description="Name of the commit author")
    author_email: str = Field(description="Email of the commit author")
    committed_date: str = Field(description="Commit date in YYYY-MM-DD format")
    description: str = Field(
        description="Why this commit is suspected of causing the issue, under 20 words"
    )


class SuggestedAssignee(BaseModel):
    """A suggested person to assign the issue to."""

    name: str = Field(description="Name of the suggested assignee")
    email: str = Field(description="Email of the suggested assignee")
    why: str = Field(description="Reason for suggesting this person, under 20 words")


# Artifact schemas for each step


class RootCauseArtifact(BaseModel):
    """Root cause analysis artifact generated by the Explorer agent."""

    one_line_description: str = Field(
        description="A concise summary of the root cause in under 30 words"
    )
    five_whys: list[str] = Field(
        description="Chain of one line 'why' statements, each under 15 words, leading to the root cause"
    )
    reproduction_steps: list[str] = Field(
        default_factory=list, description="Steps to reproduce the issue"
    )


class SolutionArtifact(BaseModel):
    """Solution plan artifact generated by the Explorer agent."""

    one_line_summary: str = Field(description="A concise summary of the solution in under 30 words")
    steps: list[SolutionStep] = Field(
        description="Ordered list of steps, each under 20 words, to implement the solution"
    )


class ImpactAssessmentArtifact(BaseModel):
    """Impact assessment artifact generated by the Explorer agent."""

    one_line_description: str = Field(
        description="A concise summary of the overall impact in under 30 words"
    )
    impacts: list[ImpactItem] = Field(
        description="List of specific impacts with labels and descriptions"
    )


class TriageArtifact(BaseModel):
    """Triage artifact generated by the Explorer agent."""

    suspect_commit: SuspectCommit | None = Field(
        default=None, description="Suspected commit that introduced the issue, if identified"
    )
    suggested_assignee: SuggestedAssignee | None = Field(
        default=None, description="Suggested person to assign the issue to, if determined"
    )


# Note: CodeChanges step does not have an artifact schema.
# Code changes are read directly from the Explorer state's file_patches.
