import {CHART_PALETTE} from 'sentry/constants/chartPalette';

export const THROUGHPUT_COLOR = CHART_PALETTE[3][3];
export const P50_COLOR = CHART_PALETTE[3][1];
export const P95_COLOR = CHART_PALETTE[0][0];
export const AVG_COLOR = CHART_PALETTE[0][0];
export const ERRORS_COLOR = CHART_PALETTE[5][3];

export const COLD_START_COLOR = CHART_PALETTE[5][4];
export const WARM_START_COLOR = CHART_PALETTE[5][5];

export const RELEASE_COMPARISON = {
  PRIMARY_RELEASE_COLOR: CHART_PALETTE[0][0],
  SECONDARY_RELEASE_COLOR: CHART_PALETTE[5][3],
};
