import styled from '@emotion/styled';

import {
  Container,
  type ContainerElement,
  type ContainerProps,
} from '@sentry/scraps/layout/container';

import type {SurfaceVariant} from 'sentry/utils/theme';

import {getBorder, getRadius, rc} from './styles';

interface FlatSurfaceProps<T extends ContainerElement = 'div'> extends Omit<
  ContainerProps<T>,
  'background' | 'border'
> {
  elevation?: never;
  variant?: SurfaceVariant;
}

interface OverlaySurfaceProps<T extends ContainerElement = 'div'> extends Omit<
  ContainerProps<T>,
  'background' | 'border'
> {
  variant: 'overlay';
  elevation?: 'low' | 'medium' | 'high';
}

interface FlatSurfacePropsWithRenderFunction {
  children: (props: {className: string}) => React.ReactNode;
  elevation?: never;
  variant?: SurfaceVariant;
}

interface OverlaySurfacePropsWithRenderFunction {
  children: (props: {className: string}) => React.ReactNode;
  variant: 'overlay';
  elevation?: 'low' | 'medium' | 'high';
}

type SurfaceProps<T extends ContainerElement = 'div'> =
  | FlatSurfaceProps<T>
  | OverlaySurfaceProps<T>;

/**
 * Surface is a layout primitive that provides background colors and optional elevation
 * shadows for layered UI elements. It extends Container with variant-specific styling.
 *
 * @param variant - Surface background variant:
 *   - `primary` | `secondary` | `tertiary`: Flat surfaces with no elevation
 *   - `overlay`: Elevated surface with shadow (e.g., modals, popovers, dropdowns)
 *
 * @param elevation - Shadow depth for overlay variant only. Defaults to `low` for overlays.
 *   - `low`: Subtle shadow for slightly elevated content (default)
 *   - `medium`: Raised shadow for interactive overlays
 *   - `high`: Prominent shadow for modals and dialogs
 *
 * @param radius - Border radius size. Defaults to `md` for overlay variant, no default for others.
 *
 * @example
 * // Flat surface
 * <Surface variant="primary">Content</Surface>
 *
 * // Elevated overlay with low elevation (default)
 * <Surface variant="overlay" elevation="low">Tooltip content</Surface>
 *
 * // Elevated overlay with medium elevation
 * <Surface variant="overlay" elevation="low">Tooltip content</Surface>
 *
 * // Elevated overlay with high elevation
 * <Surface variant="overlay" elevation="high">Modal content</Surface>
 *
 */

function isRenderFunction(
  props:
    | SurfaceProps<any>
    | FlatSurfacePropsWithRenderFunction
    | OverlaySurfacePropsWithRenderFunction
): props is FlatSurfacePropsWithRenderFunction | OverlaySurfacePropsWithRenderFunction {
  return typeof props.children === 'function';
}

export const Surface = styled(
  <T extends ContainerElement = 'div'>(
    props:
      | SurfaceProps<T>
      | FlatSurfacePropsWithRenderFunction
      | OverlaySurfacePropsWithRenderFunction
  ) => {
    if (isRenderFunction(props)) {
      // When using render prop, only pass className to the child function. T
      // The className in this case is internally generated by emotion, and not part of the
      // passed props.
      return props.children({className: (props as any).className ?? ''});
    }

    const {variant, elevation: _, ...rest} = props;
    if (variant === 'overlay') {
      return <Container border="primary" radius={rest.radius ?? 'md'} {...rest} />;
    }
    return <Container radius={rest.radius} {...rest} />;
  }
)<SurfaceProps<any>>`
  ${p =>
    rc('background', p.variant, p.theme, v =>
      v ? p.theme.tokens.background[v] : undefined
    )};
  ${p =>
    rc('border', p.variant === 'overlay' ? 'primary' : undefined, p.theme, getBorder)};
  ${p =>
    rc(
      'border-radius',
      p.radius ?? (p.variant === 'overlay' ? 'md' : undefined),
      p.theme,
      getRadius
    )};
  ${p =>
    rc(
      'box-shadow',
      p.elevation ?? (p.variant === 'overlay' ? ('low' as const) : undefined),
      p.theme,
      v => (v ? p.theme.shadow[v] : undefined)
    )};
` as unknown as <T extends ContainerElement = 'div'>(
  props:
    | SurfaceProps<T>
    | FlatSurfacePropsWithRenderFunction
    | OverlaySurfacePropsWithRenderFunction
) => React.ReactElement;
