# Generated by Django 5.2.12 on 2026-03-13

from sentry.new_migrations.migrations import CheckedMigration
from sentry.new_migrations.monkey.models import SafeDeleteModel
from sentry.new_migrations.monkey.state import DeletionAction


class Migration(CheckedMigration):
    is_post_deployment = False

    dependencies = [
        ("seer", "0004_pending_delete_seerorganizationsettings"),
    ]

    operations = [
        SafeDeleteModel(
            name="SeerOrganizationSettings",
            deletion_action=DeletionAction.DELETE,
        ),
    ]
