# Generated by Django 5.2.12 on 2026-05-05 02:03

from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration
from sentry.new_migrations.monkey.fields import SafeRemoveField
from sentry.new_migrations.monkey.state import DeletionAction


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("seer", "0009_genericize_night_shift_results"),
    ]

    operations = [
        SafeRemoveField(
            model_name="seernightshiftrunresult",
            name="action",
            deletion_action=DeletionAction.DELETE,
        ),
        SafeRemoveField(
            model_name="seernightshiftrun",
            name="triage_strategy",
            deletion_action=DeletionAction.DELETE,
        ),
        SafeRemoveField(
            model_name="seernightshiftrun",
            name="error_message",
            deletion_action=DeletionAction.DELETE,
        ),
        migrations.AlterField(
            model_name="seernightshiftrunresult",
            name="kind",
            field=models.CharField(max_length=256),
        ),
    ]
