# Generated by Django 5.2.14 on 2026-06-12 17:07
import logging

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.numbers import validate_bigint
from sentry.utils.query import RangeQuerySetWrapperWithProgressBar

logger = logging.getLogger(__name__)


def _parse_group_id(value: object) -> int | None:
    # str.isdigit() is unsafe here — it accepts unicode digits int() rejects — so
    # parse with int() and bounds-check that it fits the bigint group_id column.
    if not isinstance(value, str):
        return None
    try:
        group_id = int(value)
    except ValueError:
        return None
    return group_id if validate_bigint(group_id) else None


def backfill_seer_agent_run_group_id(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    SeerAgentRun = apps.get_model("seer", "SeerAgentRun")
    Group = apps.get_model("sentry", "Group")

    # For autofix runs extras["category_value"] is the stringified group id, set
    # only recently — recover it for historical rows, but only link a group that
    # belongs to the run's own org (never trust the value across the tenant
    # boundary). (agent_run_id, run_org_id, candidate_group_id) per row.
    candidates: list[tuple[int, int, int]] = []
    skipped_bad_value = 0

    # Only autofix rows store a group id in category_value; other sources (e.g.
    # dashboard_generate) put unrelated ids there, so this filter is load-bearing.
    queryset = SeerAgentRun.objects.filter(
        source="autofix",
        group_id__isnull=True,
    ).values_list("id", "run__organization_id", "extras")

    for agent_run_id, run_org_id, extras in RangeQuerySetWrapperWithProgressBar(
        queryset, result_value_getter=lambda values: values[0]
    ):
        group_id = _parse_group_id((extras or {}).get("category_value"))
        if group_id is None:
            skipped_bad_value += 1
            continue
        candidates.append((agent_run_id, run_org_id, group_id))

    group_org: dict[int, int] = {}
    candidate_group_ids = sorted({group_id for _, _, group_id in candidates})
    for i in range(0, len(candidate_group_ids), 5000):
        chunk = candidate_group_ids[i : i + 5000]
        for group_id, org_id in Group.objects.filter(id__in=chunk).values_list(
            "id", "project__organization_id"
        ):
            group_org[group_id] = org_id

    batch: list[object] = []
    skipped_missing_group = 0
    skipped_org_mismatch = 0
    linked = 0

    for agent_run_id, run_org_id, group_id in candidates:
        org_id = group_org.get(group_id)
        if org_id is None:
            skipped_missing_group += 1
            continue
        if org_id != run_org_id:
            skipped_org_mismatch += 1
            continue

        batch.append(SeerAgentRun(id=agent_run_id, group_id=group_id))
        linked += 1

        if len(batch) >= 1000:
            SeerAgentRun.objects.bulk_update(batch, ["group_id"])
            batch = []

    if batch:
        SeerAgentRun.objects.bulk_update(batch, ["group_id"])

    logger.info(
        "backfill_seer_agent_run_group_id.done",
        extra={
            "linked": linked,
            "skipped_bad_value": skipped_bad_value,
            "skipped_missing_group": skipped_missing_group,
            "skipped_org_mismatch": skipped_org_mismatch,
        },
    )


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("seer", "0017_drop_old_fk_columns"),
        # Reads sentry.Group (and Project for org) to validate tenant ownership.
        ("sentry", "1114_extend_repository_url_length"),
    ]

    operations = [
        migrations.RunPython(
            backfill_seer_agent_run_group_id,
            reverse_code=migrations.RunPython.noop,
            hints={"tables": ["seer_seeragentrun"]},
        ),
    ]
