# Generated by Django 5.2.14 on 2026-06-22 14:53
import logging

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import Model

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.query import RangeQuerySetWrapperWithProgressBar

logger = logging.getLogger(__name__)


def backfill_night_shift_run_shards(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    SeerNightShiftRun = apps.get_model("seer", "SeerNightShiftRun")
    SeerNightShiftRunShard = apps.get_model("seer", "SeerNightShiftRunShard")

    # Pre-shard runs carry a single scalar seer_run and no shard rows. Give each
    # one a shard so delivery resolves it through shards, letting the legacy
    # seer_run read-fallback be removed. Runs that already have a shard are
    # excluded, so this is safe to re-run.
    queryset = SeerNightShiftRun.objects.filter(
        seer_run_id__isnull=False,
        shards__isnull=True,
    ).values_list("id", "seer_run_id")

    batch: list[Model] = []
    created = 0
    for run_id, seer_run_id in RangeQuerySetWrapperWithProgressBar(
        queryset, result_value_getter=lambda values: values[0]
    ):
        batch.append(SeerNightShiftRunShard(run_id=run_id, seer_run_id=seer_run_id))
        created += 1
        if len(batch) >= 1000:
            # ignore_conflicts guards the shard's unique seer_run if a row was
            # added concurrently between the scan and the write.
            SeerNightShiftRunShard.objects.bulk_create(batch, ignore_conflicts=True)
            batch = []

    if batch:
        SeerNightShiftRunShard.objects.bulk_create(batch, ignore_conflicts=True)

    logger.info("backfill_night_shift_run_shards.done", extra={"shards_created": created})


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("seer", "0019_add_night_shift_run_shard"),
    ]

    operations = [
        migrations.RunPython(
            backfill_night_shift_run_shards,
            reverse_code=migrations.RunPython.noop,
            hints={"tables": ["seer_nightshiftrunshard"]},
        ),
    ]
