import {t} from 'sentry/locale';
import {DisplayType, WidgetType} from 'sentry/views/dashboards/types';
import {type PrebuiltDashboard} from 'sentry/views/dashboards/utils/prebuiltConfigs';
import {DEFAULT_QUERY_FILTER} from 'sentry/views/insights/browser/webVitals/settings';

export const WEB_VITALS_SUMMARY_PREBUILT_CONFIG: PrebuiltDashboard = {
  dateCreated: '',
  projects: [],
  title: 'Web Vitals Page Summary',
  filters: {
    globalFilter: [],
  },
  widgets: [
    {
      id: 'score-breakdown-chart',
      title: t('Score Breakdown'),
      displayType: DisplayType.AREA,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: [
            'performance_score(measurements.score.lcp)',
            'performance_score(measurements.score.fcp)',
            'performance_score(measurements.score.inp)',
            'performance_score(measurements.score.cls)',
            'performance_score(measurements.score.ttfb)',
          ],
          aggregates: [
            'performance_score(measurements.score.lcp)',
            'performance_score(measurements.score.fcp)',
            'performance_score(measurements.score.inp)',
            'performance_score(measurements.score.cls)',
            'performance_score(measurements.score.ttfb)',
          ],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 0,
        w: 5,
        h: 2,
        x: 0,
        minH: 2,
      },
    },
    {
      id: 'score-breakdown-wheel',
      title: t('Performance Score'),
      displayType: DisplayType.WHEEL,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: [
            'performance_score(measurements.score.lcp)',
            'performance_score(measurements.score.fcp)',
            'performance_score(measurements.score.inp)',
            'performance_score(measurements.score.cls)',
            'performance_score(measurements.score.ttfb)',
            'performance_score(measurements.score.total)',
            'count_scores(measurements.score.total)',
            'count_scores(measurements.score.lcp)',
            'count_scores(measurements.score.fcp)',
            'count_scores(measurements.score.inp)',
            'count_scores(measurements.score.cls)',
            'count_scores(measurements.score.ttfb)',
          ],
          aggregates: [],
          columns: [
            'performance_score(measurements.score.lcp)',
            'performance_score(measurements.score.fcp)',
            'performance_score(measurements.score.inp)',
            'performance_score(measurements.score.cls)',
            'performance_score(measurements.score.ttfb)',
            'performance_score(measurements.score.total)',
            'count_scores(measurements.score.total)',
            'count_scores(measurements.score.lcp)',
            'count_scores(measurements.score.fcp)',
            'count_scores(measurements.score.inp)',
            'count_scores(measurements.score.cls)',
            'count_scores(measurements.score.ttfb)',
          ],
          orderby: '',
        },
      ],
      layout: {
        y: 0,
        w: 1,
        h: 2,
        x: 5,
        minH: 2,
      },
    },
    {
      id: 'lcp-score-meter',
      title: t('Largest Contentful Paint'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.lcp)', 'avg(measurements.score.ratio.lcp)'],
          aggregates: ['p75(measurements.lcp)', 'avg(measurements.score.ratio.lcp)'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 0,
        minH: 1,
      },
    },
    {
      id: 'fcp-score-meter',
      title: t('First Contentful Paint'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.fcp)', 'avg(measurements.score.ratio.fcp)'],
          aggregates: ['p75(measurements.fcp)', 'avg(measurements.score.ratio.fcp)'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 1,
        minH: 1,
      },
    },
    {
      id: 'inp-score-meter',
      title: t('Interaction to Next Paint'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.inp)', 'avg(measurements.score.ratio.inp)'],
          aggregates: ['p75(measurements.inp)', 'avg(measurements.score.ratio.inp)'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 2,
        minH: 1,
      },
    },
    {
      id: 'cls-score-meter',
      title: t('Cumulative Layout Shift'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.cls)', 'avg(measurements.score.ratio.cls)'],
          aggregates: ['p75(measurements.cls)', 'avg(measurements.score.ratio.cls)'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 3,
        minH: 1,
      },
    },
    {
      id: 'ttfb-score-meter',
      title: t('Time To First Byte'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.ttfb)', 'avg(measurements.score.ratio.ttfb)'],
          aggregates: ['p75(measurements.ttfb)', 'avg(measurements.score.ratio.ttfb)'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 4,
        minH: 1,
      },
    },
    {
      id: 'pageloads-chart',
      title: t('Pageloads'),
      displayType: DisplayType.LINE,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: `span.op:pageload`,
          fields: ['count()'],
          aggregates: ['count()'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 2,
        w: 1,
        h: 2,
        x: 5,
        minH: 2,
      },
    },
    {
      id: 'interactions-chart',
      title: t('Interactions'),
      displayType: DisplayType.LINE,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: `span.op:[ui.interaction.click,ui.interaction.hover,ui.interaction.drag,ui.interaction.press]`,
          fields: ['count()'],
          aggregates: ['count()'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 4,
        w: 1,
        h: 2,
        x: 5,
        minH: 2,
      },
    },
  ],
};
