import {t} from 'sentry/locale';
import {DisplayType, WidgetType} from 'sentry/views/dashboards/types';
import {type PrebuiltDashboard} from 'sentry/views/dashboards/utils/prebuiltConfigs';
import {ISSUE_TYPES} from 'sentry/views/dashboards/utils/prebuiltConfigs/webVitals/webVitals';
import {DEFAULT_QUERY_FILTER} from 'sentry/views/insights/browser/webVitals/settings';

export const WEB_VITALS_SUMMARY_PREBUILT_CONFIG: PrebuiltDashboard = {
  dateCreated: '',
  projects: [],
  title: 'Web Vitals Page Summary',
  filters: {
    globalFilter: [],
  },
  widgets: [
    {
      id: 'score-breakdown-chart',
      title: t('Score Breakdown'),
      displayType: DisplayType.AREA,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: [
            'performance_score(measurements.score.lcp)',
            'performance_score(measurements.score.fcp)',
            'performance_score(measurements.score.inp)',
            'performance_score(measurements.score.cls)',
            'performance_score(measurements.score.ttfb)',
          ],
          aggregates: [
            'performance_score(measurements.score.lcp)',
            'performance_score(measurements.score.fcp)',
            'performance_score(measurements.score.inp)',
            'performance_score(measurements.score.cls)',
            'performance_score(measurements.score.ttfb)',
          ],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 0,
        w: 5,
        h: 2,
        x: 0,
        minH: 2,
      },
    },
    {
      id: 'score-breakdown-wheel',
      title: t('Performance Score'),
      displayType: DisplayType.WHEEL,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: [
            'performance_score(measurements.score.lcp)',
            'performance_score(measurements.score.fcp)',
            'performance_score(measurements.score.inp)',
            'performance_score(measurements.score.cls)',
            'performance_score(measurements.score.ttfb)',
            'performance_score(measurements.score.total)',
            'count_scores(measurements.score.total)',
            'count_scores(measurements.score.lcp)',
            'count_scores(measurements.score.fcp)',
            'count_scores(measurements.score.inp)',
            'count_scores(measurements.score.cls)',
            'count_scores(measurements.score.ttfb)',
          ],
          aggregates: [],
          columns: [
            'performance_score(measurements.score.lcp)',
            'performance_score(measurements.score.fcp)',
            'performance_score(measurements.score.inp)',
            'performance_score(measurements.score.cls)',
            'performance_score(measurements.score.ttfb)',
            'performance_score(measurements.score.total)',
            'count_scores(measurements.score.total)',
            'count_scores(measurements.score.lcp)',
            'count_scores(measurements.score.fcp)',
            'count_scores(measurements.score.inp)',
            'count_scores(measurements.score.cls)',
            'count_scores(measurements.score.ttfb)',
          ],
          orderby: '',
        },
      ],
      layout: {
        y: 0,
        w: 1,
        h: 2,
        x: 5,
        minH: 2,
      },
    },
    {
      id: 'lcp-p75-meter',
      title: t('P75 Largest Contentful Paint'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.lcp)'],
          aggregates: ['p75(measurements.lcp)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 1200,
          max2: 2400,
        },
        unit: null,
      },
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 0,
        minH: 1,
      },
    },
    {
      id: 'fcp-p75-meter',
      title: t('P75 First Contentful Paint'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.fcp)'],
          aggregates: ['p75(measurements.fcp)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 900,
          max2: 1600,
        },
        unit: null,
      },
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 1,
        minH: 1,
      },
    },
    {
      id: 'inp-p75-meter',
      title: t('P75 Interaction to Next Paint'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.inp)'],
          aggregates: ['p75(measurements.inp)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 200,
          max2: 500,
        },
        unit: null,
      },
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 2,
        minH: 1,
      },
    },
    {
      id: 'cls-p75-meter',
      title: t('P75 Cumulative Layout Shift'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.cls)'],
          aggregates: ['p75(measurements.cls)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 0.1,
          max2: 0.25,
        },
        unit: null,
      },
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 3,
        minH: 1,
      },
    },
    {
      id: 'ttfb-p75-meter',
      title: t('P75 Time To First Byte'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.ttfb)'],
          aggregates: ['p75(measurements.ttfb)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 200,
          max2: 400,
        },
        unit: 'millisecond',
      },
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 4,
        minH: 1,
      },
    },
    {
      id: 'lcp-score-meter',
      title: t('Largest Contentful Paint Score'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['avg(measurements.score.ratio.lcp)'],
          aggregates: ['avg(measurements.score.ratio.lcp)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 0.5,
          max2: 0.9,
        },
        unit: null,
        preferredPolarity: '+',
      },
      layout: {
        y: 3,
        w: 1,
        h: 1,
        x: 0,
        minH: 1,
      },
    },
    {
      id: 'fcp-score-meter',
      title: t('First Contentful Paint Score'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['avg(measurements.score.ratio.fcp)'],
          aggregates: ['avg(measurements.score.ratio.fcp)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 0.5,
          max2: 0.9,
        },
        unit: null,
        preferredPolarity: '+',
      },
      layout: {
        y: 3,
        w: 1,
        h: 1,
        x: 1,
        minH: 1,
      },
    },
    {
      id: 'inp-score-meter',
      title: t('Interaction to Next Paint Score'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['avg(measurements.score.ratio.inp)'],
          aggregates: ['avg(measurements.score.ratio.inp)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 0.5,
          max2: 0.9,
        },
        unit: null,
        preferredPolarity: '+',
      },
      layout: {
        y: 3,
        w: 1,
        h: 1,
        x: 2,
        minH: 1,
      },
    },
    {
      id: 'cls-score-meter',
      title: t('Cumulative Layout Shift Score'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['avg(measurements.score.ratio.cls)'],
          aggregates: ['avg(measurements.score.ratio.cls)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 0.5,
          max2: 0.9,
        },
        unit: null,
        preferredPolarity: '+',
      },
      layout: {
        y: 3,
        w: 1,
        h: 1,
        x: 3,
        minH: 1,
      },
    },
    {
      id: 'ttfb-score-meter',
      title: t('Time To First Byte Score'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['avg(measurements.score.ratio.ttfb)'],
          aggregates: ['avg(measurements.score.ratio.ttfb)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 0.5,
          max2: 0.9,
        },
        unit: null,
        preferredPolarity: '+',
      },
      layout: {
        y: 3,
        w: 1,
        h: 1,
        x: 4,
        minH: 1,
      },
    },

    {
      id: 'issues-table',
      title: t('Web Vital Issues'),
      displayType: DisplayType.TABLE,
      widgetType: WidgetType.ISSUE,
      interval: '5m',
      tableWidths: [-1, 100, -1],
      queries: [
        {
          name: '',
          conditions: `issue.type:[${ISSUE_TYPES.join(',')}]`,
          fields: ['issue', 'assignee', 'title'],
          aggregates: [],
          columns: ['issue', 'assignee', 'title'],
          orderby: 'date',
        },
      ],
      layout: {
        y: 4,
        w: 5,
        h: 2,
        x: 0,
        minH: 2,
      },
    },
    {
      id: 'lcp-samples-table',
      title: t('LCP Samples'),
      displayType: DisplayType.TABLE,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: `has:measurements.lcp`,
          fields: [
            'trace',
            'lcp.element',
            'measurements.lcp',
            'profile.id',
            'replay.id',
            'measurements.score.ratio.lcp',
            'timestamp',
          ],
          aggregates: [],
          columns: [
            'trace',
            'lcp.element',
            'measurements.lcp',
            'profile.id',
            'replay.id',
            'measurements.score.ratio.lcp',
            'timestamp',
          ],
          orderby: '-timestamp',
        },
      ],
      layout: {
        y: 6,
        w: 5,
        h: 2,
        x: 0,
        minH: 2,
      },
    },
    {
      id: 'inp-samples-table',
      title: t('INP Samples'),
      displayType: DisplayType.TABLE,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: `has:measurements.inp`,
          fields: [
            'trace',
            'measurements.inp',
            'profile.id',
            'replay.id',
            'measurements.score.ratio.inp',
            'timestamp',
          ],
          aggregates: [],
          columns: [
            'trace',
            'measurements.inp',
            'profile.id',
            'replay.id',
            'measurements.score.ratio.inp',
            'timestamp',
          ],
          orderby: '-timestamp',
        },
      ],
      layout: {
        y: 8,
        w: 5,
        h: 2,
        x: 0,
        minH: 2,
      },
    },
    {
      id: 'cls-samples-table',
      title: t('CLS Samples'),
      displayType: DisplayType.TABLE,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: `has:measurements.cls`,
          fields: [
            'trace',
            'measurements.cls',
            'profile.id',
            'replay.id',
            'measurements.score.ratio.cls',
            'timestamp',
          ],
          aggregates: [],
          columns: [
            'trace',
            'measurements.cls',
            'profile.id',
            'replay.id',
            'measurements.score.ratio.cls',
            'timestamp',
          ],
          orderby: '-timestamp',
        },
      ],
      layout: {
        y: 10,
        w: 5,
        h: 2,
        x: 0,
        minH: 2,
      },
    },
    {
      id: 'pageloads-chart',
      title: t('Pageloads'),
      displayType: DisplayType.LINE,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: `span.op:pageload`,
          fields: ['count()'],
          aggregates: ['count()'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 2,
        w: 1,
        h: 2,
        x: 5,
        minH: 2,
      },
    },
    {
      id: 'interactions-chart',
      title: t('Interactions'),
      displayType: DisplayType.LINE,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: `span.op:[ui.interaction.click,ui.interaction.hover,ui.interaction.drag,ui.interaction.press]`,
          fields: ['count()'],
          aggregates: ['count()'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 4,
        w: 1,
        h: 2,
        x: 5,
        minH: 2,
      },
    },
  ],
};
