import {t} from 'sentry/locale';
import {FieldKind} from 'sentry/utils/fields';
import {DisplayType, WidgetType} from 'sentry/views/dashboards/types';
import {type PrebuiltDashboard} from 'sentry/views/dashboards/utils/prebuiltConfigs';
import {DEFAULT_QUERY_FILTER} from 'sentry/views/insights/browser/webVitals/settings';
import {SpanFields} from 'sentry/views/insights/types';

const ISSUE_TYPES = [
  'web_vitals',
  'performance_render_blocking_asset_span',
  'performance_uncompressed_assets',
  'performance_http_overhead',
  'performance_consecutive_http',
  'performance_n_plus_one_api_calls',
  'performance_large_http_payload',
  'performance_p95_endpoint_regression',
];

export const WEB_VITALS_PREBUILT_CONFIG: PrebuiltDashboard = {
  dateCreated: '',
  projects: [],
  title: 'Web Vitals',
  filters: {
    globalFilter: [
      {
        dataset: WidgetType.SPANS,
        tag: {
          key: 'span.system',
          name: 'span.system',
          kind: FieldKind.TAG,
        },
        value: '',
      },
      {
        dataset: WidgetType.SPANS,
        tag: {
          key: 'span.action',
          name: 'span.action',
          kind: FieldKind.TAG,
        },
        value: '',
      },
      {
        dataset: WidgetType.SPANS,
        tag: {
          key: 'span.domain',
          name: 'span.domain',
          kind: FieldKind.TAG,
        },
        value: '',
      },
    ],
  },
  widgets: [
    {
      id: 'score-breakdown-wheel',
      title: t('Performance Score'),
      displayType: DisplayType.WHEEL,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: [
            'performance_score(measurements.score.lcp)',
            'performance_score(measurements.score.fcp)',
            'performance_score(measurements.score.inp)',
            'performance_score(measurements.score.cls)',
            'performance_score(measurements.score.ttfb)',
            'performance_score(measurements.score.total)',
            'count_scores(measurements.score.total)',
            'count_scores(measurements.score.lcp)',
            'count_scores(measurements.score.fcp)',
            'count_scores(measurements.score.inp)',
            'count_scores(measurements.score.cls)',
            'count_scores(measurements.score.ttfb)',
          ],
          aggregates: [],
          columns: [
            'performance_score(measurements.score.lcp)',
            'performance_score(measurements.score.fcp)',
            'performance_score(measurements.score.inp)',
            'performance_score(measurements.score.cls)',
            'performance_score(measurements.score.ttfb)',
            'performance_score(measurements.score.total)',
            'count_scores(measurements.score.total)',
            'count_scores(measurements.score.lcp)',
            'count_scores(measurements.score.fcp)',
            'count_scores(measurements.score.inp)',
            'count_scores(measurements.score.cls)',
            'count_scores(measurements.score.ttfb)',
          ],
          orderby: '',
        },
      ],
      layout: {
        y: 0,
        w: 2,
        h: 2,
        x: 0,
        minH: 2,
      },
    },
    {
      id: 'score-breakdown-chart',
      title: t('Score Breakdown'),
      displayType: DisplayType.AREA,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: [
            'performance_score(measurements.score.lcp)',
            'performance_score(measurements.score.fcp)',
            'performance_score(measurements.score.inp)',
            'performance_score(measurements.score.cls)',
            'performance_score(measurements.score.ttfb)',
          ],
          aggregates: [
            'performance_score(measurements.score.lcp)',
            'performance_score(measurements.score.fcp)',
            'performance_score(measurements.score.inp)',
            'performance_score(measurements.score.cls)',
            'performance_score(measurements.score.ttfb)',
          ],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 0,
        w: 4,
        h: 2,
        x: 2,
        minH: 2,
      },
    },
    {
      id: 'lcp-p75-meter',
      title: t('P75 Largest Contentful Paint'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.lcp)'],
          aggregates: ['p75(measurements.lcp)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 1200,
          max2: 2400,
        },
        unit: 'ms',
      },
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 0,
        minH: 1,
      },
    },
    {
      id: 'fcp-p75-meter',
      title: t('P75 First Contentful Paint'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.fcp)'],
          aggregates: ['p75(measurements.fcp)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 900,
          max2: 1600,
        },
        unit: 'ms',
      },
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 1,
        minH: 1,
      },
    },
    {
      id: 'inp-p75-meter',
      title: t('P75 Interaction to Next Paint'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.inp)'],
          aggregates: ['p75(measurements.inp)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 200,
          max2: 500,
        },
        unit: 'ms',
      },
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 2,
        minH: 1,
      },
    },
    {
      id: 'cls-p75-meter',
      title: t('P75 Cumulative Layout Shift'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.cls)'],
          aggregates: ['p75(measurements.cls)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 0.1,
          max2: 0.25,
        },
        unit: 'ratio',
      },
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 3,
        minH: 1,
      },
    },
    {
      id: 'ttfb-p75-meter',
      title: t('P75 Time To First Byte'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['p75(measurements.ttfb)'],
          aggregates: ['p75(measurements.ttfb)'],
          columns: [],
          orderby: '',
        },
      ],
      thresholds: {
        max_values: {
          max1: 200,
          max2: 400,
        },
        unit: 'ms',
      },
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 4,
        minH: 1,
      },
    },
    {
      id: 'lcp-score-meter',
      title: t('Largest Contentful Paint Score'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['avg(measurements.score.ratio.lcp)'],
          aggregates: ['avg(measurements.score.ratio.lcp)'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 0,
        minH: 1,
      },
    },
    {
      id: 'fcp-score-meter',
      title: t('First Contentful Paint Score'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['avg(measurements.score.ratio.fcp)'],
          aggregates: ['avg(measurements.score.ratio.fcp)'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 1,
        minH: 1,
      },
    },
    {
      id: 'inp-score-meter',
      title: t('Interaction to Next Paint Score'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['avg(measurements.score.ratio.inp)'],
          aggregates: ['avg(measurements.score.ratio.inp)'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 2,
        minH: 1,
      },
    },
    {
      id: 'cls-score-meter',
      title: t('Cumulative Layout Shift Score'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['avg(measurements.score.ratio.cls)'],
          aggregates: ['avg(measurements.score.ratio.cls)'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 3,
        minH: 1,
      },
    },
    {
      id: 'ttfb-score-meter',
      title: t('Time To First Byte Score'),
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: ['avg(measurements.score.ratio.ttfb)'],
          aggregates: ['avg(measurements.score.ratio.ttfb)'],
          columns: [],
          orderby: '',
        },
      ],
      layout: {
        y: 2,
        w: 1,
        h: 1,
        x: 4,
        minH: 1,
      },
    },
    {
      id: 'issues-table',
      title: t('Web Vital Issues'),
      displayType: DisplayType.TABLE,
      widgetType: WidgetType.ISSUE,
      interval: '5m',
      tableWidths: [-1, 100, -1],
      queries: [
        {
          name: '',
          conditions: `issue.type:[${ISSUE_TYPES.join(',')}]`,
          fields: ['issue', 'assignee', 'title'],
          aggregates: [],
          columns: ['issue', 'assignee', 'title'],
          orderby: 'date',
        },
      ],
      layout: {
        y: 3,
        w: 6,
        h: 2,
        x: 0,
        minH: 2,
      },
    },
    {
      id: 'pages-table',
      title: t('Pages'),
      displayType: DisplayType.TABLE,
      widgetType: WidgetType.SPANS,
      interval: '5m',
      tableWidths: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
      queries: [
        {
          name: '',
          conditions: DEFAULT_QUERY_FILTER,
          fields: [
            SpanFields.TRANSACTION,
            SpanFields.PROJECT,
            'count()',
            'p75(measurements.lcp)',
            'p75(measurements.fcp)',
            'p75(measurements.cls)',
            'p75(measurements.ttfb)',
            'p75(measurements.inp)',
            'performance_score(measurements.score.total)',
            'opportunity_score(measurements.score.total)',
          ],
          aggregates: [],
          columns: [
            SpanFields.TRANSACTION,
            SpanFields.PROJECT,
            'count()',
            'p75(measurements.lcp)',
            'p75(measurements.fcp)',
            'p75(measurements.cls)',
            'p75(measurements.ttfb)',
            'p75(measurements.inp)',
            'performance_score(measurements.score.total)',
            'opportunity_score(measurements.score.total)',
          ],
          orderby: `-opportunity_score(measurements.score.total)`,
          fieldAliases: [
            t('Pages'),
            t('Project'),
            t('Pageloads'),
            t('LCP'),
            t('FCP'),
            t('CLS'),
            t('TTFB'),
            t('INP'),
            t('Perf Score'),
            t('Opportunity'),
          ],
          linkedDashboards: [
            {
              dashboardId: '-1',
              field: SpanFields.TRANSACTION,
              staticDashboardId: 7,
            },
          ],
        },
      ],
      layout: {
        y: 5,
        w: 6,
        h: 6,
        x: 0,
        minH: 2,
      },
    },
  ],
};
