FROM python:2.7

RUN apt-get update && apt-get install -y --no-install-recommends \
        apt-transport-https \
        vim-nox \
        postgresql-client \
        less \
    && rm -rf /var/lib/apt/lists/*

ENV NODE_VERSION 0.12.7-1nodesource1~jessie1

RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
RUN echo 'deb https://deb.nodesource.com/node_0.12 jessie main' > /etc/apt/sources.list.d/nodesource.list \
    && apt-get update && apt-get install -y --no-install-recommends \
        nodejs=$NODE_VERSION \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app
WORKDIR /app

ENV PATH=$PATH:/app/bin:/app/node_modules/.bin

EXPOSE 8000

CMD ["bash"]
