# Generated by Django 5.2.1 on 2025-07-08 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
import sentry.db.models.fields.hybrid_cloud_foreign_key
import sentry.db.models.fields.jsonfield
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    initial = True

    dependencies = [
        ("sentry", "0943_move_discover_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="DiscoverSavedQuery",
                    fields=[
                        (
                            "id",
                            sentry.db.models.fields.bounded.BoundedBigAutoField(
                                primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "created_by_id",
                            sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                                "sentry.User", db_index=True, null=True, on_delete="SET_NULL"
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("query", sentry.db.models.fields.jsonfield.JSONField(default=dict)),
                        ("version", models.IntegerField(null=True)),
                        ("date_created", models.DateTimeField(auto_now_add=True)),
                        ("date_updated", models.DateTimeField(auto_now=True)),
                        (
                            "visits",
                            sentry.db.models.fields.bounded.BoundedBigIntegerField(
                                default=1, null=True
                            ),
                        ),
                        (
                            "last_visited",
                            models.DateTimeField(default=django.utils.timezone.now, null=True),
                        ),
                        ("is_homepage", models.BooleanField(blank=True, null=True)),
                        (
                            "dataset",
                            sentry.db.models.fields.bounded.BoundedPositiveIntegerField(
                                db_default=0, default=0
                            ),
                        ),
                        (
                            "dataset_source",
                            sentry.db.models.fields.bounded.BoundedPositiveIntegerField(
                                db_default=0, default=0
                            ),
                        ),
                        (
                            "organization",
                            sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="sentry.organization",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "sentry_discoversavedquery",
                    },
                ),
                migrations.CreateModel(
                    name="DiscoverSavedQueryProject",
                    fields=[
                        (
                            "id",
                            sentry.db.models.fields.bounded.BoundedBigAutoField(
                                primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "discover_saved_query",
                            sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="discover.discoversavedquery",
                            ),
                        ),
                        (
                            "project",
                            sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to="sentry.project"
                            ),
                        ),
                    ],
                    options={
                        "db_table": "sentry_discoversavedqueryproject",
                        "unique_together": {("project", "discover_saved_query")},
                    },
                ),
                migrations.AddField(
                    model_name="discoversavedquery",
                    name="projects",
                    field=models.ManyToManyField(
                        through="discover.DiscoverSavedQueryProject", to="sentry.project"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="discoversavedquery",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("is_homepage", True)),
                        fields=("organization", "created_by_id", "is_homepage"),
                        name="unique_user_homepage_query",
                    ),
                ),
            ]
        )
    ]
