import ast
import contextlib
import os.path

from tools.migrations.squash import App, _fixup, inject_pending_deletions

GENERATED = """\
from django.db import migrations, models

import sentry.new_migrations.migrations


class Migration(sentry.new_migrations.migrations.CheckedMigration):
    is_post_deployment = False

    dependencies = [
        ("sentry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestTable",
            fields=[],
        ),
    ]
"""


def test_injects_operations_imports_and_deps() -> None:
    payload = {
        "operations": [
            "sentry.new_migrations.monkey.fields.AddField(\n    name='f',\n),",
            "sentry.new_migrations.monkey.fields.SafeRemoveField(\n    name='f',\n),",
        ],
        "imports": ["import sentry.new_migrations.monkey.fields"],
        "dependencies": [["explore", "__first__"]],
    }

    out = "".join(inject_pending_deletions(GENERATED.splitlines(keepends=True), payload))

    assert "SafeRemoveField(" in out
    assert "import sentry.new_migrations.monkey.fields" in out
    assert '("explore", "__first__")' in out
    assert out.count("operations = [") == 1


def test_operation_writer_indentation_is_normalized() -> None:
    payload = {
        "operations": [
            "        sentry.new_migrations.monkey.fields.SafeRemoveField(\n"
            "            model_name='t',\n"
            "            name='f',\n"
            "        ),"
        ],
        "imports": ["import sentry.new_migrations.monkey.fields"],
        "dependencies": [],
    }

    out = "".join(inject_pending_deletions(GENERATED.splitlines(keepends=True), payload))

    lines = out.splitlines()
    assert "        sentry.new_migrations.monkey.fields.SafeRemoveField(" in lines
    assert "            model_name='t'," in lines
    ast.parse(out)


def test_already_present_imports_are_not_duplicated() -> None:
    payload = {
        "operations": ["        migrations.AddField(\n            name='f',\n        ),"],
        "imports": ["import sentry.new_migrations.migrations", "import sentry.new_migrations.foo"],
        "dependencies": [],
    }

    out = "".join(inject_pending_deletions(GENERATED.splitlines(keepends=True), payload))

    lines = out.splitlines()
    assert lines.count("import sentry.new_migrations.migrations") == 1
    assert lines.count("import sentry.new_migrations.foo") == 1


def test_empty_payload_is_noop() -> None:
    lines = GENERATED.splitlines(keepends=True)
    payload: dict = {"operations": [], "imports": [], "dependencies": []}

    assert inject_pending_deletions(lines, payload) == lines


REALISTIC_SQUASH = """\
# Generated by Django 5.2.14 on 2026-08-04 00:00

from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in
    # production.
    # Once deployed, run these manually via:
    # https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    initial = True

    dependencies = [
        ("sentry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceItemAttributeContext",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={"db_table": "explore_traceitemattributecontext"},
        ),
    ]
"""

REAL_ADD_FIELD = (
    "        migrations.AddField(\n"
    "            model_name='traceitemattributecontext',\n"
    "            name='last_received',\n"
    "            field=models.DateTimeField(null=True),\n"
    "        ),"
)
REAL_SAFE_REMOVE = (
    "        sentry.new_migrations.monkey.fields.SafeRemoveField(\n"
    "            model_name='traceitemattributecontext',\n"
    "            name='last_received',\n"
    "            deletion_action=sentry.new_migrations.monkey.state."
    "DeletionAction['MOVE_TO_PENDING'],\n"
    "        ),"
)
REAL_PAYLOAD = {
    "operations": [REAL_ADD_FIELD, REAL_SAFE_REMOVE],
    "imports": [
        "import sentry.new_migrations.monkey.fields",
        "import sentry.new_migrations.monkey.state",
    ],
    "dependencies": [["explore", "__first__"]],
}


def _run_fixup(tmp_path, source: str = REALISTIC_SQUASH, payload=REAL_PAYLOAD) -> str:
    root = tmp_path / "migrations"
    root.mkdir()
    (root / "0001_squash.py").write_text(source, encoding="UTF-8")
    app = App(name="explore", current="0010_something", root=str(root), replaces=["0001_initial"])
    _fixup(app, {"explore": app}, {"explore": payload})
    with open(os.path.join(str(root), f"{app.squash_name}.py"), encoding="UTF-8") as f:
        return f.read()


def _assign_list(tree: ast.AST, name: str) -> ast.List:
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and node.targets[0].id == name
            and isinstance(node.value, ast.List)
        ):
            return node.value
    raise AssertionError(f"no {name} list")


def test_fixup_injects_into_operations_and_dependencies(tmp_path) -> None:
    out = _run_fixup(tmp_path)

    tree = ast.parse(out)

    ops = _assign_list(tree, "operations")
    op_srcs = [ast.unparse(e) for e in ops.elts]
    assert any("SafeRemoveField(" in s for s in op_srcs), out
    assert any("AddField(" in s for s in op_srcs), out

    deps = _assign_list(tree, "dependencies")
    dep_values = [ast.literal_eval(e) for e in deps.elts if isinstance(e, ast.Tuple)]
    assert ("explore", "__first__") in dep_values, out


def _bound_names(tree: ast.AST) -> list[str]:
    names = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            names += [a.asname or a.name.split(".")[0] for a in node.names]
        elif isinstance(node, ast.ImportFrom):
            names += [a.asname or a.name for a in node.names]
    return names


def test_fixup_does_not_duplicate_django_db_models_import(tmp_path) -> None:
    payload = {**REAL_PAYLOAD, "imports": ["from django.db import models"]}

    out = _run_fixup(tmp_path, payload=payload)

    names = _bound_names(ast.parse(out))
    assert names.count("models") == 1, out
    assert names.count("migrations") == 1, out


def test_fixup_still_adds_genuinely_new_imports(tmp_path) -> None:
    payload = {
        **REAL_PAYLOAD,
        "imports": [
            "from django.db import models",
            "import sentry.new_migrations.monkey.fields",
        ],
    }

    out = _run_fixup(tmp_path, payload=payload)

    names = _bound_names(ast.parse(out))
    assert names.count("models") == 1, out
    assert names.count("sentry") >= 1, out
    assert "import sentry.new_migrations.monkey.fields" in out


SINGLE_LINE_LISTS = """\
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    is_post_deployment = False

    initial = True

    dependencies = []

    operations = []
"""


def test_fixup_handles_single_line_empty_lists(tmp_path) -> None:
    out = _run_fixup(tmp_path, source=SINGLE_LINE_LISTS)

    tree = ast.parse(out)

    ops = _assign_list(tree, "operations")
    assert [ast.unparse(e) for e in ops.elts], out
    assert any("SafeRemoveField(" in ast.unparse(e) for e in ops.elts), out

    deps = _assign_list(tree, "dependencies")
    assert ("explore", "__first__") in [
        ast.literal_eval(e) for e in deps.elts if isinstance(e, ast.Tuple)
    ], out


SINGLE_LINE_NONEMPTY = """\
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    is_post_deployment = False

    initial = True

    dependencies = [("sentry", "0001_initial")]

    operations = [migrations.RunPython(migrations.RunPython.noop)]
"""


def test_fixup_handles_single_line_non_empty_lists(tmp_path) -> None:
    out = _run_fixup(tmp_path, source=SINGLE_LINE_NONEMPTY)

    tree = ast.parse(out)

    ops = _assign_list(tree, "operations")
    op_srcs = [ast.unparse(e) for e in ops.elts]
    assert any("RunPython" in s for s in op_srcs), out
    assert any("SafeRemoveField(" in s for s in op_srcs), out

    deps = _assign_list(tree, "dependencies")
    dep_values = [ast.literal_eval(e) for e in deps.elts if isinstance(e, ast.Tuple)]
    assert ("sentry", "0001_initial") in dep_values, out
    assert ("explore", "__first__") in dep_values, out


def test_fixup_does_not_inject_dependency_inside_an_operation_call(tmp_path) -> None:
    out = _run_fixup(tmp_path)

    tree = ast.parse(out)
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            for arg in ast.walk(node):
                if isinstance(arg, ast.Tuple):
                    with contextlib.suppress(ValueError):
                        if ast.literal_eval(arg) == ("explore", "__first__"):
                            raise AssertionError(
                                f"dependency tuple nested inside {ast.unparse(node.func)}:\n{out}"
                            )
