// environment
export const UPDATE_ENVIRONMENTS = 'UPDATE_ENVIRONMENTS';

// organization
export const LOAD_ORGANIZATIONS = 'LOAD_ORGANIZATIONS';
export const SET_ACTIVE_ORGANIZATION = 'SET_ACTIVE_ORGANIZATION';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';

// project
export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT';
