import os

env = os.environ.get

DEBUG = True

DEFAULT_RETENTION_DAYS = env("SENTRY_EVENT_RETENTION_DAYS", 90)

REDIS_HOST = env("REDIS_HOST", "localhost")
REDIS_PORT = int(env("REDIS_PORT", 6379))
REDIS_PASSWORD = env("REDIS_PASSWORD")
REDIS_DB = int(env("REDIS_DB", 1))
USE_REDIS_CLUSTER = False

# Dogstatsd Options
DOGSTATSD_HOST = env("DOGSTATSD_HOST")
DOGSTATSD_PORT = env("DOGSTATSD_PORT")

SENTRY_DSN = env("SENTRY_DSN")

ERRORS_ROLLOUT_ALL = True
ERRORS_ROLLOUT_WRITABLE_STORAGE = True
