# Generated by Django 5.2.1 on 2025-05-28 16:49

import django.db.models.deletion
from django.db import migrations, models

import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
import sentry.db.models.fields.jsonfield
import sentry.preprod.models
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    initial = True

    dependencies = [
        ("sentry", "0913_split_discover_dataset_dashboards_self_hosted"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreprodBuildConfiguration",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "project",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.project"
                    ),
                ),
            ],
            options={
                "db_table": "sentry_preprodbuildconfiguration",
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="PreprodArtifact",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "file_id",
                    sentry.db.models.fields.bounded.BoundedBigIntegerField(
                        db_index=True, null=True
                    ),
                ),
                ("date_built", models.DateTimeField(null=True)),
                (
                    "state",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(
                        default=sentry.preprod.models.PreprodArtifact.ArtifactState["UPLOADING"]
                    ),
                ),
                (
                    "artifact_type",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(null=True),
                ),
                (
                    "error_code",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(null=True),
                ),
                ("error_message", models.TextField(null=True)),
                ("build_version", models.CharField(max_length=255, null=True)),
                ("build_number", sentry.db.models.fields.bounded.BoundedBigIntegerField(null=True)),
                ("extras", sentry.db.models.fields.jsonfield.JSONField(null=True)),
                (
                    "project",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.project"
                    ),
                ),
                (
                    "build_configuration",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="preprod.preprodbuildconfiguration",
                    ),
                ),
            ],
            options={
                "db_table": "sentry_preprodartifact",
            },
        ),
        migrations.CreateModel(
            name="PreprodArtifactSizeMetrics",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "metrics_artifact_type",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(null=True),
                ),
                (
                    "state",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(
                        default=sentry.preprod.models.PreprodArtifactSizeMetrics.SizeAnalysisState[
                            "PENDING"
                        ]
                    ),
                ),
                (
                    "error_code",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(null=True),
                ),
                ("error_message", models.TextField(null=True)),
                ("processing_version", models.CharField(max_length=255, null=True)),
                (
                    "min_install_size",
                    sentry.db.models.fields.bounded.BoundedPositiveBigIntegerField(null=True),
                ),
                (
                    "max_install_size",
                    sentry.db.models.fields.bounded.BoundedPositiveBigIntegerField(null=True),
                ),
                (
                    "min_download_size",
                    sentry.db.models.fields.bounded.BoundedPositiveBigIntegerField(null=True),
                ),
                (
                    "max_download_size",
                    sentry.db.models.fields.bounded.BoundedPositiveBigIntegerField(null=True),
                ),
                (
                    "preprod_artifact",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="preprod.preprodartifact"
                    ),
                ),
            ],
            options={
                "db_table": "sentry_preprodartifactsizemetrics",
                "unique_together": {("preprod_artifact", "metrics_artifact_type")},
            },
        ),
    ]
