# Generated by Django 5.2.8 on 2026-01-07 10:40

from asyncio.log import logger

from django.db import IntegrityError, migrations, router, transaction

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.query import RangeQuerySetWrapperWithProgressBar


def backfill_preprod_artifact_mobile_app_info(apps, schema_editor):
    PreprodArtifact = apps.get_model("preprod", "PreprodArtifact")
    PreprodArtifactMobileAppInfo = apps.get_model("preprod", "PreprodArtifactMobileAppInfo")

    all_artifacts = PreprodArtifact.objects.all()
    mobile_app_info_to_create = []

    for artifact in RangeQuerySetWrapperWithProgressBar(all_artifacts):
        # Skip if PreprodArtifactMobileAppInfo already exists for this artifact
        if PreprodArtifactMobileAppInfo.objects.filter(preprod_artifact_id=artifact.id).exists():
            continue

        # Only create if there's at least one mobile app field with data
        has_mobile_app_data = any(
            [
                artifact.build_version,
                artifact.build_number is not None,
                artifact.app_name,
                artifact.app_icon_id,
            ]
        )

        if has_mobile_app_data:
            mobile_app_info_to_create.append(
                PreprodArtifactMobileAppInfo(
                    preprod_artifact_id=artifact.id,
                    build_version=artifact.build_version,
                    build_number=artifact.build_number,
                    app_name=artifact.app_name,
                    app_icon_id=artifact.app_icon_id,
                )
            )

    with transaction.atomic(router.db_for_write(PreprodArtifactMobileAppInfo)):
        try:
            PreprodArtifactMobileAppInfo.objects.bulk_create(
                mobile_app_info_to_create,
                ignore_conflicts=True,
            )
        except IntegrityError as e:
            logger.exception(
                "Error bulk creating preprod artifact mobile app info",
                extra={
                    "mobile_app_info_to_create": len(mobile_app_info_to_create),
                    "error": e,
                },
            )


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    # This migration is safe to run after the code has deployed as the total amount of PreprodArtifacts is small (~6k records)
    is_post_deployment = False

    dependencies = [
        ("preprod", "0020_add_preprod_artifact_mobile_app_info"),
    ]

    operations = [
        migrations.RunPython(
            backfill_preprod_artifact_mobile_app_info,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
            hints={"tables": ["preprod_preprodartifact", "sentry_preprodartifactmobileappinfo"]},
        ),
    ]
