# Generated by Django 5.2.8

from django.db import migrations, models

import sentry.db.models.fields.bounded
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    is_post_deployment = False

    dependencies = [
        ("preprod", "0026_add_initial_snapshot_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="preprodartifact",
            name="installable_app_error_code",
            field=sentry.db.models.fields.bounded.BoundedPositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="preprodartifact",
            name="installable_app_error_message",
            field=models.TextField(null=True),
        ),
    ]
