[devenv]
minimum_version = 1.22.0

[node]
# upstream (https://nodejs.org/dist/) is not reliable enough
# ask someone in team-devinfra to upload for you
darwin_x86_64 = https://storage.googleapis.com/sentry-dev-infra-assets/node/node-v26.11.1-darwin-x64.tar.xz
darwin_x86_64_sha256 = 68a8a4de0c46e693a261d13efb43d041fcd7386187816ef9a4b14bf60003adb2
darwin_arm64 = https://storage.googleapis.com/sentry-dev-infra-assets/node/node-v26.11.1-darwin-arm64.tar.xz
darwin_arm64_sha256 = 0ef9b443000681bffc062ec126d53f97933ea9b086ea73dcba0480d87e639b39
linux_x86_64 = https://storage.googleapis.com/sentry-dev-infra-assets/node/node-v26.11.1-linux-x64.tar.xz
linux_x86_64_sha256 = 3883bfc73f9a680ca4eab04b196068aaaab1373ffa77d8fc1a4408222495b651
linux_arm64 = https://storage.googleapis.com/sentry-dev-infra-assets/node/node-v26.11.1-linux-arm64.tar.xz
linux_arm64_sha256 = 0945e2cde6aa0f54d980f03874dfe5cf3a549ce714c7fb9019e591ce0accf282
# used for autoupdate
version = v26.11.1
