`lektor`
--------

Sentry is cross-platform crash reporting built with love.

Options
```````

- `--config PATH`: Path to configuration files.
- `--version`: Show the version and exit.
- `--help`: print this help page.

Subcommands
```````````

.. toctree::
 :maxdepth: 1

 repair <repair/index>
 upgrade <upgrade/index>
 help <help/index>
 devserver <devserver/index>
 django <django/index>
 celery <celery/index>
 start <start/index>
 init <init/index>
 cleanup <cleanup/index>
 export <export/index>
 createuser <createuser/index>
 import <import/index>
 shell <shell/index>

