export enum MCPReferrer {
  MCP_TRAFFIC_WIDGET = 'api.performance.mcp.traffic-widget',
  MCP_TRANSPORT_WIDGET = 'api.performance.mcp.transport-widget',
  MCP_SOURCES_WIDGET = 'api.performance.mcp.sources-widget',
  MCP_TOOL_TRAFFIC_WIDGET = 'api.performance.mcp.tool-traffic-widget',
  MCP_PROMPT_TRAFFIC_WIDGET = 'api.performance.mcp.prompt-traffic-widget',
  MCP_RESOURCE_TRAFFIC_WIDGET = 'api.performance.mcp.resource-traffic-widget',
  MCP_TOOL_DURATION_WIDGET = 'api.performance.mcp.tool-duration-widget',
  MCP_PROMPT_DURATION_WIDGET = 'api.performance.mcp.prompt-duration-widget',
  MCP_RESOURCE_DURATION_WIDGET = 'api.performance.mcp.resource-duration-widget',
  MCP_TOOL_ERROR_RATE_WIDGET = 'api.performance.mcp.tool-error-rate-widget',
  MCP_PROMPT_ERROR_RATE_WIDGET = 'api.performance.mcp.prompt-error-rate-widget',
  MCP_RESOURCE_ERROR_RATE_WIDGET = 'api.performance.mcp.resource-error-rate-widget',
  MCP_TOOL_TABLE = 'api.performance.mcp.tool-table',
  MCP_PROMPT_TABLE = 'api.performance.mcp.prompt-table',
  MCP_RESOURCE_TABLE = 'api.performance.mcp.resource-table',
}
