// Mock pull requests data
export const pullRequestsData = [
  {
    id: '1',
    title: 'steps4: add smiles',
    number: 10,
    author: 'Flamefire',
    status: 'open',
    timestamp: '1 day ago',
    coverage: '87.50%',
    uncompressedSize: '2.4 MB',
    downloadSize: '856 KB',
    authorUser: {
      id: '1',
      email: 'flamefire@example.com',
      name: 'Flamefire',
      username: 'flamefire',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/1234567?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '2',
    title: 'steps3: add Codecov badge',
    number: 9,
    author: 'Maya Rodriguez',
    status: 'open',
    timestamp: '1 day ago',
    coverage: '92.30%',
    uncompressedSize: '1.8 MB',
    downloadSize: '642 KB',
    authorUser: {
      id: '2',
      email: 'maya.rodriguez@example.com',
      name: 'Maya Rodriguez',
      username: 'mayarod',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/7654321?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '3',
    title: 'step3: add project status check target',
    number: 7,
    author: 'Alex Chen',
    status: 'open',
    timestamp: '1 day ago',
    coverage: '85.60%',
    uncompressedSize: '3.1 MB',
    downloadSize: '1.1 MB',
    authorUser: {
      id: '3',
      email: 'alex.chen@example.com',
      name: 'Alex Chen',
      username: 'alexchen',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/9876543?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '4',
    title: 'steps3: cover divide by 0 case',
    number: 8,
    author: 'Sarah Johnson',
    status: 'open',
    timestamp: '1 day ago',
    coverage: '100%',
    uncompressedSize: '2.0 MB',
    downloadSize: '712 KB',
    authorUser: {
      id: '4',
      email: 'sarah.johnson@example.com',
      name: 'Sarah Johnson',
      username: 'sarahj',
      ip_address: '',
      avatar: {
        avatarUrl: null,
        avatarType: 'gravatar' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '5',
    title: 'step3: add project status check target',
    number: 6,
    author: 'David Kim',
    status: 'open',
    timestamp: '1 day ago',
    coverage: '78.45%',
    uncompressedSize: '2.7 MB',
    downloadSize: '968 KB',
    authorUser: {
      id: '5',
      email: 'david.kim@example.com',
      name: 'David Kim',
      username: 'dkim',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/5432109?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '6',
    title: 'step2: upload coverage reports to Codecov',
    number: 5,
    author: 'Emma Thompson',
    status: 'open',
    timestamp: '1 day ago',
    coverage: '91.20%',
    uncompressedSize: '1.5 MB',
    downloadSize: '534 KB',
    authorUser: {
      id: '6',
      email: 'emma.thompson@example.com',
      name: 'Emma Thompson',
      username: 'emmathompson',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/9876543?v=4',
        avatarType: 'gravatar' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '7',
    title: 'step1: create initial project structure',
    number: 4,
    author: 'Marcus Johnson',
    status: 'merged',
    timestamp: '2 days ago',
    coverage: '95%',
    uncompressedSize: '4.2 MB',
    downloadSize: '1.5 MB',
    authorUser: {
      id: '7',
      email: 'marcus.johnson@example.com',
      name: 'Marcus Johnson',
      username: 'marcusj',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/1357924?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '8',
    title: 'initial commit setup',
    number: 3,
    author: 'Priya Patel',
    status: 'merged',
    timestamp: '3 days ago',
    coverage: '88%',
    uncompressedSize: '3.8 MB',
    downloadSize: '1.3 MB',
    authorUser: {
      id: '8',
      email: 'priya.patel@example.com',
      name: 'Priya Patel',
      username: 'priyap',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/2468135?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '9',
    title: 'fix typo in documentation',
    number: 2,
    author: 'Jake Wilson',
    status: 'merged',
    timestamp: '4 days ago',
    coverage: '100%',
    uncompressedSize: '856 KB',
    downloadSize: '298 KB',
    authorUser: {
      id: '9',
      email: 'jake.wilson@example.com',
      name: 'Jake Wilson',
      username: 'jakew',
      ip_address: '',
      avatar: {
        avatarUrl: null,
        avatarType: 'gravatar' as const,
        avatarUuid: null,
      },
    },
  },
  // Add closed pull requests to match the design
  ...Array.from({length: 35}, (_, index) => {
    const authors = [
      'Lisa Wang',
      'Carlos Rivera',
      'Aisha Okafor',
      "Ryan O'Connor",
      'Fatima Al-Zahra',
      'Hiroshi Tanaka',
      'Elena Petrov',
      'Ahmed Hassan',
      'Sophie Dubois',
      'Raj Sharma',
      'Isabella Santos',
      'Dmitri Volkov',
      'Zara Khan',
      'Lucas Anderson',
      'Mei Chen',
      'Omar Benali',
      'Ingrid Larsson',
      'Kenji Nakamura',
      'Nadia Popov',
      'Gabriel Silva',
      'Yuki Sato',
      'Amara Osei',
      'Viktor Kozlov',
      'Camila Torres',
      'Hassan Ali',
      'Nina Johansson',
      'Arjun Gupta',
      'Leila Moradi',
      'Diego Fernandez',
      'Anya Petrov',
      'Kwame Asante',
      'Sakura Yamamoto',
      'Mateo Rodriguez',
      'Zoe Mitchell',
      'Tariq Mahmoud',
    ];
    const author = authors[index % authors.length]!;
    const username = author
      .toLowerCase()
      .replace(/['\s]/g, '')
      .replace("o'connor", 'oconnor');
    const email = `${username}@example.com`;

    // Generate varied but realistic size values
    const sizeVariants = [
      {uncompressed: '1.2 MB', download: '428 KB'},
      {uncompressed: '2.8 MB', download: '982 KB'},
      {uncompressed: '3.5 MB', download: '1.2 MB'},
      {uncompressed: '945 KB', download: '334 KB'},
      {uncompressed: '4.1 MB', download: '1.4 MB'},
      {uncompressed: '1.9 MB', download: '678 KB'},
      {uncompressed: '2.3 MB', download: '812 KB'},
    ];
    const sizeData = sizeVariants[index % sizeVariants.length]!;

    // Generate varied coverage percentages
    const coverageValues = [
      '95.20%',
      '88.75%',
      '92.10%',
      '76.50%',
      '100%',
      '83.40%',
      '89.90%',
      '94.30%',
      '81.25%',
      '97.80%',
    ];
    const coverage = coverageValues[index % coverageValues.length]!;

    return {
      id: `closed-${index + 1}`,
      title: `Closed PR ${index + 1}`,
      number: 100 + index,
      author,
      status: 'closed',
      timestamp: `${Math.floor(index / 7) + 1} weeks ago`,
      coverage,
      uncompressedSize: sizeData.uncompressed,
      downloadSize: sizeData.download,
      authorUser: {
        id: `closed-${index + 1}`,
        email,
        name: author,
        username,
        ip_address: '',
      },
    };
  }),
];

// ============================================================================
// Mock commits data (used by FileExplorer tab - Commit History View)
// ============================================================================
export const commitsData = [
  {
    id: '1',
    message: 'step4: add smiles',
    author: 'Flamefire',
    hash: 'd677638',
    timestamp: '1 day ago',
    coverage: '68.50%',
    uploadCount: {
      total: 81,
      processed: 65,
      pending: 15,
      failed: 1,
    },
    authorUser: {
      id: '1',
      email: 'flamefire@example.com',
      name: 'Flamefire',
      username: 'flamefire',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/1234567?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '2',
    message: 'step3: add Codecov badge',
    author: 'Maya Rodriguez',
    hash: '3d59704',
    timestamp: '2 days ago',
    coverage: '65%',
    uploadCount: {
      total: 80,
      processed: 80,
      pending: 0,
      failed: 0,
    },
    authorUser: {
      id: '2',
      email: 'maya.rodriguez@example.com',
      name: 'Maya Rodriguez',
      username: 'mayarod',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/87772943?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '3',
    message: 'step3: add Codecov badge',
    author: 'Alex Chen',
    hash: '4663d65',
    timestamp: '3 days ago',
    coverage: '100%',
    uploadCount: {
      total: 78,
      processed: 78,
      pending: 0,
      failed: 0,
    },
    authorUser: {
      id: '3',
      email: 'alex.chen@example.com',
      name: 'Alex Chen',
      username: 'alexchen',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/88201630?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '4',
    message: 'step3: cover divide by 0 case',
    author: 'Sarah Johnson',
    hash: 'f0a9d69',
    timestamp: '3 days ago',
    coverage: '100%',
    uploadCount: {
      total: 78,
      processed: 78,
      pending: 0,
      failed: 0,
    },
    authorUser: {
      id: '4',
      email: 'sarah.johnson@example.com',
      name: 'Sarah Johnson',
      username: 'sarahj',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/71270647?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '5',
    message: 'step3: cover divide by 0 case',
    author: 'David Kim',
    hash: '3c01a7b',
    timestamp: '3 days ago',
    coverage: '100%',
    uploadCount: {
      total: 36,
      processed: 36,
      pending: 0,
      failed: 0,
    },
    authorUser: {
      id: '5',
      email: 'david.kim@example.com',
      name: 'David Kim',
      username: 'dkim',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/159853603?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '6',
    message: 'step3: add project status check target',
    author: 'Emma Thompson',
    hash: 'ee98986',
    timestamp: '3 days ago',
    coverage: '100%',
    uploadCount: {
      total: 66,
      processed: 66,
      pending: 0,
      failed: 0,
    },
    authorUser: {
      id: '6',
      email: 'emma.thompson@example.com',
      name: 'Emma Thompson',
      username: 'emmathompson',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/3456789?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '7',
    message: 'step3: add project status check target',
    author: 'Marcus Johnson',
    hash: 'a09f75c',
    timestamp: '3 days ago',
    coverage: '100%',
    uploadCount: {
      total: 77,
      processed: 77,
      pending: 0,
      failed: 0,
    },
    authorUser: {
      id: '7',
      email: 'marcus.johnson@example.com',
      name: 'Marcus Johnson',
      username: 'marcusj',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/6789012?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '8',
    message: 'step2: upload coverage reports to Codecov',
    author: 'Priya Patel',
    hash: '366e107',
    timestamp: '3 days ago',
    coverage: '100%',
    uploadCount: {
      total: 88,
      processed: 88,
      pending: 0,
      failed: 0,
    },
    authorUser: {
      id: '8',
      email: 'priya.patel@example.com',
      name: 'Priya Patel',
      username: 'priyap',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/8901234?v=4',
        avatarType: 'upload' as const,
        avatarUuid: null,
      },
    },
  },
  {
    id: '9',
    message: 'step2: upload coverage reports to Codecov',
    author: 'Jake Wilson',
    hash: '79d45ad',
    timestamp: '3 days ago',
    coverage: '100%',
    uploadCount: {
      total: 55,
      processed: 55,
      pending: 0,
      failed: 0,
    },
    authorUser: {
      id: '9',
      email: 'jake.wilson@example.com',
      name: 'Jake Wilson',
      username: 'jakew',
      ip_address: '',
      avatar: {
        avatarUrl: 'https://avatars.githubusercontent.com/u/5678901?v=4',
        avatarType: 'gravatar' as const,
        avatarUuid: null,
      },
    },
  },
];
