import {
  IconAdd,
  IconCheckmark,
  IconClose,
  IconDelete,
  IconEdit,
  IconFile,
  IconFire,
  IconFlag,
  IconGraph,
  IconLock,
  IconMute,
  IconNext,
  IconPlay,
  IconPrevious,
  IconRefresh,
  IconUnsubscribed,
  IconUser,
} from 'sentry/icons';
import {GroupActivityType} from 'sentry/types/group';

export const GroupActivityTypeIconMapping: Record<GroupActivityType, React.ReactNode> = {
  [GroupActivityType.NOTE]: <IconFile />,
  [GroupActivityType.SET_RESOLVED]: <IconCheckmark />,
  [GroupActivityType.SET_RESOLVED_BY_AGE]: <IconCheckmark />,
  [GroupActivityType.SET_RESOLVED_IN_RELEASE]: <IconCheckmark />,
  [GroupActivityType.SET_RESOLVED_IN_COMMIT]: <IconCheckmark />,
  [GroupActivityType.SET_RESOLVED_IN_PULL_REQUEST]: <IconCheckmark />,
  [GroupActivityType.SET_UNRESOLVED]: <IconClose />,
  [GroupActivityType.SET_IGNORED]: <IconMute />,
  [GroupActivityType.SET_PUBLIC]: <IconLock />,
  [GroupActivityType.SET_PRIVATE]: <IconLock locked />,
  [GroupActivityType.SET_REGRESSION]: <IconFire />,
  [GroupActivityType.CREATE_ISSUE]: <IconAdd />,
  [GroupActivityType.UNMERGE_SOURCE]: <IconPrevious />,
  [GroupActivityType.UNMERGE_DESTINATION]: <IconPrevious />,
  [GroupActivityType.FIRST_SEEN]: <IconFlag />,
  [GroupActivityType.ASSIGNED]: <IconUser />,
  [GroupActivityType.UNASSIGNED]: <IconUnsubscribed />,
  [GroupActivityType.MERGE]: <IconNext />,
  [GroupActivityType.REPROCESS]: <IconRefresh />,
  [GroupActivityType.MARK_REVIEWED]: <IconCheckmark />,
  [GroupActivityType.AUTO_SET_ONGOING]: <IconPlay />,
  [GroupActivityType.SET_ESCALATING]: <IconGraph type="area" />,
  [GroupActivityType.SET_PRIORITY]: <IconEdit />,
  [GroupActivityType.DELETED_ATTACHMENT]: <IconDelete />,
};
