# Generated by Django 5.2.15 on 2026-08-15 04:48

import hashlib

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils import json


def move_sources(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Investigation = apps.get_model("investigations", "Investigation")
    active_by_lineage = {}
    for investigation in Investigation.objects.using(schema_editor.connection.alias).order_by(
        "organization_id", "source_key", "-source_revision", "-id"
    ):
        if investigation.source_type == "manual" or investigation.source_key is None:
            continue
        source_type = (
            "metric_open_period"
            if investigation.source_type == "breached_metric"
            else investigation.source_type
        )
        source = {"type": source_type, "ref": investigation.source_ref}
        snapshot = investigation.filters.get("breachedMetric")
        if isinstance(snapshot, dict):
            source["snapshot"] = snapshot
        identity = {
            "templateKey": investigation.template_key,
            "type": source_type,
            "ref": investigation.source_ref,
        }
        lineage_key = hashlib.sha256(json.dumps(identity, sort_keys=True).encode()).hexdigest()
        updates = {"source": source, "lineage_key": lineage_key}
        active_key = investigation.organization_id, lineage_key
        if investigation.status == "active":
            if active_key in active_by_lineage:
                updates["status"] = "archived"
            else:
                active_by_lineage[active_key] = investigation.id
        Investigation.objects.using(schema_editor.connection.alias).filter(
            id=investigation.id
        ).update(**updates)


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("investigations", "0003_remove_investigation_cell_models"),
        ("seer", "0032_add_extras_to_seer_run_milestone"),
        ("sentry", "1153_create_group_action_log_outbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigation",
            name="lineage_key",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="investigation",
            name="source",
            field=models.JSONField(db_default={}, default=dict),
        ),
        migrations.RunPython(
            move_sources,
            migrations.RunPython.noop,
            hints={"tables": ["investigations_investigation"]},
        ),
        migrations.AddConstraint(
            model_name="investigation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lineage_key__isnull", False)),
                fields=("organization", "lineage_key", "source_revision"),
                name="investigation_unique_lineage_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="investigation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lineage_key__isnull", False), ("status", "active")),
                fields=("organization", "lineage_key"),
                name="investigation_unique_active_lineage",
            ),
        ),
    ]
