# Generated by Django 5.2.15 on 2026-09-16 00:00

from sentry.new_migrations.migrations import CheckedMigration
from sentry.new_migrations.monkey.special import SafeRunSQL


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("investigations", "0008_delete_investigation_cell_tables"),
    ]

    operations = [
        # `0007` turned the producing_seer_run foreign key into a plain integer in Django's
        # state only, so the index the field carried survives in the database with nothing
        # declaring it. No state operations, because the state has no index to remove.
        # DROP INDEX CONCURRENTLY blocks neither reads nor writes.
        SafeRunSQL(
            sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS "
                '"investigations_investigati_producing_seer_run_id_dafebd0c";'
            ),
            reverse_sql="""
            CREATE INDEX CONCURRENTLY IF NOT EXISTS
            "investigations_investigati_producing_seer_run_id_dafebd0c"
            ON "investigations_investigationblock" ("producing_seer_run_id");
            """,
            hints={"tables": ["investigations_investigationblock"]},
            use_statement_timeout=False,
        ),
    ]
