from __future__ import annotations

import logging

from sentry.integrations.coding_agent.client import CodingAgentClient
from sentry.integrations.coding_agent.models import CodingAgentLaunchRequest
from sentry.integrations.github_copilot.models import (
    GithubCopilotJobRequest,
    GithubCopilotJobResponse,
    GithubCopilotJobStatusResponse,
    GithubCopilotPRConfig,
    GithubPRDetails,
)
from sentry.seer.autofix.utils import CodingAgentProviderType, CodingAgentState, CodingAgentStatus

logger = logging.getLogger(__name__)


class GithubCopilotAgentClient(CodingAgentClient):
    integration_name = "github_copilot"
    base_url = "https://api.githubcopilot.com"

    def __init__(self, user_access_token: str):
        super().__init__()
        self.token = user_access_token

    def _get_auth_headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.token}",
            "User-Agent": "sentry",
        }

    @staticmethod
    def encode_agent_id(owner: str, repo: str, job_id: str) -> str:
        return f"{owner}:{repo}:{job_id}"

    @staticmethod
    def decode_agent_id(agent_id: str) -> tuple[str, str, str] | None:
        parts = agent_id.split(":", 2)
        if len(parts) != 3:
            return None
        return parts[0], parts[1], parts[2]

    def launch(self, *, webhook_url: str, request: CodingAgentLaunchRequest) -> CodingAgentState:
        owner = request.repository.owner
        repo = request.repository.name

        payload = GithubCopilotJobRequest(
            problem_statement=request.prompt,
            content_filter_mode="hidden_characters",
            pull_request=GithubCopilotPRConfig(
                title=f"fix: {request.branch_name}",
                body_suffix="\n\n---\n🤖 Generated by Sentry + GitHub Copilot",
            ),
            run_name="Sentry Issue Fix",
            event_type="sentry",
        )

        logger.info(
            "coding_agent.github_copilot.launch",
            extra={
                "owner": owner,
                "repo": repo,
                "agent_type": self.__class__.__name__,
            },
        )

        api_response = self.post(
            f"/agents/swe/v1/jobs/{owner}/{repo}",
            headers={
                "content-type": "application/json;charset=utf-8",
                **self._get_auth_headers(),
            },
            data=payload.dict(exclude_none=True),
            json=True,
            timeout=60,
        )

        logger.info(
            "coding_agent.github_copilot.response",
            extra={
                "owner": owner,
                "repo": repo,
                "status_code": api_response.status_code,
                "response_body": api_response.json,
                "response_text": api_response.text,
            },
        )

        job_response = GithubCopilotJobResponse.validate(api_response.json)
        agent_id = self.encode_agent_id(owner, repo, job_response.job_id)

        return CodingAgentState(
            id=agent_id,
            status=CodingAgentStatus.RUNNING,
            provider=CodingAgentProviderType.GITHUB_COPILOT_AGENT,
            name="GitHub Copilot",
            started_at=job_response.created_at,
            agent_url=None,
        )

    def get_job_status(self, owner: str, repo: str, job_id: str) -> GithubCopilotJobStatusResponse:
        api_response = self.get(
            f"/agents/swe/v1/jobs/{owner}/{repo}/{job_id}",
            headers=self._get_auth_headers(),
            timeout=30,
        )

        logger.info(
            "coding_agent.github_copilot.get_job_status",
            extra={
                "owner": owner,
                "repo": repo,
                "job_id": job_id,
                "status_code": api_response.status_code,
            },
        )

        return GithubCopilotJobStatusResponse.validate(api_response.json)

    def get_pr_details(self, owner: str, repo: str, pr_number: int) -> GithubPRDetails:
        api_response = self.get(
            f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}",
            headers={
                **self._get_auth_headers(),
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            timeout=30,
        )

        logger.info(
            "coding_agent.github_copilot.get_pr_details",
            extra={
                "owner": owner,
                "repo": repo,
                "pr_number": pr_number,
                "status_code": api_response.status_code,
            },
        )

        return GithubPRDetails(
            title=api_response.json["title"],
            body=api_response.json.get("body"),
            state=api_response.json["state"],
        )
