# Generated by Django 5.1.1 on 2024-09-24 20:48

import django.utils.timezone
from django.db import migrations, models

import sentry.db.models.fields.jsonfield
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    checked = False

    dependencies = [
        ("taskworker", "0002_flatten_retry_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="InflightActivationModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("taskname", models.CharField(max_length=255, null=True)),
                ("namespace", models.CharField(max_length=255, null=True)),
                ("parameters", sentry.db.models.fields.jsonfield.JSONField(null=True)),
                ("headers", sentry.db.models.fields.jsonfield.JSONField(null=True)),
                ("received_at", models.DateTimeField()),
                ("deadline", models.DateTimeField(null=True)),
                ("retry_attempts", models.IntegerField(default=0)),
                ("retry_kind", models.CharField(blank=True, max_length=255, null=True)),
                ("deadletter_after_attempt", models.IntegerField(blank=True, null=True)),
                ("discard_after_attempt", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField()),
                ("offset", models.IntegerField()),
                ("added_at", models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ("deadletter_at", models.DateTimeField(blank=True, null=True)),
                ("processing_deadline", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="PendingTasks",
        ),
    ]
