# Generated by Django 5.2.8 on 2026-01-26 21:34

from django.db import migrations
from django.db.models import deletion

from sentry.db.models.fields.foreignkey import FlexibleForeignKey
from sentry.new_migrations.migrations import CheckedMigration
from sentry.new_migrations.monkey.models import SafeDeleteModel
from sentry.new_migrations.monkey.special import SafeRunSQL
from sentry.new_migrations.monkey.state import DeletionAction


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("prevent", "0002_alter_integration_id_not_null"),
        ("sentry", "1020_alter_apiapplication_client_secret_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preventaiconfiguration",
            name="organization",
            field=FlexibleForeignKey(
                db_constraint=False,
                on_delete=deletion.CASCADE,
                to="sentry.organization",
            ),
        ),
        SafeRunSQL(
            sql="ALTER TABLE prevent_ai_configuration DROP CONSTRAINT IF EXISTS prevent_ai_configur_organization_id_69ec9fa2_fk_sentry_or;",
            reverse_sql=migrations.RunSQL.noop,
            hints={"tables": ["prevent_ai_configuration"]},
        ),
        SafeDeleteModel(
            name="PreventAIConfiguration",
            deletion_action=DeletionAction.MOVE_TO_PENDING,
        ),
    ]
