class SCMError(Exception): ...


class SCMIntegrationNotFound(SCMError): ...


class SCMRateLimitExceeded(SCMError): ...


class SCMRepositoryNotFound(SCMError): ...


class SCMRepositoryInactive(SCMError): ...


class SCMRepositoryOrganizationMismatch(SCMError): ...


class SCMUnsupportedIntegrationSpecified(SCMError): ...
