# Generated by Django 1.11.29 on 2021-01-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    is_post_deployment = False

    # This flag is used to decide whether to run this migration in a transaction or not.
    # By default we prefer to run in a transaction, but for migrations where you want
    # to `CREATE INDEX CONCURRENTLY` this needs to be set to False. Typically you'll
    # want to create an index concurrently when adding one to an existing table.
    atomic = True

    dependencies = [
        ("nodestore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="data",
            field=models.TextField(),
        ),
    ]
