export const CHART_MAX_BAR_WIDTH = 20;
export const CHART_HIGH_CARDINALITY_THRESHOLD = 20;
export const CHART_AXIS_LABEL_FONT_SIZE = 12;
export const CHART_TOOLTIP_MAX_VALUE_LENGTH = 300;
export const CHART_MAX_SERIES_LENGTH = 40;

export const CHARTS_COLUMN_COUNT = 3;
export const CHARTS_PER_PAGE = CHARTS_COLUMN_COUNT * 4;

export const CHART_SELECTED_SERIES_NAME = 'selected';
export const CHART_BASELINE_SERIES_NAME = 'baseline';
