from __future__ import annotations

MISSING_BASE_GRACE_PERIOD_SECONDS = 600
RECONSTRUCTION_RETRY_COUNTDOWN_SECONDS = 60
SNAPSHOT_ARCHIVE_MANIFEST_FILENAME = "manifest.json"

MAX_PIXELS_PER_BATCH = 40_000_000
MAX_PAIRS_PER_CHUNK = 100
CHUNK_RESULT_FETCH_WORKERS = 8
