# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-18 18:52
from __future__ import unicode_literals

from django.db import migrations
import sentry.db.models.fields.bounded


class Migration(migrations.Migration):
    # This flag is used to mark that a migration shouldn't be automatically run in
    # production. We set this to True for operations that we think are risky and want
    # someone from ops to run manually and monitor.
    # General advice is that if in doubt, mark your migration as `is_dangerous`.
    # Some things you should always mark as dangerous:
    # - Large data migrations. Typically we want these to be run manually by ops so that
    #   they can be monitored. Since data migrations will now hold a transaction open
    #   this is even more important.
    # - Adding columns to highly active tables, even ones that are NULL.
    is_dangerous = False

    # This flag is used to decide whether to run this migration in a transaction or not.
    # By default we prefer to run in a transaction, but for migrations where you want
    # to `CREATE INDEX CONCURRENTLY` this needs to be set to False. Typically you'll
    # want to create an index concurrently when adding one to an existing table.
    atomic = True


    dependencies = [
        ('sentry', '0097_add_sentry_app_id_to_sentry_alertruletriggeraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationonboardingtask',
            name='task',
            field=sentry.db.models.fields.bounded.BoundedPositiveIntegerField(choices=[(1, b'create_project'), (2, b'send_first_event'), (3, b'invite_member'), (4, b'setup_second_platform'), (5, b'setup_user_context'), (6, b'setup_release_tracking'), (7, b'setup_sourcemaps'), (8, b'setup_user_reports'), (9, b'setup_issue_tracker'), (10, b'setup_alert_rules'), (11, b'setup_transactions')]),
        ),
    ]
