# Generated by Django 1.11.29 on 2021-03-12 12:38

from django.db import migrations
from sentry.utils.query import RangeQuerySetWrapperWithProgressBar


def time_to_timestamp_to_hour(apps, schema_editor):
    DiscoverSavedQuery = apps.get_model("sentry", "DiscoverSavedQuery")
    for query in RangeQuerySetWrapperWithProgressBar(DiscoverSavedQuery.objects.all()):
        fields = query.query["fields"]
        if "time" in fields:
            for i, field in enumerate(fields):
                if field == "time":
                    fields[i] = "timestamp.to_hour"
            if query.query["orderby"] in ["time", "-time"]:
                query.query["orderby"] += "stamp.to_hour"
            query.save()


class Migration(migrations.Migration):
    # This flag is used to mark that a migration shouldn't be automatically run in
    # production. We set this to True for operations that we think are risky and want
    # someone from ops to run manually and monitor.
    # General advice is that if in doubt, mark your migration as `is_dangerous`.
    # Some things you should always mark as dangerous:
    # - Large data migrations. Typically we want these to be run manually by ops so that
    #   they can be monitored. Since data migrations will now hold a transaction open
    #   this is even more important.
    # - Adding columns to highly active tables, even ones that are NULL.
    is_dangerous = False

    # This flag is used to decide whether to run this migration in a transaction or not.
    # By default we prefer to run in a transaction, but for migrations where you want
    # to `CREATE INDEX CONCURRENTLY` this needs to be set to False. Typically you'll
    # want to create an index concurrently when adding one to an existing table.
    # You'll also usually want to set this to `False` if you're writing a data
    # migration, since we don't want the entire migration to run in one long-running
    # transaction.
    atomic = False

    dependencies = [
        ("sentry", "0176_remove_targets"),
    ]

    operations = [
        migrations.RunPython(time_to_timestamp_to_hour, reverse_code=migrations.RunPython.noop)
    ]
