# Generated by Django 2.2.28 on 2023-02-13 17:12

from django.db import migrations

import sentry.db.models.fields.hybrid_cloud_foreign_key
from sentry.new_migrations.migrations import CheckedMigration

# DO NOT MERGE THIS MIGRATION.  It is intended as a staging ground for the aggregate of all migrations.  Instead, break
# off each individual domain migration into a smaller migration in a separate PR and work that into master alongside
# the necessary query changes in this PR.


def exported_data_user_migrations():
    database_operations = [
        migrations.AlterField(
            model_name="exporteddata",
            name="user",
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                to="sentry.User", db_constraint=False, db_index=True, null=True
            ),
        ),
    ]

    state_operations = [
        migrations.AlterField(
            model_name="exporteddata",
            name="user",
            field=sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                "sentry.User", db_index=True, null=True, on_delete="SET_NULL"
            ),
        ),
        migrations.RenameField(
            model_name="exporteddata",
            old_name="user",
            new_name="user_id",
        ),
    ]

    return database_operations + [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]


def alertruleactivity_user_migrations():
    database_operations = [
        migrations.AlterField(
            model_name="alertruleactivity",
            name="user",
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                to="sentry.User", db_constraint=False, db_index=True, null=True
            ),
        ),
    ]

    state_operations = [
        migrations.AlterField(
            model_name="alertruleactivity",
            name="user",
            field=sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                "sentry.User", db_index=True, null=True, on_delete="SET_NULL"
            ),
        ),
        migrations.RenameField(
            model_name="alertruleactivity",
            old_name="user",
            new_name="user_id",
        ),
    ]

    return database_operations + [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]


def discover_saved_query_user_migrations():
    database_operations = [
        migrations.AlterField(
            model_name="discoversavedquery",
            name="created_by",
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                to="sentry.User", db_constraint=False, db_index=True, null=True
            ),
        ),
    ]

    state_operations = [
        migrations.AlterField(
            model_name="discoversavedquery",
            name="created_by",
            field=sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                "sentry.User", db_index=True, null=True, on_delete="SET_NULL"
            ),
        ),
        migrations.RenameField(
            model_name="discoversavedquery",
            old_name="created_by",
            new_name="created_by_id",
        ),
    ]

    return database_operations + [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]


def incidentsubscription_user_migrations():
    database_operations = [
        migrations.AlterField(
            model_name="incidentsubscription",
            name="user",
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                to="sentry.User", db_constraint=False, db_index=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="incidentsubscription",
            unique_together={("incident", "user_id")},
        ),
    ]

    state_operations = [
        migrations.AlterField(
            model_name="incidentsubscription",
            name="user",
            field=sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                "sentry.User", db_index=True, on_delete="CASCADE"
            ),
        ),
        migrations.RenameField(
            model_name="incidentsubscription",
            old_name="user",
            new_name="user_id",
        ),
    ]

    return database_operations + [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production. For
    # the most part, this should only be used for operations where it's safe to run the migration
    # after your code has deployed. So this should not be used for most operations that alter the
    # schema of a table.
    # Here are some things that make sense to mark as dangerous:
    # - Large data migrations. Typically we want these to be run manually by ops so that they can
    #   be monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   have ops run this and not block the deploy. Note that while adding an index is a schema
    #   change, it's completely safe to run the operation after the code has deployed.
    is_dangerous = False

    dependencies = [
        ("sentry", "0354_break_saved_search_foreign_key"),
    ]

    operations = (
        exported_data_user_migrations()
        + discover_saved_query_user_migrations()
        + alertruleactivity_user_migrations()
        + incidentsubscription_user_migrations()
    )
