# Generated by Django 2.2.28 on 2023-02-23 20:59

from django.db import migrations, models

import sentry.db.models.fields.hybrid_cloud_foreign_key
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production. For
    # the most part, this should only be used for operations where it's safe to run the migration
    # after your code has deployed. So this should not be used for most operations that alter the
    # schema of a table.
    # Here are some things that make sense to mark as dangerous:
    # - Large data migrations. Typically we want these to be run manually by ops so that they can
    #   be monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   have ops run this and not block the deploy. Note that while adding an index is a schema
    #   change, it's completely safe to run the operation after the code has deployed.
    is_dangerous = False

    dependencies = [
        ("sentry", "0360_authenticator_config_type_change"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlogentry",
            name="sentry_audi_organiz_c8bd18_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlogentry",
            name="sentry_audi_organiz_588b1e_idx",
        ),
        migrations.RemoveField(
            model_name="auditlogentry",
            name="organization",
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="organization_id",
            field=sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                "sentry.Organization", db_index=True, default=-1, on_delete="SET_NULL"
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(
                fields=["organization_id", "datetime"], name="sentry_audi_organiz_c8bd18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(
                fields=["organization_id", "event", "datetime"],
                name="sentry_audi_organiz_588b1e_idx",
            ),
        ),
    ]
