# Generated by Django 2.2.28 on 2023-03-07 17:55
from django.db import connection, migrations
from psycopg2.extras import execute_values

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.query import RangeQuerySetWrapperWithProgressBar

BATCH_SIZE = 100
DEFAULT_ENVIRONMENT_NAME = "production"

UPDATE_QUERY = """
    UPDATE sentry_monitorcheckin
    SET monitor_environment_id = data.monitor_environment_id
    FROM (VALUES %s) AS data (id, monitor_environment_id)
    WHERE sentry_monitorcheckin.id = data.id"""


def backfill_monitor_checkins(apps, schema_editor):
    MonitorCheckIn = apps.get_model("sentry", "MonitorCheckIn")
    MonitorEnvironment = apps.get_model("sentry", "MonitorEnvironment")
    Environment = apps.get_model("sentry", "Environment")
    EnvironmentProject = apps.get_model("sentry", "EnvironmentProject")

    queryset = RangeQuerySetWrapperWithProgressBar(
        MonitorCheckIn.objects.all().select_related("monitor")
    )
    cursor = connection.cursor()
    batch = []
    for monitor_checkin in queryset:
        if monitor_checkin.monitor_environment:
            pass

        monitor = monitor_checkin.monitor

        environment = Environment.objects.get_or_create(
            name=DEFAULT_ENVIRONMENT_NAME, organization_id=monitor.organization_id
        )[0]

        EnvironmentProject.objects.get_or_create(
            project_id=monitor_checkin.project_id, environment=environment, is_hidden=None
        )

        monitorenvironment_defaults = {
            "status": monitor.status,
            "next_checkin": monitor.next_checkin,
            "last_checkin": monitor.last_checkin,
        }
        monitor_environment = MonitorEnvironment.objects.get_or_create(
            monitor=monitor, environment=environment, defaults=monitorenvironment_defaults
        )[0]

        batch.append((monitor_checkin.id, monitor_environment.id))
        if len(batch) >= BATCH_SIZE:
            execute_values(cursor, UPDATE_QUERY, batch, page_size=BATCH_SIZE)
            batch = []

    if batch:
        execute_values(cursor, UPDATE_QUERY, batch, page_size=BATCH_SIZE)


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production. For
    # the most part, this should only be used for operations where it's safe to run the migration
    # after your code has deployed. So this should not be used for most operations that alter the
    # schema of a table.
    # Here are some things that make sense to mark as dangerous:
    # - Large data migrations. Typically we want these to be run manually by ops so that they can
    #   be monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   have ops run this and not block the deploy. Note that while adding an index is a schema
    #   change, it's completely safe to run the operation after the code has deployed.
    is_dangerous = True

    dependencies = [
        ("sentry", "0373_dist_id_to_name"),
    ]

    operations = [
        migrations.RunPython(
            backfill_monitor_checkins,
            migrations.RunPython.noop,
            hints={
                "tables": [
                    "sentry_monitorcheckin",
                    "sentry_monitorenvironment",
                    "sentry_environment",
                    "sentry_environmentproject",
                ]
            },
        ),
    ]
