# Generated by Django 3.2.20 on 2023-08-18 22:52

import django.db.models.deletion
from django.db import migrations, models

import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
import sentry.db.models.fields.jsonfield
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production. For
    # the most part, this should only be used for operations where it's safe to run the migration
    # after your code has deployed. So this should not be used for most operations that alter the
    # schema of a table.
    # Here are some things that make sense to mark as dangerous:
    # - Large data migrations. Typically we want these to be run manually by ops so that they can
    #   be monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   have ops run this and not block the deploy. Note that while adding an index is a schema
    #   change, it's completely safe to run the operation after the code has deployed.
    is_dangerous = False

    dependencies = [
        ("sentry", "0534_add_notification_uuid_to_rule_fire_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertProcedure",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("is_manual", models.BooleanField(default=False)),
                ("issue_alert_actions", sentry.db.models.fields.jsonfield.JSONField(default=[])),
                (
                    "organization",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.organization"
                    ),
                ),
            ],
            options={
                "db_table": "sentry_alertprocedure",
                "unique_together": {("organization", "label")},
            },
        ),
        migrations.CreateModel(
            name="AlertTemplate",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("issue_alert_data", sentry.db.models.fields.jsonfield.JSONField(default={})),
                (
                    "organization",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.organization"
                    ),
                ),
                (
                    "procedure",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.alertprocedure"
                    ),
                ),
            ],
            options={
                "db_table": "sentry_alerttemplate",
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="AlertTemplateIssueAlert",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "rule",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.rule"
                    ),
                ),
                (
                    "template",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.alerttemplate"
                    ),
                ),
            ],
            options={
                "db_table": "sentry_alerttemplateissuealert",
            },
        ),
        migrations.AddField(
            model_name="alerttemplate",
            name="issue_alerts",
            field=models.ManyToManyField(
                through="sentry.AlertTemplateIssueAlert", to="sentry.Rule"
            ),
        ),
    ]
