# Generated by Django 5.1.7 on 2025-03-25 19:24

import django.db.models.deletion
from django.db import migrations

import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
from sentry.new_migrations.migrations import CheckedMigration
from sentry.new_migrations.monkey.fields import SafeRemoveField
from sentry.new_migrations.monkey.state import DeletionAction


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "0846_hard_drop_groupsearchview_position"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="monitorcheckin",
            name="sentry_moni_trace_i_c63ea4_idx",
        ),
        migrations.AlterField(
            model_name="monitorcheckin",
            name="location",
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sentry.monitorlocation",
            ),
        ),
        migrations.AlterField(
            model_name="monitorcheckin",
            name="status",
            field=sentry.db.models.fields.bounded.BoundedPositiveIntegerField(default=0),
        ),
        SafeRemoveField(
            model_name="monitorcheckin",
            name="location",
            deletion_action=DeletionAction.MOVE_TO_PENDING,
        ),
    ]
