# Generated by Django 5.1.7 on 2025-04-01 20:22

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models

import sentry.models.groupopenperiod
from sentry.new_migrations.migrations import CheckedMigration
from sentry.new_migrations.monkey.special import SafeRunSQL


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "0855_give_monitor_type_a_db_default"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="groupopenperiod",
            name="exclude_open_period_overlap",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                SafeRunSQL(
                    """ALTER TABLE "sentry_groupopenperiod"
                ADD CONSTRAINT "exclude_open_period_overlap" EXCLUDE USING GIST (
                    "group_id" gist_int8_ops WITH =,
                    (TSTZRANGE("date_started", "date_ended", '[)')) WITH &&
                );""",
                    use_statement_timeout=False,
                    hints={"tables": ["sentry_groupopenperiod"]},
                )
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="groupopenperiod",
                    constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            (models.F("group"), "="),
                            (
                                sentry.models.groupopenperiod.TsTzRange(
                                    "date_started",
                                    "date_ended",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(),
                                ),
                                "&&",
                            ),
                        ],
                        name="exclude_open_period_overlap",
                    ),
                ),
            ],
        ),
    ]
