# Generated by Django 5.1.7 on 2025-04-01 20:22

from django.db import migrations

from sentry.new_migrations.migrations import CheckedMigration
from sentry.new_migrations.monkey.special import SafeRunSQL


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("sentry", "0856_monitors_remove_type_column_state"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="groupopenperiod",
                    name="exclude_open_period_overlap",
                ),
            ],
            database_operations=[
                SafeRunSQL(
                    """
                    ALTER TABLE "sentry_groupopenperiod"
                    DROP CONSTRAINT IF EXISTS "exclude_open_period_overlap";
                    """,
                    hints={"tables": ["sentry_groupopenperiod"]},
                ),
            ],
        ),
        # These two operations weren't able to run together in the right sequence -
        # commenting this out to include in a later migration. This migration now
        # only drops the exclusion constraint.
        # SafeRunSQL(
        #     """ALTER TABLE "sentry_groupopenperiod"
        #         ADD CONSTRAINT "exclude_open_period_overlap" EXCLUDE USING GIST (
        #             "group_id" gist_int8_ops WITH =,
        #             (TSTZRANGE("date_started", "date_ended", '[)')) WITH &&
        #         );""",
        #     use_statement_timeout=False,
        #     hints={"tables": ["sentry_groupopenperiod"]},
        # ),
    ]
