# Generated by Django 5.1.7 on 2025-04-03 17:48

from sentry.new_migrations.migrations import CheckedMigration
from sentry.new_migrations.monkey.special import SafeRunSQL


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("sentry", "0859_monitors_remove_type_column_db"),
    ]

    # Note that this constraint is applied on the table but not explicitly set in the model.
    # See the comment in the model for more info.
    operations = [
        SafeRunSQL(
            """ALTER TABLE "sentry_groupopenperiod"
                ADD CONSTRAINT "exclude_overlapping_start_end" EXCLUDE USING GIST (
                    "group_id" gist_int8_ops WITH =,
                    (TSTZRANGE("date_started", "date_ended", '[)')) WITH &&
                );""",
            use_statement_timeout=False,
            hints={"tables": ["sentry_groupopenperiod"]},
        ),
    ]
