# Generated by Django 5.1.7 on 2025-04-24 19:56

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models

import sentry.db.models.fields.bounded
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "0868_delete_group_open_periods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertruletriggeraction",
            name="status",
            field=sentry.db.models.fields.bounded.BoundedPositiveIntegerField(
                db_default=0, default=0
            ),
        ),
        migrations.AlterField(
            model_name="authidentityreplica",
            name="last_verified",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(),
                default=django.utils.timezone.now,
            ),
        ),
        migrations.AlterField(
            model_name="controloutbox",
            name="date_added",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(),
                default=django.utils.timezone.now,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="dashboardwidgetquery",
            name="date_modified",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(),
                default=django.utils.timezone.now,
            ),
        ),
        migrations.AlterField(
            model_name="dashboardwidgetqueryondemand",
            name="date_added",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(),
                default=django.utils.timezone.now,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="type",
            field=sentry.db.models.fields.bounded.BoundedPositiveIntegerField(
                db_default=1, db_index=True, default=1
            ),
        ),
        migrations.AlterField(
            model_name="perfstringindexer",
            name="use_case_id",
            field=models.CharField(db_default="performance", default="performance", max_length=120),
        ),
        migrations.AlterField(
            model_name="projectdebugfile",
            name="date_accessed",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(),
                default=django.utils.timezone.now,
            ),
        ),
        migrations.AlterField(
            model_name="projectownership",
            name="suspect_committer_auto_assignment",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="regionoutbox",
            name="date_added",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(),
                default=django.utils.timezone.now,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_type",
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.CharField(db_default=None, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_unclaimed",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
