# Generated by Django 5.2.1 on 2025-05-19 21:17

from django.db import migrations

import sentry.db.models.fields.bounded
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "0902_detection_type_match_size"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="exporteddata",
                    name="file_id",
                    field=sentry.db.models.fields.bounded.BoundedBigIntegerField(
                        db_index=True, null=True
                    ),
                ),
                migrations.AlterField(
                    model_name="exporteddatablob",
                    name="blob_id",
                    field=sentry.db.models.fields.bounded.BoundedBigIntegerField(db_index=True),
                ),
                migrations.AlterField(
                    model_name="projectdebugfile",
                    name="project_id",
                    field=sentry.db.models.fields.bounded.BoundedBigIntegerField(
                        db_index=True, null=True
                    ),
                ),
                migrations.AlterField(
                    model_name="releasefile",
                    name="dist_id",
                    field=sentry.db.models.fields.bounded.BoundedBigIntegerField(
                        db_index=True, null=True
                    ),
                ),
                migrations.AlterField(
                    model_name="releasefile",
                    name="organization_id",
                    field=sentry.db.models.fields.bounded.BoundedBigIntegerField(db_index=True),
                ),
                migrations.AlterField(
                    model_name="releasefile",
                    name="release_id",
                    field=sentry.db.models.fields.bounded.BoundedBigIntegerField(db_index=True),
                ),
            ]
        )
    ]
