# Generated by Django 5.2.1 on 2025-06-02 20:17

import logging

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.query import bulk_delete_objects

logger = logging.getLogger(__name__)


def delete_open_periods(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    GroupOpenPeriod = apps.get_model("sentry", "GroupOpenPeriod")

    while GroupOpenPeriod.objects.exists():
        ids = GroupOpenPeriod.objects.values_list("id", flat=True)[:10000]
        bulk_delete_objects(GroupOpenPeriod, id__in=ids)
        logger.info("Deleted open periods", extra={"count": len(ids)})


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("sentry", "0915_add_user_email_unique_column"),
    ]

    operations = [
        migrations.RunPython(
            code=delete_open_periods,
            reverse_code=migrations.RunPython.noop,
            hints={"tables": ["sentry_groupopenperiod"]},
        ),
    ]
