# Generated by Django 5.2.1 on 2025-06-04 21:35

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.models.savedsearch import Visibility
from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.query import RangeQuerySetWrapperWithProgressBar


def convert_org_saved_searches_to_views(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    SavedSearch = apps.get_model("sentry", "SavedSearch")
    GroupSearchView = apps.get_model("sentry", "GroupSearchView")

    org_saved_searches = SavedSearch.objects.filter(
        visibility=Visibility.ORGANIZATION, owner_id__isnull=False
    )

    for saved_search in RangeQuerySetWrapperWithProgressBar(org_saved_searches):
        matching_views = GroupSearchView.objects.filter(
            organization=saved_search.organization,
            user_id=saved_search.owner_id,
            name=saved_search.name,
            query=saved_search.query,
            query_sort=saved_search.sort,
        )

        if matching_views.count() == 0:
            GroupSearchView.objects.create(
                organization=saved_search.organization,
                user_id=saved_search.owner_id,
                name=saved_search.name,
                query=saved_search.query,
                query_sort=saved_search.sort,
                date_added=saved_search.date_added,
            )


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("sentry", "0920_convert_org_saved_searches_to_views_revised"),
    ]

    operations = [
        migrations.RunPython(
            convert_org_saved_searches_to_views,
            reverse_code=migrations.RunPython.noop,
            hints={"tables": ["sentry_groupsearchview", "sentry_savedsearch"]},
        )
    ]
