# Generated by Django 5.2.1 on 2025-06-14 16:22

from django.db import migrations

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "0927_dashboard_add_unique_constraint_user_dashboard"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="notificationactionproject",
                    name="action",
                ),
                migrations.RemoveField(
                    model_name="notificationactionproject",
                    name="project",
                ),
                migrations.RemoveField(
                    model_name="notificationmessage",
                    name="action",
                ),
                migrations.RemoveField(
                    model_name="notificationmessage",
                    name="group",
                ),
                migrations.RemoveField(
                    model_name="notificationmessage",
                    name="incident",
                ),
                migrations.RemoveField(
                    model_name="notificationmessage",
                    name="parent_notification_message",
                ),
                migrations.RemoveField(
                    model_name="notificationmessage",
                    name="rule_fire_history",
                ),
                migrations.RemoveField(
                    model_name="notificationmessage",
                    name="trigger_action",
                ),
                migrations.AlterUniqueTogether(
                    name="notificationsettingoption",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="notificationsettingoption",
                    name="user",
                ),
                migrations.AlterUniqueTogether(
                    name="notificationsettingprovider",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="notificationsettingprovider",
                    name="user",
                ),
                migrations.DeleteModel(
                    name="NotificationAction",
                ),
                migrations.DeleteModel(
                    name="NotificationActionProject",
                ),
                migrations.DeleteModel(
                    name="NotificationMessage",
                ),
                migrations.DeleteModel(
                    name="NotificationSettingOption",
                ),
                migrations.DeleteModel(
                    name="NotificationSettingProvider",
                ),
            ]
        )
    ]
