# Generated by Django 5.2.1 on 2025-06-23 19:21

from typing import LiteralString

from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration
from sentry.new_migrations.monkey.special import SafeRunSQL


def _option_value_to_json(table: LiteralString) -> SafeRunSQL:
    return SafeRunSQL(
        f"""
        ALTER TABLE {table} ALTER COLUMN value TYPE jsonb USING value::jsonb;
        """,
        reverse_sql=f"""
        ALTER TABLE {table} ALTER COLUMN value TYPE text;
        """,
        hints={"tables": [table]},
    )


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("sentry", "0936_prompts_activity_index"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                _option_value_to_json("sentry_controloption"),
                _option_value_to_json("sentry_option"),
                _option_value_to_json("sentry_organizationoptions"),
                _option_value_to_json("sentry_projectoptions"),
                _option_value_to_json("sentry_projecttemplateoption"),
                _option_value_to_json("sentry_useroption"),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="controloption",
                    name="value",
                    field=models.JSONField(null=True),
                ),
                migrations.AlterField(
                    model_name="option",
                    name="value",
                    field=models.JSONField(null=True),
                ),
                migrations.AlterField(
                    model_name="organizationoption",
                    name="value",
                    field=models.JSONField(null=True),
                ),
                migrations.AlterField(
                    model_name="projectoption",
                    name="value",
                    field=models.JSONField(null=True),
                ),
                migrations.AlterField(
                    model_name="projecttemplateoption",
                    name="value",
                    field=models.JSONField(null=True),
                ),
                migrations.AlterField(
                    model_name="useroption",
                    name="value",
                    field=models.JSONField(null=True),
                ),
            ],
        )
    ]
