# Generated by Django 5.2.8 on 2025-11-21 21:54

import django.db.models.deletion
from django.db import migrations, models

import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
import sentry.db.models.fields.hybrid_cloud_foreign_key
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "1009_add_date_updated_to_organizationmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationContributors",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "integration_id",
                    sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                        "sentry.Integration", db_index=True, on_delete="CASCADE"
                    ),
                ),
                ("external_identifier", models.CharField(db_index=True, max_length=255)),
                ("alias", models.CharField(blank=True, max_length=255, null=True)),
                ("num_actions", sentry.db.models.fields.bounded.BoundedIntegerField(default=0)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.organization"
                    ),
                ),
            ],
            options={
                "db_table": "sentry_organizationcontributors",
                "indexes": [
                    models.Index(
                        fields=["organization_id", "date_updated"],
                        name="sentry_oc_org_date_upd_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "integration_id", "external_identifier"),
                        name="sentry_orgcont_unique_org_cont",
                    )
                ],
            },
        ),
    ]
