# Generated by Django 5.2.8 on 2025-12-19 23:11

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.new_migrations.migrations import CheckedMigration


def backfill_on_command_phrase_trigger(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Backfill on_command_phrase code review trigger for all existing RepositorySettings and Organization defaultCodeReviewTriggers."""
    RepositorySettings = apps.get_model("sentry", "RepositorySettings")
    OrganizationOption = apps.get_model("sentry", "OrganizationOption")

    # Backfill RepositorySettings
    settings_to_update = []

    for setting in RepositorySettings.objects.all():
        triggers = list(setting.code_review_triggers or [])
        if "on_command_phrase" not in triggers:
            setting.code_review_triggers = triggers + ["on_command_phrase"]
            settings_to_update.append(setting)

    if settings_to_update:
        RepositorySettings.objects.bulk_update(settings_to_update, ["code_review_triggers"])

    # Backfill Organization defaultCodeReviewTriggers
    org_options_to_update = []

    for org_option in OrganizationOption.objects.filter(key="sentry:default_code_review_triggers"):
        triggers = list(org_option.value or [])
        if "on_command_phrase" not in triggers:
            org_option.value = triggers + ["on_command_phrase"]
            org_options_to_update.append(org_option)

    if org_options_to_update:
        OrganizationOption.objects.bulk_update(org_options_to_update, ["value"])


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "1014_add_pkce_to_apigrant"),
    ]

    operations = [
        migrations.RunPython(
            backfill_on_command_phrase_trigger,
            reverse_code=migrations.RunPython.noop,
            hints={"tables": ["sentry_repositorysettings", "sentry_organizationoptions"]},
        ),
    ]
