# Generated by Django 5.2.8 on 2026-01-08 18:18

import django.contrib.postgres.fields
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.new_migrations.migrations import CheckedMigration


def remove_on_command_phrase_from_repository_settings(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Remove 'on_command_phrase' from RepositorySettings.code_review_triggers."""
    RepositorySettings = apps.get_model("sentry", "RepositorySettings")

    all_settings = list(RepositorySettings.objects.all())

    updated_settings = []
    for settings in all_settings:
        if (
            settings.code_review_triggers
            and isinstance(settings.code_review_triggers, list)
            and "on_command_phrase" in settings.code_review_triggers
        ):
            settings.code_review_triggers = [
                trigger
                for trigger in settings.code_review_triggers
                if trigger != "on_command_phrase"
            ]
            updated_settings.append(settings)

    if updated_settings:
        RepositorySettings.objects.bulk_update(updated_settings, fields=["code_review_triggers"])


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "1015_backfill_self_hosted_sentry_app_emails"),
    ]

    operations = [
        migrations.RunPython(
            remove_on_command_phrase_from_repository_settings,
            reverse_code=migrations.RunPython.noop,
            hints={"tables": ["sentry_repositorysettings"]},
        ),
        migrations.AlterField(
            model_name="repositorysettings",
            name="code_review_triggers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("on_new_commit", "on_new_commit"),
                        ("on_ready_for_review", "on_ready_for_review"),
                    ],
                    max_length=32,
                ),
                default=list,
            ),
        ),
    ]
