# Generated by Django 5.2.8 on 2026-01-14 23:23

import django.utils.timezone
from django.db import migrations, models

import sentry.db.models.fields.bounded
import sentry.db.models.fields.hybrid_cloud_foreign_key
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "1018_encrypt_integration_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedIdentityProvider",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "organization_id",
                    sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                        "sentry.Organization", db_index=True, on_delete="CASCADE"
                    ),
                ),
                ("issuer", models.CharField(max_length=512)),
                ("name", models.CharField(max_length=100)),
                ("jwks_uri", models.URLField(max_length=512)),
                ("jwks_cache", models.JSONField(blank=True, null=True)),
                ("jwks_cached_at", models.DateTimeField(blank=True, null=True)),
                ("subject_claim", models.CharField(default="sub", max_length=50)),
                ("tenant_claim", models.CharField(blank=True, max_length=50, null=True)),
                ("allowed_client_ids", models.JSONField(default=list)),
                ("allowed_scopes", models.JSONField(default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "sentry_trustedidentityprovider",
                "unique_together": {("organization_id", "issuer")},
            },
        ),
    ]
