# Generated by Django 5.2.8 on 2026-01-30 21:35

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.query import RangeQuerySetWrapperWithProgressBar


def delete_duplicate_commit_comparisons(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """
    Delete duplicate CommitComparison records, keeping the oldest (lowest ID) for each unique
    combination of (organization_id, head_repo_name, head_sha, base_sha).

    Before deleting, updates PreprodArtifact foreign key references to point to the kept record.
    """
    CommitComparison = apps.get_model("sentry", "CommitComparison")
    PreprodArtifact = apps.get_model("preprod", "PreprodArtifact")

    key_to_kept_id: dict[tuple[int, str, str, str | None], int] = {}
    duplicate_to_kept: dict[int, int] = {}

    for record in RangeQuerySetWrapperWithProgressBar(CommitComparison.objects.all()):
        key = (record.organization_id, record.head_repo_name, record.head_sha, record.base_sha)

        if key in key_to_kept_id:
            duplicate_to_kept[record.id] = key_to_kept_id[key]
        else:
            key_to_kept_id[key] = record.id

    if duplicate_to_kept:
        for duplicate_id, kept_id in duplicate_to_kept.items():
            PreprodArtifact.objects.filter(commit_comparison_id=duplicate_id).update(
                commit_comparison_id=kept_id
            )
        CommitComparison.objects.filter(id__in=duplicate_to_kept.keys()).delete()


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("sentry", "1022_add_event_id_to_groupopenperiodactivity"),
        ("preprod", "0026_add_initial_snapshot_models"),
    ]

    operations = [
        migrations.RunPython(
            delete_duplicate_commit_comparisons,
            reverse_code=migrations.RunPython.noop,
            hints={"tables": ["sentry_commitcomparison", "sentry_preprodartifact"]},
        ),
        migrations.AddConstraint(
            model_name="commitcomparison",
            constraint=models.UniqueConstraint(
                condition=models.Q(("base_sha__isnull", False)),
                fields=("organization_id", "head_repo_name", "head_sha", "base_sha"),
                name="sentry_commitcomparison_org_comparison_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="commitcomparison",
            constraint=models.UniqueConstraint(
                condition=models.Q(("base_sha__isnull", True)),
                fields=("organization_id", "head_repo_name", "head_sha"),
                name="sentry_commitcomparison_org_commit_uniq",
            ),
        ),
    ]
