# Generated by Django 5.2.11 on 2026-02-17 21:29

import django.db.models.deletion
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
import sentry.db.models.fields.hybrid_cloud_foreign_key
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "1030_add_commitcomparison_extras"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_id",
                    sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                        "sentry.User", db_index=True, null=True, on_delete="SET_NULL"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(),
                ),
                (
                    "source_id",
                    sentry.db.models.fields.bounded.BoundedBigIntegerField(db_index=True),
                ),
                (
                    "frequency",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(),
                ),
                (
                    "day_of_week",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(
                        blank=True, null=True
                    ),
                ),
                (
                    "day_of_month",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(
                        blank=True, null=True
                    ),
                ),
                ("hour", sentry.db.models.fields.bounded.BoundedPositiveIntegerField()),
                ("time_range", models.CharField(blank=True, max_length=32, null=True)),
                ("recipient_emails", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField(db_index=True)),
                (
                    "organization",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sentry.organization",
                    ),
                ),
            ],
            options={
                "db_table": "sentry_scheduledreport",
                "indexes": [
                    models.Index(
                        fields=["organization", "source_type", "source_id"],
                        name="sentry_sche_organiz_15bc2b_idx",
                    ),
                    models.Index(
                        fields=["is_active", "next_run_at"],
                        name="sentry_sche_is_acti_fbe604_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "time_range__in",
                                ("1h", "1d", "24h", "7d", "14d", "30d", "90d"),
                            ),
                            ("time_range", None),
                            _connector="OR",
                        ),
                        name="sentry_scheduledreport_valid_time_range",
                    )
                ],
            },
        ),
    ]
