# Generated by Django 5.2.12 on 2026-04-30 09:08

import django.db.models.deletion
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
import sentry.db.models.fields.hybrid_cloud_foreign_key
import uuid
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "1074_remove_dashboardtombstone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInboundFilter",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("rule_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("user_identifier", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "created_by_id",
                    sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                        "sentry.User", db_index=True, null=True, on_delete="SET_NULL"
                    ),
                ),
                (
                    "updated_by_id",
                    sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                        "sentry.User", db_index=True, null=True, on_delete="SET_NULL"
                    ),
                ),
                ("filter_type", models.CharField(max_length=32)),
                ("value", models.TextField()),
                ("value_hash", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "organization",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.organization"
                    ),
                ),
                (
                    "project",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.project"
                    ),
                ),
            ],
            options={
                "db_table": "sentry_projectinboundfilter",
                "indexes": [
                    models.Index(
                        fields=["organization", "project", "filter_type", "id"],
                        name="sentry_pif_org_proj_type_id",
                    ),
                    models.Index(
                        fields=["project", "filter_type", "id"], name="sentry_pif_proj_type_id"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "filter_type__in",
                                [
                                    "ip_address",
                                    "release",
                                    "error_message",
                                    "log_message",
                                    "trace_metric_name",
                                ],
                            )
                        ),
                        name="sentry_pif_type_known",
                    ),
                    models.UniqueConstraint(
                        fields=("project", "filter_type", "value_hash"),
                        name="sentry_pif_proj_type_val_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user_identifier__isnull", False)),
                        fields=("project", "user_identifier"),
                        name="sentry_pif_proj_userid_uniq",
                    ),
                ],
            },
        ),
    ]
