# Generated by Django 5.2.14 on 2026-05-14 00:04

import django.db.models.deletion
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
import sentry.db.models.fields.hybrid_cloud_foreign_key
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "1086_add_source_to_external_actor"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupDerivedData",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(default=1),
                ),
                (
                    "cursor",
                    sentry.db.models.fields.bounded.BoundedBigIntegerField(default=0),
                ),
                ("data", models.JSONField(default=dict)),
                ("primary", models.BooleanField(default=False)),
                (
                    "group",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.group"
                    ),
                ),
            ],
            options={
                "db_table": "sentry_groupderiveddata",
                "indexes": [
                    models.Index(fields=["version"], name="sentry_grou_version_6c96e2_idx"),
                    models.Index(
                        fields=["group", "primary"],
                        name="sentry_grou_group_i_1762f9_idx",
                    ),
                ],
                "unique_together": {("group", "version")},
            },
        ),
        migrations.CreateModel(
            name="IssueActionLog",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("type", sentry.db.models.fields.bounded.BoundedPositiveIntegerField()),
                (
                    "user_id",
                    sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                        "sentry.User", db_index=True, null=True, on_delete="DO_NOTHING"
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("idempotency_key", models.CharField(max_length=64, null=True)),
                (
                    "group",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.group"
                    ),
                ),
            ],
            options={
                "db_table": "sentry_issueactionlog",
                "indexes": [
                    models.Index(fields=["group", "id"], name="sentry_issu_group_i_506da3_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("group", "idempotency_key"),
                        name="uniq_issueactionlog_group_idempotency_key",
                    )
                ],
            },
        ),
    ]
