# Generated by Django 5.2.12 on 2026-05-13 12:00

import logging

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.new_migrations.migrations import CheckedMigration

logger = logging.getLogger(__name__)

_OLD_FILTER = "span.name:mcp.server"
_NEW_FILTER = "span.op:mcp.server"


def backfill_mcp_dashboard_widget_filters(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """
    The MCP pre-built dashboards filtered spans on `span.name:mcp.server`, but
    a recent Relay change corrected the `name` of MCP spans, so that filter no
    longer matches. The fix in code switched to `span.op:mcp.server`, but any
    widgets already saved with the old condition (from prebuilt dashboards that
    were copied/customized, or from users who hand-typed the filter) are still
    broken. Replace the literal substring everywhere it appears in
    DashboardWidgetQuery.conditions.
    """
    DashboardWidgetQuery = apps.get_model("sentry", "DashboardWidgetQuery")

    updated = 0
    rows = DashboardWidgetQuery.objects.filter(conditions__contains=_OLD_FILTER).values_list(
        "id", "conditions"
    )
    for row_id, conditions in rows:
        new_conditions = conditions.replace(_OLD_FILTER, _NEW_FILTER)
        if new_conditions == conditions:
            continue
        DashboardWidgetQuery.objects.filter(id=row_id).update(conditions=new_conditions)
        updated += 1

    logger.info("backfill_mcp_dashboard_widget_filters: complete, updated=%d", updated)


class Migration(CheckedMigration):
    is_post_deployment = True

    dependencies = [
        ("sentry", "1095_make_project_repository_fk_notnull"),
    ]

    operations = [
        migrations.RunPython(
            backfill_mcp_dashboard_widget_filters,
            reverse_code=migrations.RunPython.noop,
            hints={"tables": ["sentry_dashboardwidgetquery"]},
        ),
    ]
