# Generated by Django 5.2.14 on 2026-05-19 00:24

import django.db.models.functions.datetime
import sentry.db.models.fields.bounded
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "1097_add_new_unique_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueActionLogEntry",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("group_id", sentry.db.models.fields.bounded.BoundedBigIntegerField()),
                (
                    "project_id",
                    sentry.db.models.fields.bounded.BoundedBigIntegerField(),
                ),
                (
                    "original_group_id",
                    sentry.db.models.fields.bounded.BoundedBigIntegerField(null=True),
                ),
                ("type", sentry.db.models.fields.bounded.BoundedPositiveIntegerField()),
                (
                    "actor_type",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(),
                ),
                ("actor_id", sentry.db.models.fields.bounded.BoundedBigIntegerField()),
                ("data", models.JSONField(default=dict)),
                (
                    "date_added",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("idempotency_key", models.CharField(max_length=64, null=True)),
            ],
            options={
                "db_table": "sentry_issueactionlogentry",
                "indexes": [
                    models.Index(
                        fields=["group_id", "date_added", "id"],
                        name="sentry_issu_group_i_ff3639_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("group_id", "idempotency_key"),
                        name="uniq_issueactionlogentry_group_idempotency_key",
                    )
                ],
            },
        ),
    ]
