# Generated by Django 5.2.14 on 2026-06-09 20:58

import datetime
import django.db.models.deletion
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "1110_add_team_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupDerivedData",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "cursor_date",
                    models.DateTimeField(
                        default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
                    ),
                ),
                (
                    "cursor_id",
                    sentry.db.models.fields.bounded.BoundedBigIntegerField(default=0),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "view_count",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(default=0),
                ),
                (
                    "progress",
                    models.CharField(default="identified", max_length=32, null=True),
                ),
                ("last_progressed_at", models.DateTimeField(default=None, null=True)),
                (
                    "group",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sentry.group",
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "sentry_groupderiveddata",
                "indexes": [
                    models.Index(
                        fields=["progress", "group"],
                        name="sentry_grou_progres_f1627f_idx",
                    ),
                    models.Index(
                        fields=["last_progressed_at", "group"],
                        name="sentry_grou_last_pr_8c8185_idx",
                    ),
                ],
            },
        ),
    ]
