# Generated by Django 5.2.15 on 2026-08-12 16:57

import datetime
import django.db.models.functions.datetime
import django.utils.timezone
import sentry.db.models.fields.bounded
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "1152_organizationmemberteam_add_new_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupActionLogOutbox",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("shard_scope", sentry.db.models.fields.bounded.BoundedPositiveIntegerField()),
                ("shard_identifier", sentry.db.models.fields.bounded.BoundedBigIntegerField()),
                ("category", sentry.db.models.fields.bounded.BoundedPositiveIntegerField()),
                ("object_identifier", sentry.db.models.fields.bounded.BoundedBigIntegerField()),
                ("payload", models.JSONField(null=True)),
                ("scheduled_from", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        default=datetime.datetime(2016, 8, 1, 0, 0, tzinfo=datetime.timezone.utc)
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
            ],
            options={
                "db_table": "sentry_groupactionlogoutbox",
                "indexes": [
                    models.Index(
                        fields=["shard_scope", "shard_identifier", "category", "object_identifier"],
                        name="sentry_grou_shard_s_30f0b8_idx",
                    ),
                    models.Index(
                        fields=["shard_scope", "shard_identifier", "scheduled_for"],
                        name="sentry_grou_shard_s_298428_idx",
                    ),
                    models.Index(
                        fields=["shard_scope", "shard_identifier", "id"],
                        name="sentry_grou_shard_s_359989_idx",
                    ),
                ],
            },
        ),
    ]
