# Generated by Django 5.2.16 on 2026-08-28 03:46

import django.db.models.deletion
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
import sentry.db.models.fields.hybrid_cloud_foreign_key
from django.conf import settings
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("sentry", "1159_organizationmemberteam_new_id_unique_not_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAccount",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "organization_id",
                    sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                        "sentry.Organization", db_index=True, on_delete="CASCADE"
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("is_active", models.BooleanField(db_default=True, default=True)),
            ],
            options={
                "db_table": "sentry_serviceaccount",
            },
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="service_account_id",
            field=sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                "sentry.ServiceAccount",
                blank=True,
                db_index=True,
                null=True,
                on_delete="CASCADE",
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="user",
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service_account_id__isnull", False)),
                fields=("organization", "service_account_id"),
                name="sentry_orgmember_org_service_account_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user_id__isnull", True),
                    ("service_account_id__isnull", True),
                    _connector="OR",
                ),
                name="sentry_orgmember_not_user_and_service_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceaccount",
            constraint=models.UniqueConstraint(
                fields=("organization_id", "name"),
                name="sentry_serviceaccount_org_name_unique",
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="service_account",
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_tokens",
                to="sentry.serviceaccount",
            ),
        ),
        migrations.AddField(
            model_name="organizationmembermapping",
            name="service_account",
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orgmembermapping_set",
                to="sentry.serviceaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembermapping",
            index=models.Index(
                fields=["organization_id", "service_account"],
                name="sentry_orga_organiz_f16b8d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="apitoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("service_account__isnull", True), ("user__isnull", False)),
                    models.Q(("service_account__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="sentry_apitoken_exactly_one_principal",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmembermapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", True),
                    ("service_account__isnull", True),
                    _connector="OR",
                ),
                name="sentry_orgmembermapping_not_user_and_service_account",
            ),
        ),
    ]
