# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentry/services/rpc/protobufs/User.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n(sentry/services/rpc/protobufs/User.proto" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t"2\n\x11\x43hangeNameRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t28\n\x0bUserService\x12)\n\nChangeName\x12\x12.ChangeNameRequest\x1a\x05.User"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "sentry.services.rpc.protobufs.User_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _USER._serialized_start = 44
    _USER._serialized_end = 76
    _CHANGENAMEREQUEST._serialized_start = 78
    _CHANGENAMEREQUEST._serialized_end = 128
    _USERSERVICE._serialized_start = 130
    _USERSERVICE._serialized_end = 186
# @@protoc_insertion_point(module_scope)
