#!/bin/bash

if [[ -z "$SOURCE_COMMIT" ]]; then
	export SOURCE_COMMIT="${SOURCE_COMMIT:-$(git rev-parse HEAD)}"
	echo "Updating SOURCE_COMMIT from 'git rev-parse HEAD'"
fi

echo "SOURCE_COMMIT: $SOURCE_COMMIT"

docker build -t "$DOCKER_REPO:$SOURCE_COMMIT" -f $DOCKERFILE_PATH .
