#!/bin/bash

set -e;

if [[ -z "$SOURCE_COMMIT" ]]; then
	export SOURCE_COMMIT="${SOURCE_COMMIT:-$(git rev-parse HEAD)}";
	echo "Updating SOURCE_COMMIT from 'git rev-parse HEAD'";
fi

echo "SOURCE_COMMIT: $SOURCE_COMMIT";

docker push "$DOCKER_REPO:$SOURCE_COMMIT"
docker push "$DOCKER_REPO:$SOURCE_COMMIT-onbuild"
