#!/bin/bash

set -x;

if [[ -z "$SOURCE_COMMIT" ]]; then
	export SOURCE_COMMIT="${SOURCE_COMMIT:-$(git rev-parse HEAD)}";
	echo "Updating SOURCE_COMMIT from 'git rev-parse HEAD'";
fi

echo "SOURCE_COMMIT: $SOURCE_COMMIT";
echo $(pwd);
cd "$(git rev-parse --show-toplevel)/docker";

wget -qO - "https://github.com/getsentry/onpremise/archive/v10.tar.gz" | tar -xzf -;
export SENTRY_IMAGE=getsentry/sentry:git;
cd onpremise-v10;
./install.sh;
docker-compose run --rm web createuser --superuser --email test@sentry.io --password test123TEST;
docker-compose up -d
timeout 60 bash -c 'until $(curl -Isf -o /dev/null http://localhost:9000); do printf '.'; sleep 0.5; done'
