# Generated by Django 5.2.1 on 2025-11-13 19:27

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.query import RangeQuerySetWrapperWithProgressBar


def backfill_monitor_environment_is_muted(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """
    Backfill MonitorEnvironment.is_muted from Monitor.is_muted for all muted monitors.

    After this migration:
    - is_muted=True monitors will have ALL environments muted
    - is_muted=False monitors will have environments unchanged (some, none, or all unmuted)

    This gets us into the correct state for the dual-write implementation where:
    - Monitor is muted if and only if ALL environments are muted
    - Monitor is unmuted if ANY environment is unmuted
    """
    Monitor = apps.get_model("monitors", "Monitor")
    MonitorEnvironment = apps.get_model("monitors", "MonitorEnvironment")

    # Filter is_muted in memory to avoid query timeouts (no composite index on id, is_muted)
    all_monitors = Monitor.objects.all()

    for monitor in RangeQuerySetWrapperWithProgressBar(all_monitors):
        if monitor.is_muted:
            MonitorEnvironment.objects.filter(monitor=monitor).update(is_muted=True)


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("monitors", "0010_delete_orphaned_detectors"),
    ]

    operations = [
        migrations.RunPython(
            backfill_monitor_environment_is_muted,
            migrations.RunPython.noop,
            hints={"tables": ["sentry_monitor", "sentry_monitorenvironment"]},
        ),
    ]
