# Generated by Django 5.2.14 on 2026-06-23 11:53

import django.db.models.deletion
import django.utils.timezone
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
import sentry.uptime.models
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    replaces = [
        ("uptime", "0001_squashed_0042_extra_uptime_indexes"),
        ("uptime", "0043_uptime_django_json_field"),
        ("uptime", "0044_remove_project_uptime_subscription"),
        ("uptime", "0045_backfill_detector_thresholds"),
        ("uptime", "0046_delete_project_uptime_subscription_table"),
        ("uptime", "0047_remove_uptime_status_columns"),
        ("uptime", "0048_delete_uptime_status_columns"),
        ("uptime", "0049_cleanup_failed_safe_deletes"),
        ("uptime", "0050_response_capture"),
        ("uptime", "0051_add_assertion"),
        ("uptime", "0052_add_date_added_index_to_uptimeresponsecapture"),
        ("uptime", "0053_add_response_capture_enabled"),
        ("uptime", "0054_delete_bad_assertions"),
        ("uptime", "0055_backfill_2xx_status_assertion"),
    ]

    initial = True

    checked = False  # This is an initial migration and can take locks

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UptimeSubscription",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_added",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("type", models.TextField()),
                ("status", models.SmallIntegerField(db_default=0, default=0)),
                ("subscription_id", models.TextField(null=True, unique=True)),
                ("url", models.CharField(max_length=255)),
                (
                    "url_domain",
                    models.CharField(db_default="", default="", max_length=255),
                ),
                (
                    "url_domain_suffix",
                    models.CharField(db_default="", default="", max_length=255),
                ),
                (
                    "host_provider_id",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                (
                    "host_provider_name",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                ("interval_seconds", models.IntegerField()),
                ("timeout_ms", models.IntegerField()),
                ("method", models.CharField(db_default="GET", max_length=20)),
                ("headers", models.JSONField(db_default=[])),
                ("body", models.TextField(null=True)),
                (
                    "trace_sampling",
                    models.BooleanField(db_default=False, default=False),
                ),
                (
                    "response_capture_enabled",
                    models.BooleanField(db_default=True, default=True),
                ),
                (
                    "capture_response_on_failure",
                    models.BooleanField(db_default=True, default=True),
                ),
                ("assertion", models.JSONField(null=True)),
            ],
            options={
                "db_table": "uptime_uptimesubscription",
                "indexes": [
                    models.Index(
                        fields=["url_domain_suffix", "url_domain"],
                        name="uptime_upti_url_dom_ead522_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UptimeResponseCapture",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("file_id", sentry.db.models.fields.bounded.BoundedBigIntegerField()),
                (
                    "scheduled_check_time_ms",
                    sentry.db.models.fields.bounded.BoundedBigIntegerField(),
                ),
                (
                    "uptime_subscription",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_captures",
                        to="uptime.uptimesubscription",
                    ),
                ),
            ],
            options={
                "db_table": "uptime_uptimeresponsecapture",
                "indexes": [
                    models.Index(
                        fields=["uptime_subscription", "scheduled_check_time_ms"],
                        name="uptime_upti_uptime__aa1fbe_idx",
                    ),
                    models.Index(fields=["date_added"], name="uptime_upti_date_ad_d591fd_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UptimeSubscriptionRegion",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "region_slug",
                    models.CharField(db_default="", db_index=True, max_length=255),
                ),
                (
                    "mode",
                    models.CharField(
                        db_default=sentry.uptime.models.UptimeSubscriptionRegion.RegionMode[
                            "ACTIVE"
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "uptime_subscription",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="uptime.uptimesubscription",
                    ),
                ),
            ],
            options={
                "db_table": "uptime_uptimesubscriptionregion",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("uptime_subscription"),
                        models.F("region_slug"),
                        name="uptime_uptimesubscription_region_slug_unique",
                    )
                ],
            },
        ),
    ]
