# Generated by Django 5.2.1 on 2025-05-21 16:30

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models

import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
import sentry.db.models.fields.hybrid_cloud_foreign_key
import sentry.db.models.fields.jsonfield
import sentry.uptime.models
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    replaces = [
        ("uptime", "0001_uptime_subscriptions"),
        ("uptime", "0002_remove_separate_remote_subscription"),
        ("uptime", "0003_drop_remote_subscription"),
        ("uptime", "0004_projectuptimesubscription_mode"),
        ("uptime", "0005_uptime_status"),
        ("uptime", "0006_projectuptimesubscription_name_owner"),
        ("uptime", "0007_update_detected_subscription_interval"),
        ("uptime", "0008_uptime_url_suffix"),
        ("uptime", "0009_better_name_for_uptime_rdap_columns"),
        ("uptime", "0010_remove_uptime_whois_columns_state"),
        ("uptime", "0011_remove_uptime_whois_columns_db"),
        ("uptime", "0012_uptime_subscription_request_fields"),
        ("uptime", "0013_uptime_subscription_new_unique"),
        ("uptime", "0014_add_uptime_enviromnet"),
        ("uptime", "0015_headers_deafult_empty_list"),
        ("uptime", "0016_translate_uptime_object_headers_to_lists"),
        ("uptime", "0017_unique_on_timeout"),
        ("uptime", "0018_add_trace_sampling_field_to_uptime"),
        ("uptime", "0019_uptime_region"),
        ("uptime", "0020_drop_region"),
        ("uptime", "0021_drop_region_table_col"),
        ("uptime", "0022_add_trace_sampling_to_uptime_monitors"),
        ("uptime", "0023_translate_uptime_object_headers_to_lists_take_two"),
        ("uptime", "0024_add_status_to_project_uptime_subscription"),
        ("uptime", "0025_uptime_migrate_constraint"),
        ("uptime", "0026_region_mode_col"),
        ("uptime", "0027_remove_migrated_and_unique_constraint"),
        ("uptime", "0028_drop_migrated_column"),
        ("uptime", "0029_uptime_subscription_index_domain_cols"),
        ("uptime", "0030_status_update_date"),
        ("uptime", "0031_translate_uptime_object_headers_to_lists_take_three"),
        ("uptime", "0032_stats_on_subscription"),
        ("uptime", "0033_uptime_backfill_to_detectors"),
        ("uptime", "0034_uptime_backfill_uptime_status"),
        ("uptime", "0035_uptime_backfill_detector_enabled"),
        ("uptime", "0036_uptime_status_indexes"),
        ("uptime", "0037_fix_drift_default_to_db_default"),
        ("uptime", "0038_uptime_drop_project_subscription_uptime_status"),
        ("uptime", "0039_uptime_drop_project_subscription_uptime_status_db"),
        ("uptime", "0040_uptime_backfill_detector_conditions"),
        ("uptime", "0041_uptime_backfill_detector_grouphash"),
        ("uptime", "0042_extra_uptime_indexes"),
    ]

    initial = True

    checked = False  # This is an initial migration and can take locks

    dependencies = [
        ("sentry", "0001_squashed_0904_onboarding_task_project_id_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="UptimeSubscription",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("type", models.TextField()),
                ("status", models.SmallIntegerField(db_default=0, default=0)),
                ("subscription_id", models.TextField(null=True, unique=True)),
                ("url", models.CharField(max_length=255)),
                ("url_domain", models.CharField(db_default="", default="", max_length=255)),
                ("url_domain_suffix", models.CharField(db_default="", default="", max_length=255)),
                ("host_provider_id", models.CharField(db_index=True, max_length=255, null=True)),
                ("host_provider_name", models.CharField(db_index=True, max_length=255, null=True)),
                ("interval_seconds", models.IntegerField()),
                ("timeout_ms", models.IntegerField()),
                ("method", models.CharField(db_default="GET", max_length=20)),
                (
                    "headers",
                    sentry.db.models.fields.jsonfield.JSONField(db_default=[], default=dict),
                ),
                ("body", models.TextField(null=True)),
                ("trace_sampling", models.BooleanField(db_default=False, default=False)),
                ("uptime_status", models.PositiveSmallIntegerField(db_default=1)),
                (
                    "uptime_status_update_date",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
            ],
            options={
                "db_table": "uptime_uptimesubscription",
                "indexes": [
                    models.Index(
                        fields=["url_domain_suffix", "url_domain"],
                        name="uptime_upti_url_dom_ead522_idx",
                    ),
                    models.Index(
                        fields=["uptime_status", "uptime_status_update_date"],
                        name="uptime_upti_uptime__546c70_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectUptimeSubscription",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                (
                    "status",
                    sentry.db.models.fields.bounded.BoundedPositiveBigIntegerField(db_default=0),
                ),
                ("mode", models.SmallIntegerField(db_default=1, default=1)),
                ("name", models.TextField()),
                (
                    "owner_user_id",
                    sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                        "sentry.User", db_index=True, null=True, on_delete="SET_NULL"
                    ),
                ),
                (
                    "environment",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sentry.environment",
                    ),
                ),
                (
                    "owner_team",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="sentry.team"
                    ),
                ),
                (
                    "project",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.project"
                    ),
                ),
                (
                    "uptime_subscription",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="uptime.uptimesubscription"
                    ),
                ),
            ],
            options={
                "db_table": "uptime_projectuptimesubscription",
                "indexes": [
                    models.Index(fields=["project", "mode"], name="uptime_proj_project_30b94a_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("mode", 1)),
                        fields=("project_id", "uptime_subscription"),
                        name="uptime_projectuptimesubscription_unique_manual_project_subscription",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("mode__in", (2, 3))),
                        fields=("project_id", "uptime_subscription"),
                        name="uptime_projectuptimesubscription_unique_auto_project_subscription",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UptimeSubscriptionRegion",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("region_slug", models.CharField(db_default="", db_index=True, max_length=255)),
                (
                    "mode",
                    models.CharField(
                        db_default=sentry.uptime.models.UptimeSubscriptionRegion.RegionMode[
                            "ACTIVE"
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "uptime_subscription",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="uptime.uptimesubscription",
                    ),
                ),
            ],
            options={
                "db_table": "uptime_uptimesubscriptionregion",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("uptime_subscription"),
                        models.F("region_slug"),
                        name="uptime_uptimesubscription_region_slug_unique",
                    )
                ],
            },
        ),
    ]
