# Generated by Django 5.2.1 on 2025-08-06 16:59

from typing import int
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration
from sentry.new_migrations.monkey.special import SafeRunSQL


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("uptime", "0001_squashed_0042_extra_uptime_indexes"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                SafeRunSQL(
                    """
                    ALTER TABLE uptime_uptimesubscription
                        ALTER COLUMN headers DROP DEFAULT,
                        ALTER COLUMN headers TYPE jsonb USING headers::jsonb,
                        ALTER COLUMN headers SET DEFAULT '[]'::jsonb;
                    """,
                    reverse_sql="""
                    ALTER TABLE uptime_uptimesubscription
                        ALTER COLUMN headers DROP DEFAULT,
                        ALTER COLUMN headers TYPE text
                        ALTER COLUMN headers SET DEFAULT '[]';
                    """,
                    hints={"tables": ["uptime_uptimesubscription"]},
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="uptimesubscription",
                    name="headers",
                    field=models.JSONField(db_default=[]),
                ),
            ],
        )
    ]
