BBBB BBBB
BBBB BBBBBBBBBBBBBB

BB BBBBBBBBBBBB
    XXXX gettext('Sites') XXXXX

    XXX XXXXXXXXXXXXXXXXXXXX
        BBB BBBBB BBBBBBBBBBB BB B BB BBBBBBBBBBBB
            XXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFFFXXXXXXX XX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXX
        BBBBBB
    XXXXX
BBBBB
