// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
//
// Generated by StoriesListBuilder (stories-list-builder.ts)
// @generated SignedSource<<95c5deadb54181c9bd4910d1700a30aa>>
//
// This script contains a list of story files to be dynamically loaded by our
// component library.

const FilesList: string[] = ['app/icons/icons.stories.tsx'];

export {FilesList};
