from __future__ import annotations

import logging
from collections import defaultdict
from collections.abc import Sequence
from types import NoneType
from typing import Any

from sentry.issue_detection.detectors.span_first.base import SpanFirstDetector
from sentry.issue_detection.detectors.span_first.slow_db_query_detector import (
    SpanFirstSlowDBQueryDetector,
)
from sentry.issue_detection.performance_detection import get_detection_settings
from sentry.issue_detection.performance_problem import PerformanceProblem, PerformanceProblemDict
from sentry.issue_detection.types import StandaloneSpan
from sentry.issues.grouptype import (
    PerformanceNPlusOneAPICallsGroupType,
    PerformanceNPlusOneGroupType,
)
from sentry.models.project import Project
from sentry.utils import metrics
from sentry.utils.sdk import sdk_logger

logger = logging.getLogger(__name__)

SpanFirstDetectorClass = type[SpanFirstDetector]

# Add new span-first detector types here to include them in the experiment
SPAN_FIRST_DETECTORS: list[SpanFirstDetectorClass] = [
    SpanFirstSlowDBQueryDetector,
]


# Bucket detectors by the slug of the grouptype they produce
SPAN_FIRST_DETECTORS_BY_GROUPTYPE: dict[str, list[SpanFirstDetectorClass]] = {}
for detector_class in SPAN_FIRST_DETECTORS:
    SPAN_FIRST_DETECTORS_BY_GROUPTYPE.setdefault(detector_class.grouptype.slug, []).append(
        detector_class
    )


def run_span_first_detectors(
    grouptypes: Sequence[str],
    segment_span: StandaloneSpan,
    spans: Sequence[StandaloneSpan],
    project: Project,
) -> dict[str, list[PerformanceProblem]]:
    """
    For each of grouptype slugs in `grouptypes`, run the corresponding span-first detectors, and
    return the resulting problems bucketed by slug. Detectors that share a grouptype (e.g. N+1 and
    MN+1, or SQL Injection and Query Injection) accumulate into the same bucket -- so callers should
    sample/gate by grouptype, not by detector class. Detectors that fail are logged and excluded
    from the result.

    The caller is responsible for deciding which grouptypes to evaluate (typically via
    `SpanFirstDetectorsRolloutController.should_check_experiment`). This function does no sampling
    of its own.
    """
    detection_settings = get_detection_settings(project)
    span_first_problems: dict[str, list[PerformanceProblem]] = {}

    for grouptype in grouptypes:
        detector_classes = SPAN_FIRST_DETECTORS_BY_GROUPTYPE.get(grouptype, [])

        for detector_class in detector_classes:
            try:
                detector_settings = detection_settings[detector_class.type]
                problems = run_detector(detector_class, detector_settings, segment_span, spans)
            except Exception:
                logger.exception(
                    "span_first_detectors.detector_run_failed",
                    extra={"detector": detector_class.__name__},
                )
            else:
                span_first_problems.setdefault(grouptype, []).extend(problems)

    return span_first_problems


def run_detector(
    detector_class: type[Any],
    settings: dict[str, Any],
    segment_span: StandaloneSpan,
    segment: Sequence[StandaloneSpan],
) -> list[PerformanceProblem]:
    """
    Span-first analogue of `sentry.issue_detection.performance_detection.run_detector_on_data`.

    Instantiates the detector, walks the given spans through it, and returns the problems it
    produced. Returns an empty list if creation gating disallows it.
    """
    detector = detector_class(settings, segment_span, segment)

    if not detector.is_creation_allowed():
        return []

    for span in segment:
        detector.visit_span(span)
    detector.on_complete()

    return list(detector.stored_problems.values())


def compare_span_first_problems_to_control_data(
    project: Project,
    trace_id: str,
    span_first_problems_by_grouptype: dict[str, list[PerformanceProblem]],
    all_control_problems: Sequence[PerformanceProblem],
) -> None:
    """
    For each grouptype slug present in `span_first_problems_by_grouptype`, compare the problems
    generated by the span-first detectors against the matching subset of existing-detector-generated
    problems, logging mismatches. Emits metrics for comparison skips (if neither set of detectors
    found anything) and comparison results.

    Only compares problems for grouptypes whose span-first detectors ran successfully (i.e., any
    grouptypes whose corresponding span-first detectors a) exist, b) were enabled, and c) didn't
    throw during `run_span_first_detectors`).
    """
    # Bucket control problems by grouptype slug to match the format in which we have the span-first
    # problems
    control_problems_by_grouptype: dict[str, list[PerformanceProblem]] = {}
    for problem in all_control_problems:
        control_problems_by_grouptype.setdefault(problem.type.slug, []).append(problem)

    for grouptype, span_first_problems in span_first_problems_by_grouptype.items():
        control_problems = control_problems_by_grouptype.get(grouptype) or []

        # The vast majority of the time, a given detector isn't going to detect anything, and while
        # it's good to know that the new and legacy detectors agree on not having found anything,
        # those trivial cases can end up overwhelming the more interesting cases. Splitting them off
        # into their own metric lets us continue to track them (at the standard 10% sample rate)
        # while at the same time reducing the hits to the main comparison metric sufficiently that
        # we can afford to ramp its sample rate up to 100%.
        if not control_problems and not span_first_problems:
            metrics.incr(
                "span_first_detectors.empty_result_comparison_skipped", tags={"callsite": grouptype}
            )
            continue  # Skip running the comparison for this grouptype

        control_problem_dicts = [problem.to_dict() for problem in control_problems]
        span_first_problem_dicts = [problem.to_dict() for problem in span_first_problems]

        try:
            shared_fingerprints, non_shared_fingerprints, diffs = _compare_problem_sets(
                control_problem_dicts, span_first_problem_dicts
            )
            differences_found = bool(non_shared_fingerprints or diffs)

            if differences_found:
                _log_mismatch(
                    problem_type=grouptype,
                    control_problems=control_problem_dicts,
                    span_first_problems=span_first_problem_dicts,
                    shared_fingerprints=shared_fingerprints,
                    non_shared_fingerprints=non_shared_fingerprints,
                    diffs=diffs,
                    extra_metadata={
                        "trace_id": trace_id,
                        "project_id": project.id,
                        "project_slug": project.slug,
                        "org_slug": project.organization.slug,
                    },
                )

        except Exception:
            logger.exception("span_first_detectors.comparison_error")

        else:
            metrics.incr(
                "span_first_detectors.compare_results",
                sample_rate=1.0,
                tags={"callsite": grouptype, "exact_match": not differences_found},
            )


def _compare_problem_sets(
    control_problem_dicts: list[PerformanceProblemDict],
    span_first_problem_dicts: list[PerformanceProblemDict],
) -> tuple[set[str], set[str], dict[str, list[str]]]:
    """
    Compare the given problem sets, returning a tuple of the form

        (shared_fingerprints, non_shared_fingerprints, diffs)

    where `diffs` is a mapping of locations where the data differs to the fingerprints of the
    problems which differ there.
    """
    diffs: dict[str, list[str]] = defaultdict(list)

    control_problems_by_fingerprint = {
        problem["fingerprint"]: problem for problem in control_problem_dicts
    }
    span_first_problems_by_fingerprint = {
        problem["fingerprint"]: problem for problem in span_first_problem_dicts
    }

    control_problem_fingerprints = set(control_problems_by_fingerprint)
    span_first_problem_fingerprints = set(span_first_problems_by_fingerprint)
    shared_fingerprints = control_problem_fingerprints.intersection(span_first_problem_fingerprints)
    non_shared_fingerprints = control_problem_fingerprints.symmetric_difference(
        span_first_problem_fingerprints
    )

    for fingerprint in shared_fingerprints:
        control_problem_dict = control_problems_by_fingerprint[fingerprint]
        span_first_problem_dict = span_first_problems_by_fingerprint[fingerprint]

        _collect_single_problem_diffs(control_problem_dict, span_first_problem_dict, diffs)

    return (shared_fingerprints, non_shared_fingerprints, diffs)


def _collect_single_problem_diffs(
    control_problem_dict: PerformanceProblemDict,
    span_first_problem_dict: PerformanceProblemDict,
    # A mapping of locations where data differs to fingerprints of the problems which differ in
    # those locations, to which any differences found will be added
    diffs: dict[str, list[str]],
) -> None:
    fingerprint = control_problem_dict["fingerprint"]

    for key in control_problem_dict:
        control_value: Any = control_problem_dict.get(key)
        span_first_value: Any = span_first_problem_dict.get(key)

        if key in {"op", "desc"} and control_value != span_first_value:
            diffs[key].append(fingerprint)

        elif key in {
            "parent_span_ids",
            "cause_span_ids",
            "offender_span_ids",
        } and not _are_equivalent_lists(control_value, span_first_value):
            diffs[key].append(fingerprint)

        elif key == "evidence_display" and not _are_equivalent_lists(
            # The value under this key is a list of dictionaries. Since under the hood we use sets
            # to do the list comparison, the list values need to be hashable, so convert each dict
            # to a string before running the comparison.
            [f"{c['name']}{c['value']}{c['important']}" for c in control_value],
            [f"{sf['name']}{sf['value']}{sf['important']}" for sf in span_first_value],
        ):
            diffs[key].append(fingerprint)

        elif key == "evidence_data":
            control_evidence_data_dict = control_value
            span_first_evidence_data_dict = span_first_value

            control_evidence_data_keys = set(control_evidence_data_dict)
            span_first_evidence_data_keys = set(span_first_evidence_data_dict)
            shared_evidence_data_keys = control_evidence_data_keys.intersection(
                span_first_evidence_data_keys
            )
            non_shared_evidence_data_keys = control_evidence_data_keys.symmetric_difference(
                span_first_evidence_data_keys
            )

            if non_shared_evidence_data_keys:
                diffs["evidence_data.non_shared_keys"].append(
                    f"{fingerprint}: {', '.join(sorted(non_shared_evidence_data_keys))}"
                )

            for evidence_data_key in shared_evidence_data_keys:
                if evidence_data_key in {
                    "op",
                    "parent_span_ids",
                    "cause_span_ids",
                    "offender_span_ids",
                }:
                    # These values have already been checked at the top level of the problem
                    continue

                control_evidence_data_value = control_evidence_data_dict.get(evidence_data_key)
                span_first_evidence_data_value = span_first_evidence_data_dict.get(
                    evidence_data_key
                )

                if isinstance(control_evidence_data_value, (int, float, str, NoneType)):
                    if control_evidence_data_value != span_first_evidence_data_value:
                        diffs[f"evidence_data.{evidence_data_key}"].append(fingerprint)

                elif isinstance(control_evidence_data_value, list):
                    if evidence_data_key == "span_evidence_key_value":
                        # As with `evidence_display` above, flatten each list of dicts into a list
                        # of strings before running the comparison
                        control_evidence_data_value = [
                            f"{c['key']}{c['value']}{c.get('is_multi_value')}"
                            for c in control_evidence_data_value
                        ]
                        span_first_evidence_data_value = [
                            f"{sf['key']}{sf['value']}{sf.get('is_multi_value')}"
                            for sf in span_first_evidence_data_value
                        ]

                    if not _are_equivalent_lists(
                        control_evidence_data_value, span_first_evidence_data_value
                    ):
                        diffs[f"evidence_data.{evidence_data_key}"].append(fingerprint)


def _are_equivalent_lists(list1: Sequence[Any], list2: Sequence[Any]) -> bool:
    """
    Given two lists, check for equality, ignoring list order.
    """
    return set(list1) == set(list2)


def _strip_unnecessary_problem_data(
    problem_dict: Any,  # Have to type as Any to be able to delete from it
    diffs: dict[str, list[str]],
) -> dict[str, Any]:
    """
    Before passing it to the logger, strip duplicate data out of the given problem dictionary.
    Mutates in place, but also returns the given dictionary for convenience.
    """
    fingerprint = problem_dict["fingerprint"]
    problem_type_id = problem_dict["type"]

    # We log the detector type separately, so no need to include it in every problem dict
    del problem_dict["type"]

    # The data in `evidence_display` is just a rejiggering of data included elsewhere, so unless we
    # have a mismatch there, we can remove it
    if "evidence_display" not in diffs or fingerprint not in diffs["evidence_display"]:
        del problem_dict["evidence_display"]

    evidence_data = problem_dict["evidence_data"]
    # Iterate over a separate copy of the keys so we can delete freely
    for evidence_data_key in set(evidence_data):
        # These values have already been serialized at the top level of the problem
        if evidence_data_key in {"op", "parent_span_ids", "cause_span_ids", "offender_span_ids"}:
            del evidence_data[evidence_data_key]

        # In most cases, `repeating_spans` and `repeating_spans_compact` contain essentially the
        # same data, so we don't need them both. Check if we're dealing with one of the exceptions
        # to that rule, but otherwise, delete the duplicate data unless there's a mismatch.
        elif evidence_data_key == "repeating_spans_compact":
            # In the N+1 API detector the values are totally different, so we want to keep them both
            if problem_type_id == PerformanceNPlusOneAPICallsGroupType.type_id:
                continue
            # The same goes for the N+1 query detector, but here there's a wrinkle: Both the N+1 and
            # MN+1 detectors create problems with the N+1 type, but only for the N+1 detector do we
            # want to keep both values. Fortunately, the N+1 detector uses a string for
            # `repeating_spans` while the MN+1 detector uses a list, so we can typecheck
            # `repeating_spans` to decide which of the two detectors created the current problem.
            if problem_type_id == PerformanceNPlusOneGroupType.type_id and isinstance(
                evidence_data["repeating_spans"],
                str,  # Must be N+1, not MN+1
            ):
                continue

            # For all other detector types, the data is duplicative, so only keep it if we've found
            # a mismatch
            if (
                "evidence_data.repeating_spans_compact" not in diffs
                or fingerprint not in diffs["evidence_data.repeating_spans_compact"]
            ):
                del evidence_data["repeating_spans_compact"]

    return problem_dict


def _log_mismatch(
    *,
    problem_type: str,
    control_problems: list[PerformanceProblemDict],
    span_first_problems: list[PerformanceProblemDict],
    shared_fingerprints: set[str],
    non_shared_fingerprints: set[str],
    # A mapping of locations where data differs to fingerprints of the problems which differ in
    # those locations
    diffs: dict[str, list[str]],
    # Trace, project, and org ids/slugs
    extra_metadata: dict[str, Any],
) -> None:
    # Remove duplicate data from each problem dict to make logs easier to parse
    stripped_control_problems = [
        _strip_unnecessary_problem_data(problem_dict, diffs) for problem_dict in control_problems
    ]
    stripped_span_first_problems = [
        _strip_unnecessary_problem_data(problem_dict, diffs) for problem_dict in span_first_problems
    ]

    data = {
        "problem_type": problem_type,
        "raw_data": {
            "control": (
                stripped_control_problems[0]
                if len(stripped_control_problems) == 1
                else stripped_control_problems
            ),
            "span_first": (
                stripped_span_first_problems[0]
                if len(stripped_span_first_problems) == 1
                else stripped_span_first_problems
            ),
        },
        **extra_metadata,
    }

    # If there are any problems unique to one set or another, record that
    if non_shared_fingerprints:
        data["non_shared_fingerprints"] = ", ".join(sorted(non_shared_fingerprints))

    # If there are any problems that appear in both the control set and the span-first set, record
    # where they differ
    if shared_fingerprints:
        data["diff_keys"] = ", ".join(sorted(diffs.keys()))

    # If either the control or span-first problem sets has multiple problems in it, record which of
    # those problems the mismatches apply to
    if len(control_problems) > 1 or len(span_first_problems) > 1:
        # Make our diff set more compact by stringifying each list of fingerprints
        data["diffs"] = {
            diff_key: ", ".join(sorted(fingerprints)) for diff_key, fingerprints in diffs.items()
        }

    sdk_logger.info(
        "span_first_detectors.problem_mismatch",
        # Record all of our data under a single key so it doesn't get mixed in with all of the
        # random metadata in the log display
        attributes={"data": data},
    )
