import {t} from 'sentry/locale';
import {FieldKind} from 'sentry/utils/fields';
import {DisplayType, WidgetType} from 'sentry/views/dashboards/types';
import {type PrebuiltDashboard} from 'sentry/views/dashboards/utils/prebuiltConfigs';

const TRANSACTION_OP_CONDITION = 'transaction.op:[ui.load,navigation]';

export const MOBILE_VITALS_PREBUILT_CONFIG: PrebuiltDashboard = {
  dateCreated: '',
  title: t('Mobile Vitals as a Dashboard'),
  projects: [],
  widgets: [
    {
      id: 'cold-start-big-number',
      title: 'Avg. Cold App Start',
      description: 'Average cold app start duration',
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '1h',
      thresholds: {
        max_values: {
          max1: 3000,
          max2: 5000,
        },
        unit: null,
      },
      queries: [
        {
          name: '',
          fields: ['avg(measurements.app_start_cold)'],
          aggregates: ['avg(measurements.app_start_cold)'],
          columns: [],
          fieldAliases: [''],
          conditions: TRANSACTION_OP_CONDITION,
          orderby: '',
        },
      ],
      layout: {
        x: 0,
        h: 1,
        y: 0,
        minH: 1,
        w: 3,
      },
    },
    {
      id: 'warm-start-big-number',
      title: 'Avg. Warm App Start',
      description: 'Average warm app start duration',
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '1h',
      thresholds: {
        max_values: {
          max1: 1000,
          max2: 2000,
        },
        unit: null,
      },
      queries: [
        {
          name: '',
          fields: ['avg(measurements.app_start_warm)'],
          aggregates: ['avg(measurements.app_start_warm)'],
          columns: [],
          fieldAliases: [''],
          conditions: TRANSACTION_OP_CONDITION,
          orderby: '',
        },
      ],
      layout: {
        x: 3,
        h: 1,
        y: 0,
        minH: 1,
        w: 3,
      },
    },
    {
      id: 'avg-ttid-big-number',
      title: 'Avg. TTID',
      description: 'Average time to initial display',
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '1h',
      thresholds: null,
      queries: [
        {
          name: '',
          fields: ['avg(measurements.time_to_initial_display)'],
          aggregates: ['avg(measurements.time_to_initial_display)'],
          columns: [],
          fieldAliases: [''],
          conditions: TRANSACTION_OP_CONDITION,
          orderby: '',
        },
      ],
      layout: {
        x: 0,
        h: 1,
        y: 1,
        minH: 1,
        w: 3,
      },
    },
    {
      id: 'avg-ttfd-big-number',
      title: 'Avg. TTFD',
      description: 'Average time to full display',
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '1h',
      thresholds: null,
      queries: [
        {
          name: '',
          fields: ['avg(measurements.time_to_full_display)'],
          aggregates: ['avg(measurements.time_to_full_display)'],
          columns: [],
          fieldAliases: [''],
          conditions: TRANSACTION_OP_CONDITION,
          orderby: '',
        },
      ],
      layout: {
        x: 3,
        h: 1,
        y: 1,
        minH: 1,
        w: 3,
      },
    },
    {
      id: 'avg-frame-delay-big-number',
      title: 'Avg. Frame Delay',
      description: 'Average frame delay',
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '1h',
      thresholds: null,
      queries: [
        {
          name: '',
          fields: ['avg(mobile.frames_delay)'],
          aggregates: ['avg(mobile.frames_delay)'],
          columns: [],
          fieldAliases: [''],
          conditions: TRANSACTION_OP_CONDITION,
          orderby: '',
        },
      ],
      layout: {
        x: 4,
        h: 1,
        y: 2,
        minH: 1,
        w: 2,
      },
    },
    {
      id: 'frozen-frame-rate-big-number',
      title: 'Frozen Frame Rate',
      description: 'The percentage of frames that were frozen',
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '1h',
      thresholds: null,
      queries: [
        {
          name: '',
          fields: [
            'avg(mobile.frozen_frames)',
            'avg(mobile.total_frames)',
            'equation|( avg(mobile.frozen_frames) / avg(mobile.total_frames) )',
          ],
          aggregates: [
            'avg(mobile.frozen_frames)',
            'avg(mobile.total_frames)',
            'equation|( avg(mobile.frozen_frames) / avg(mobile.total_frames) )',
          ],
          columns: [],
          fieldAliases: ['', '', ''],
          conditions: TRANSACTION_OP_CONDITION,
          orderby: '',
        },
      ],
      layout: {
        x: 2,
        h: 1,
        y: 2,
        minH: 1,
        w: 2,
      },
    },
    {
      id: 'slow-frame-rate-big-number',
      title: 'Slow Frame Rate',
      description: 'The percentage of frames that were slow',
      displayType: DisplayType.BIG_NUMBER,
      widgetType: WidgetType.SPANS,
      interval: '1h',
      thresholds: null,
      queries: [
        {
          name: '',
          fields: [
            'avg(mobile.slow_frames)',
            'avg(mobile.total_frames)',
            'equation|( avg(mobile.slow_frames) / avg(mobile.total_frames) )',
          ],
          aggregates: [
            'avg(mobile.slow_frames)',
            'avg(mobile.total_frames)',
            'equation|( avg(mobile.slow_frames) / avg(mobile.total_frames) )',
          ],
          columns: [],
          fieldAliases: ['', '', ''],
          conditions: TRANSACTION_OP_CONDITION,
          orderby: '',
        },
      ],
      layout: {
        x: 0,
        h: 1,
        y: 2,
        minH: 1,
        w: 2,
      },
    },
    {
      id: 'app-start-table',
      title: 'App Start',
      description: '',
      displayType: DisplayType.TABLE,
      widgetType: WidgetType.SPANS,
      interval: '1h',
      thresholds: null,
      queries: [
        {
          name: '',
          fields: [
            'transaction',
            'avg(measurements.app_start_cold)',
            'avg(measurements.app_start_warm)',
            'count(span.duration)',
          ],
          aggregates: [
            'avg(measurements.app_start_cold)',
            'avg(measurements.app_start_warm)',
            'count(span.duration)',
          ],
          columns: ['transaction'],
          fieldAliases: ['Screen', 'Cold Start', 'Warm Start', 'Screen Loads'],
          conditions: '',
          orderby: '-count(span.duration)',
          linkedDashboards: [
            {
              field: 'transaction',
              dashboardId: '-1',
              staticDashboardId: 9,
            },
          ],
        },
      ],
      layout: {
        x: 0,
        h: 3,
        y: 3,
        minH: 2,
        w: 6,
      },
    },
    {
      id: 'screen-rendering-table',
      title: 'Screen Rendering',
      description: '',
      displayType: DisplayType.TABLE,
      widgetType: WidgetType.SPANS,
      interval: '1h',
      thresholds: null,
      queries: [
        {
          name: '',
          fields: [
            'transaction',
            'avg(mobile.slow_frames)',
            'avg(mobile.frozen_frames)',
            'avg(mobile.total_frames)',
            'equation|avg(mobile.slow_frames) / avg(mobile.total_frames)',
            'equation|avg(mobile.frozen_frames) / avg(mobile.total_frames)',
            'avg(tags[frames_delay,number])',
            'count(span.duration)',
          ],
          aggregates: [
            'avg(mobile.slow_frames)',
            'avg(mobile.frozen_frames)',
            'avg(mobile.total_frames)',
            'equation|avg(mobile.slow_frames) / avg(mobile.total_frames)',
            'equation|avg(mobile.frozen_frames) / avg(mobile.total_frames)',
            'avg(tags[frames_delay,number])',
            'count(span.duration)',
          ],
          columns: ['transaction'],
          fieldAliases: [
            'Screen',
            'Slow Frames',
            'Frozen Frames',
            'Total Frames',
            'Slow Frame Rate',
            'Frozen Frame Rate',
            'Frame Delay',
            'Screen Loads',
          ],
          conditions: '',
          orderby: '-count(span.duration)',
          linkedDashboards: [
            {
              field: 'transaction',
              dashboardId: '-1',
              staticDashboardId: 11,
            },
          ],
        },
      ],
      layout: {
        x: 0,
        h: 3,
        y: 9,
        minH: 2,
        w: 6,
      },
    },
    {
      id: 'screen-load-table',
      title: 'Screen Load',
      description: '',
      displayType: DisplayType.TABLE,
      widgetType: WidgetType.SPANS,
      interval: '1h',
      thresholds: null,
      queries: [
        {
          name: '',
          fields: [
            'transaction',
            'avg(measurements.time_to_initial_display)',
            'avg(span.duration)',
            'count(span.duration)',
          ],
          aggregates: [
            'avg(measurements.time_to_initial_display)',
            'avg(span.duration)',
            'count(span.duration)',
          ],
          columns: ['transaction'],
          fieldAliases: ['Screen', 'TTID', 'TTFD', 'Screen Loads'],
          conditions: '',
          orderby: '-count(span.duration)',
          linkedDashboards: [
            {
              field: 'transaction',
              dashboardId: '-1',
              staticDashboardId: 10,
            },
          ],
        },
      ],
      layout: {
        x: 0,
        h: 3,
        y: 6,
        minH: 2,
        w: 6,
      },
    },
  ],
  filters: {
    globalFilter: [
      {
        dataset: WidgetType.SPANS,
        tag: {
          key: 'transaction',
          name: 'transaction',
          kind: FieldKind.TAG,
        },
        value: '',
      },
    ],
  },
};
