import {
  DEFAULT_WIDGET_WIDTH,
  getDefaultWidgetHeight,
} from 'sentry/views/dashboards/layoutUtils';
import type {Widget, WidgetLayout} from 'sentry/views/dashboards/types';

const DEFAULT_LIMIT = 5;

/**
 * This function serves as a fallback to fill out any commonly missing or transform
 * any invalid attributes generated by Seer. For example, although attributes such
 * as limit and minH are specified as required by our schema, Seer does not always
 * generate them in practice. This function as a last step helps mitigate issues
 * where dashboards fail to save due to widgets falling into these scenarios.
 */
export function applySeerWidgetDefaults(widgets: Widget[]): Widget[] {
  return widgets.map(widget => {
    const layout = applyLayoutDefaults(widget.layout, widget.displayType);
    const limit = applyLimitDefaults(widget.limit);

    return {
      ...widget,
      layout,
      limit,
    };
  });
}

function applyLayoutDefaults(
  layout: WidgetLayout | null | undefined,
  displayType: Widget['displayType']
): WidgetLayout {
  const defaultMinH = getDefaultWidgetHeight(displayType);
  if (!layout) {
    return {
      w: DEFAULT_WIDGET_WIDTH,
      h: defaultMinH,
      x: 0,
      y: 0,
      minH: defaultMinH,
    };
  }
  return {
    ...layout,
    minH: layout.minH ?? defaultMinH,
  };
}

function applyLimitDefaults(limit: number | null | undefined): number {
  if (limit === null || limit === undefined) {
    return DEFAULT_LIMIT;
  }
  return limit;
}
