# Generated by Django 5.2.16 on 2026-09-02 16:53

from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("hybridcloud", "0034_drop_webhookpayload_priority_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellcacheversion",
            name="keyname",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="controlcacheversion",
            name="keyname",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
