# Generated by Django 5.2.1 on 2025-05-21 16:29

import django.db.models.constraints
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
import sentry.db.models.fields.hybrid_cloud_foreign_key
import sentry.db.models.fields.jsonfield
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    replaces = [
        ("explore", "0001_add_explore_saved_query_model"),
        ("explore", "0002_add_starred_explore_query_model"),
        ("explore", "0003_add_prebuilt_column_to_explore_saved_queries"),
        ("explore", "0004_add_explore_last_visited_table"),
    ]

    initial = True

    checked = False  # This is an initial migration and can take locks

    dependencies = [
        ("sentry", "0001_squashed_0904_onboarding_task_project_id_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExploreSavedQuery",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_id",
                    sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                        "sentry.User", db_index=True, null=True, on_delete="SET_NULL"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("query", sentry.db.models.fields.jsonfield.JSONField(default=dict)),
                (
                    "visits",
                    sentry.db.models.fields.bounded.BoundedBigIntegerField(default=1, null=True),
                ),
                (
                    "last_visited",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("dataset", sentry.db.models.fields.bounded.BoundedPositiveIntegerField(default=0)),
                ("is_multi_query", models.BooleanField(default=False)),
                (
                    "prebuilt_id",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(
                        db_default=None, null=True
                    ),
                ),
                (
                    "prebuilt_version",
                    sentry.db.models.fields.bounded.BoundedPositiveIntegerField(
                        db_default=None, null=True
                    ),
                ),
                (
                    "organization",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.organization"
                    ),
                ),
            ],
            options={
                "db_table": "explore_exploresavedquery",
            },
        ),
        migrations.CreateModel(
            name="ExploreSavedQueryProject",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "explore_saved_query",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="explore.exploresavedquery"
                    ),
                ),
                (
                    "project",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.project"
                    ),
                ),
            ],
            options={
                "db_table": "explore_exploresavedqueryproject",
                "unique_together": {("project", "explore_saved_query")},
            },
        ),
        migrations.AddField(
            model_name="exploresavedquery",
            name="projects",
            field=models.ManyToManyField(
                through="explore.ExploreSavedQueryProject", to="sentry.project"
            ),
        ),
        migrations.CreateModel(
            name="ExploreSavedQueryLastVisited",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                        "sentry.User", db_index=True, on_delete="CASCADE"
                    ),
                ),
                ("last_visited", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "explore_saved_query",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="explore.exploresavedquery"
                    ),
                ),
                (
                    "organization",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.organization"
                    ),
                ),
            ],
            options={
                "db_table": "explore_exploresavedquerylastvisited",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "organization_id", "explore_saved_query_id"),
                        name="explore_exploresavedquerylastvisited_unique_last_visited_per_org_user_query",
                    )
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="exploresavedquery",
            unique_together={("organization", "prebuilt_id")},
        ),
        migrations.CreateModel(
            name="ExploreSavedQueryStarred",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    sentry.db.models.fields.hybrid_cloud_foreign_key.HybridCloudForeignKey(
                        "sentry.User", db_index=True, on_delete="CASCADE"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(db_default=None, null=True)),
                ("starred", models.BooleanField(db_default=True)),
                (
                    "explore_saved_query",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="explore.exploresavedquery"
                    ),
                ),
                (
                    "organization",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sentry.organization"
                    ),
                ),
            ],
            options={
                "db_table": "explore_exploresavedquerystarred",
                "constraints": [
                    models.UniqueConstraint(
                        deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                        fields=("user_id", "organization_id", "position"),
                        name="explore_exploresavedquerystarred_unique_query_position_per_org_user",
                    )
                ],
            },
        ),
    ]
