# Generated by Django 5.2.14 on 2026-07-27 20:25

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
import logging
import re
from re import Match

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.query import RangeQuerySetWrapperWithProgressBar


logger = logging.getLogger(__name__)

ALIAS_REGEX = r"(\w+)?(?!\d+)\w+"
FUNCTION_PATTERN = re.compile(
    rf"^(?P<function>[^\(]+)\((?P<columns>.*)\)( (as|AS) (?P<alias>{ALIAS_REGEX}))?$"
)
OPERATOR_MAP = {
    "equals": ":",
    "notEquals": ":",
    "greater": ":>",
    "less": ":>",
    "greaterOrEquals": ":>=",
    "lessOrEquals": ":<=",
}


def _lookback(columns: str, j: int, string: str) -> bool:
    """For parse_arguments, check that the current character is preceeded by string"""
    if j < len(string):
        return False
    return columns[j - len(string) : j] == string


def parse_arguments(_function: str, columns: str) -> list[str]:
    """
    Some functions take a quoted string for their arguments that may contain commas,
    which requires special handling.
    This function attempts to be identical with the similarly named parse_arguments
    found in static/app/utils/discover/fields.tsx
    """
    args = []

    quoted = False
    in_tag = False
    escaped = False
    in_filter = False

    i, j = 0, 0

    while j < len(columns):
        if not in_filter and not in_tag and i == j and columns[j] == '"':
            # when we see a quote at the beginning of
            # an argument, then this is a quoted string
            quoted = True
        elif not in_filter and not quoted and columns[j] == "[" and _lookback(columns, j, "tags"):
            # when the argument begins with tags[,
            # then this is the beginning of the tag that may contain commas
            in_tag = True
        elif not quoted and i == j and columns[j] == "`":
            # When the argument starts with `
            # then its a filter that may contain any number of characters
            in_filter = True
        elif i == j and columns[j] == " ":
            # argument has leading spaces, skip over them
            i += 1
        elif quoted and not escaped and columns[j] == "\\":
            # when we see a slash inside a quoted string,
            # the next character is an escape character
            escaped = True
        elif quoted and not escaped and columns[j] == '"':
            # when we see a non-escaped quote while inside
            # of a quoted string, we should end it
            quoted = False
        elif in_tag and not escaped and columns[j] == "]":
            # when we see a non-escaped quote while inside
            # of a quoted string, we should end it
            in_tag = False
        elif in_filter and columns[j] == "`":
            # When we see a ` while we're in a filter end it
            in_filter = False
        elif quoted and escaped:
            # when we are inside a quoted string and have
            # begun an escape character, we should end it
            escaped = False
        elif (quoted or in_tag) and columns[j] == ",":
            # when we are inside a quoted string or tag and see
            # a comma, it should not be considered an
            # argument separator
            pass
        elif not in_filter and columns[j] == ",":
            # when we see a comma outside of a quoted string
            # it is an argument separator
            args.append(columns[i:j].strip())
            i = j + 1
        j += 1

    if i != j:
        # add in the last argument if any
        args.append(columns[i:].strip())

    return [arg for arg in args if arg]


def is_function(field: str) -> Match[str] | None:
    return FUNCTION_PATTERN.search(field)


def update_if_combinators(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    ExploreSavedQuery = apps.get_model("explore", "ExploreSavedQuery")

    for saved_query in RangeQuerySetWrapperWithProgressBar(
        ExploreSavedQuery.objects.filter(query__query__icontains="_if", dataset__in={0, 101})
    ):
        try:
            queries = saved_query.query["query"]
            changed = False
            for query in queries:
                # We only cache per query cause the results can change query to query
                for field in query["aggregateField"]:
                    for index, axis in enumerate(field["yAxes"]):
                        if "_if" in axis:
                            match = is_function(axis)
                            if match:
                                function_name = match.group("function")
                                columns = match.group("columns")
                                arguments = parse_arguments(function_name, columns)
                                column, operator, value = arguments
                                field["yAxes"][index] = (
                                    f"{function_name}(`{'!' if operator == 'notEquals' else ''}{column}{OPERATOR_MAP[operator]}{value}`)"
                                )
                                changed = True
            if changed:
                saved_query.save()
        except Exception as error:
            logger.exception(
                "Error updating a query",
                extra={
                    "saved_query": saved_query.id,
                    "error": error,
                },
            )


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("sentry", "1146_add_gcp_service_account"),
        ("explore", "0010_remove_last_received_from_attribute_context"),
    ]

    operations = [
        migrations.RunPython(
            reverse_code=migrations.RunPython.noop,
            code=update_if_combinators,
            hints={"tables": ["explore_saved_query"]},
        ),
    ]
