# Generated by Django 5.2.15 on 2026-08-25 18:14

import django.db.models.deletion
import sentry.db.models.fields.foreignkey
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration
from sentry.new_migrations.monkey.fields import SafeRemoveField
from sentry.new_migrations.monkey.state import DeletionAction


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("explore", "0011_delete_last_received_from_attribute_context"),
        ("sentry", "1154_pullrequest_external_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="traceitemattributevaluecontext",
            name="explore_traceitemvalue_unique_project_scoped",
        ),
        migrations.RemoveConstraint(
            model_name="traceitemattributevaluecontext",
            name="explore_traceitemvalue_unique_org_scoped",
        ),
        migrations.AlterField(
            model_name="traceitemattributevaluecontext",
            name="project",
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sentry.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="traceitemattributevaluecontext",
            constraint=models.UniqueConstraint(
                fields=(
                    "organization",
                    "item_type",
                    "attribute_name",
                    "attribute_value",
                    "attribute_type",
                ),
                name="explore_traceitemvalue_unique_org_scoped",
            ),
        ),
        SafeRemoveField(
            model_name="traceitemattributevaluecontext",
            name="project",
            deletion_action=DeletionAction.MOVE_TO_PENDING,
        ),
    ]
