// Bypass the react-router alias so V6's DOM declarations can re-export the
// original core types without resolving back to themselves.
export * from 'react-router/dist/index.js';
// Explicit DOM-only exports avoid re-importing the aliased core declarations.
export {
  BrowserRouter,
  Form,
  HashRouter,
  Link,
  NavLink,
  ScrollRestoration,
  UNSAFE_ErrorResponseImpl,
  UNSAFE_FetchersContext,
  UNSAFE_ViewTransitionContext,
  UNSAFE_useScrollRestoration,
  createBrowserRouter,
  createHashRouter,
  createSearchParams,
  unstable_HistoryRouter,
  unstable_usePrompt,
  useBeforeUnload,
  useFetcher,
  useFetchers,
  useFormAction,
  useLinkClickHandler,
  useSearchParams,
  useSubmit,
  useViewTransitionState,
  type BrowserRouterProps,
  type FetcherFormProps,
  type FetcherSubmitFunction,
  type FetcherWithComponents,
  type FormEncType,
  type FormMethod,
  type FormProps,
  type GetScrollRestorationKeyFunction,
  type HashRouterProps,
  type HistoryRouterProps,
  type LinkProps,
  type NavLinkProps,
  type NavLinkRenderProps,
  type ParamKeyValuePair,
  type ScrollRestorationProps,
  type SetURLSearchParams,
  type SubmitFunction,
  type SubmitOptions,
  type URLSearchParamsInit,
  type V7_FormMethod,
} from 'react-router-dom';
export {
  createMemoryHistory as UNSAFE_createMemoryHistory,
  createRouter as UNSAFE_createRouter,
  type Router as DataRouter,
  type InitialEntry,
  type RouterNavigateOptions,
} from '@remix-run/router';
