from drf_spectacular.utils import OpenApiExample

CREATE_NOTIFICATION_ACTION = [
    OpenApiExample(
        "Create a new email spike protection notification action for the project, The Spoiled Yoghurt",
        value={
            "id": "836501735",
            "organizationId": "62848264",
            "serviceType": "sentry_notification",
            "targetDisplay": "default",
            "targeyIdentifier": "default",
            "targetType": "specific",
            "triggerType": "spike-protection",
            "projects": [
                {
                    "id": "4505321021243392",
                    "slug": "the-spoiled-yoghurt",
                    "name": "The Spoiled Yoghurt",
                    "platform": "python",
                    "dateCreated": "2023-06-08T00:13:06.004534Z",
                    "isBookmarked": False,
                    "isMember": True,
                    "features": [
                        "alert-filters",
                        "custom-inbound-filters",
                        "data-forwarding",
                        "discard-groups",
                        "minidump",
                        "race-free-group-creation",
                        "rate-limits",
                        "servicehooks",
                        "similarity-indexing",
                        "similarity-indexing-v2",
                        "similarity-view",
                        "similarity-view-v2",
                    ],
                    "firstEvent": None,
                    "firstTransactionEvent": False,
                    "access": [
                        "member:read",
                        "event:read",
                        "project:admin",
                        "team:write",
                        "project:write",
                        "team:admin",
                        "project:read",
                        "org:integrations",
                        "org:read",
                        "project:releases",
                        "team:read",
                        "alerts:write",
                        "event:admin",
                        "event:write",
                        "alerts:read",
                    ],
                    "hasAccess": True,
                    "hasMinifiedStackTrace": False,
                    "hasMonitors": False,
                    "hasProfiles": False,
                    "hasReplays": False,
                    "hasSessions": False,
                    "isInternal": False,
                    "isPublic": False,
                    "avatar": {"avatarType": "letter_avatar", "avatarUuid": None},
                    "color": "#3f70bf",
                    "status": "active",
                }
            ],
        },
        status_codes=["201"],
        response_only=True,
    )
]

LIST_NOTIFICATION_ACTIONS = [
    OpenApiExample(
        "List all spike protection notification actions for an organization",
        value=[
            {
                "id": "836501735",
                "organizationId": "62848264",
                "serviceType": "sentry_notification",
                "targetDisplay": "default",
                "targeyIdentifier": "default",
                "targetType": "specific",
                "triggerType": "spike-protection",
                "projects": [
                    {
                        "id": "4505321021243392",
                        "slug": "the-spoiled-yoghurt",
                        "name": "The Spoiled Yoghurt",
                        "platform": "python",
                        "dateCreated": "2023-06-08T00:13:06.004534Z",
                        "isBookmarked": False,
                        "isMember": True,
                        "features": [
                            "alert-filters",
                            "custom-inbound-filters",
                            "data-forwarding",
                            "discard-groups",
                            "minidump",
                            "race-free-group-creation",
                            "rate-limits",
                            "servicehooks",
                            "similarity-indexing",
                            "similarity-indexing-v2",
                            "similarity-view",
                            "similarity-view-v2",
                        ],
                        "firstEvent": None,
                        "firstTransactionEvent": False,
                        "access": [
                            "member:read",
                            "event:read",
                            "project:admin",
                            "team:write",
                            "project:write",
                            "team:admin",
                            "project:read",
                            "org:integrations",
                            "org:read",
                            "project:releases",
                            "team:read",
                            "alerts:write",
                            "event:admin",
                            "event:write",
                            "alerts:read",
                        ],
                        "hasAccess": True,
                        "hasMinifiedStackTrace": False,
                        "hasMonitors": False,
                        "hasProfiles": False,
                        "hasReplays": False,
                        "hasSessions": False,
                        "isInternal": False,
                        "isPublic": False,
                        "avatar": {"avatarType": "letter_avatar", "avatarUuid": None},
                        "color": "#3f70bf",
                        "status": "active",
                    }
                ],
            },
            {
                "id": "73847650",
                "organizationId": "62848264",
                "serviceType": "sentry_notification",
                "targetDisplay": "default",
                "targeyIdentifier": "default",
                "targetType": "specific",
                "triggerType": "spike-protection",
                "projects": [
                    {
                        "id": "2234153",
                        "slug": "the-spoiled-egg",
                        "name": "The Spoiled Egg",
                        "platform": "",
                        "dateCreated": "2023-06-02T17:50:20.304762Z",
                        "isBookmarked": False,
                        "isMember": False,
                        "features": [
                            "alert-filters",
                            "custom-inbound-filters",
                            "data-forwarding",
                            "discard-groups",
                            "minidump",
                            "race-free-group-creation",
                            "rate-limits",
                            "servicehooks",
                            "similarity-indexing",
                            "similarity-indexing-v2",
                            "similarity-view",
                            "similarity-view-v2",
                        ],
                        "firstEvent": "2023-07-03T18:10:56.197351Z",
                        "firstTransactionEvent": False,
                        "access": [
                            "alerts:read",
                            "event:write",
                            "org:read",
                            "project:read",
                            "member:read",
                            "team:read",
                            "event:read",
                            "project:releases",
                        ],
                        "hasAccess": True,
                        "hasMinifiedStackTrace": False,
                        "hasMonitors": True,
                        "hasProfiles": False,
                        "hasReplays": False,
                        "hasSessions": False,
                        "isInternal": False,
                        "isPublic": False,
                        "avatar": {"avatarType": "letter_avatar", "avatarUuid": None},
                        "color": "#6e3fbf",
                        "status": "active",
                    },
                ],
            },
        ],
        status_codes=["201"],
        response_only=True,
    )
]
