from drf_spectacular.utils import OpenApiExample

key_with_rate_limiting = {
    "id": "60120449b6b1d5e45f75561e6dabd80b",
    "name": "Liked Pegasus",
    "label": "Liked Pegasus",
    "public": "60120449b6b1d5e45f75561e6dabd80b",
    "secret": "189485c3b8ccf582bf5e12c530ef8858",
    "projectId": 4505281256090153,
    "isActive": True,
    "rateLimit": {"window": 7200, "count": 1000},
    "dsn": {
        "secret": "https://a785682ddda742d7a8a4088810e67701:bcd99b3790b3441c85ce4b1eaa854f66@o4504765715316736.ingest.sentry.io/4505281256090153",
        "public": "https://a785682ddda742d7a8a4088810e67791@o4504765715316736.ingest.sentry.io/4505281256090153",
        "csp": "https://o4504765715316736.ingest.sentry.io/api/4505281256090153/csp-report/?sentry_key=a785682ddda719b7a8a4011110d75598",
        "security": "https://o4504765715316736.ingest.sentry.io/api/4505281256090153/security/?sentry_key=a785682ddda719b7a8a4011110d75598",
        "minidump": "https://o4504765715316736.ingest.sentry.io/api/4505281256090153/minidump/?sentry_key=a785682ddda719b7a8a4011110d75598",
        "unreal": "https://o4504765715316736.ingest.sentry.io/api/4505281256090153/unreal/a785682ddda719b7a8a4011110d75598/",
        "cdn": "https://js.sentry-cdn.com/a785682ddda719b7a8a4011110d75598.min.js",
    },
    "browserSdkVersion": "7.x",
    "browserSdk": {"choices": [["latest", "latest"], ["7.x", "7.x"]]},
    "dateCreated": "2023-06-21T19:50:26.036254Z",
    "dynamicSdkLoaderOptions": {
        "hasReplay": True,
        "hasPerformance": True,
        "hasDebug": True,
    },
}

key_wo_rate_limiting = {
    "id": "da8d69cb17e80677b76e08fde4656b93",
    "name": "Bold Oarfish",
    "label": "Bold Oarfish",
    "public": "da8d69cb17e80677b76e08fde4656b93",
    "secret": "5c241ebc42ccfbec281cbefbedc7ab96",
    "projectId": 4505281256090153,
    "isActive": True,
    "rateLimit": None,
    "dsn": {
        "secret": "https://a785682ddda742d7a8a4088810e67701:bcd99b3790b3441c85ce4b1eaa854f66@o4504765715316736.ingest.sentry.io/4505281256090153",
        "public": "https://a785682ddda742d7a8a4088810e67791@o4504765715316736.ingest.sentry.io/4505281256090153",
        "csp": "https://o4504765715316736.ingest.sentry.io/api/4505281256090153/csp-report/?sentry_key=a785682ddda719b7a8a4011110d75598",
        "security": "https://o4504765715316736.ingest.sentry.io/api/4505281256090153/security/?sentry_key=a785682ddda719b7a8a4011110d75598",
        "minidump": "https://o4504765715316736.ingest.sentry.io/api/4505281256090153/minidump/?sentry_key=a785682ddda719b7a8a4011110d75598",
        "unreal": "https://o4504765715316736.ingest.sentry.io/api/4505281256090153/unreal/a785682ddda719b7a8a4011110d75598/",
        "cdn": "https://js.sentry-cdn.com/a785682ddda719b7a8a4011110d75598.min.js",
    },
    "browserSdkVersion": "7.x",
    "browserSdk": {"choices": [["latest", "latest"], ["7.x", "7.x"]]},
    "dateCreated": "2023-06-21T18:17:52.707298Z",
    "dynamicSdkLoaderOptions": {
        "hasReplay": True,
        "hasPerformance": True,
        "hasDebug": False,
    },
}

project = {
    "id": "4505321021243392",
    "slug": "the-spoiled-yoghurt",
    "name": "The Spoiled Yoghurt",
    "platform": "python",
    "dateCreated": "2023-06-08T00:13:06.004534Z",
    "isBookmarked": False,
    "isMember": True,
    "features": [
        "alert-filters",
        "custom-inbound-filters",
        "data-forwarding",
        "discard-groups",
        "minidump",
        "race-free-group-creation",
        "rate-limits",
        "servicehooks",
        "similarity-indexing",
        "similarity-indexing-v2",
        "similarity-view",
        "similarity-view-v2",
    ],
    "firstEvent": None,
    "firstTransactionEvent": False,
    "access": [
        "member:read",
        "event:read",
        "project:admin",
        "team:write",
        "project:write",
        "team:admin",
        "project:read",
        "org:integrations",
        "org:read",
        "project:releases",
        "team:read",
        "alerts:write",
        "event:admin",
        "event:write",
        "alerts:read",
    ],
    "hasAccess": True,
    "hasMinifiedStackTrace": False,
    "hasMonitors": False,
    "hasProfiles": False,
    "hasReplays": False,
    "hasSessions": False,
    "isInternal": False,
    "isPublic": False,
    "avatar": {"avatarType": "letter_avatar", "avatarUuid": None},
    "color": "#3f70bf",
    "status": "active",
}

detailed_project = {
    "id": "4505281231978496",
    "slug": "earth",
    "name": "earth",
    "platform": "python",
    "dateCreated": "2023-05-31T23:34:10.251291Z",
    "isBookmarked": False,
    "isMember": True,
    "features": [
        "alert-filters",
        "custom-inbound-filters",
        "discard-groups",
        "minidump",
        "race-free-group-creation",
        "similarity-indexing",
        "similarity-view",
    ],
    "firstEvent": None,
    "firstTransactionEvent": False,
    "access": [
        "project:releases",
        "event:admin",
        "member:read",
        "project:admin",
        "event:read",
        "team:read",
        "alerts:write",
        "team:write",
        "project:read",
        "org:integrations",
        "team:admin",
        "project:write",
        "alerts:read",
        "org:read",
        "event:write",
    ],
    "hasAccess": True,
    "hasMinifiedStackTrace": False,
    "hasMonitors": False,
    "hasProfiles": False,
    "hasReplays": False,
    "hasSessions": False,
    "isInternal": False,
    "isPublic": False,
    "avatar": {"avatarType": "letter_avatar", "avatarUuid": None},
    "color": "#643fbf",
    "status": "active",
    "team": {"id": "4505285620989952", "slug": "cool-team", "name": "test"},
    "teams": [{"id": "4505285620989952", "slug": "cool-team", "name": "test"}],
    "latestRelease": None,
    "options": {
        "sentry:symbol_sources": '[{"secret_key":"asdf","id":"60a033a8-dbf2-4b93-bb1a-daaa9acfb73a","layout":{"type":"native","casing":"default"},"name":"asdf","bucket":"asdf","region":"us-east-1","access_key":"asdf","type":"s3"},{"private_key":"asdf","id":"b6ae6d66-67fe-4b1d-96c8-c8de9b3766be","layout":{"type":"native","casing":"default"},"name":"asdf","bucket":"asdf","client_email":"asdf@me.com","type":"gcs"},{"id":"15f4fcb4-6516-4880-bb71-a021fcc1a86c","name":"asdf","url":"asdf.com","layout":{"type":"native","casing":"default"},"type":"http"}]',
        "sentry:builtin_symbol_sources": [
            "ios",
            "microsoft",
            "nuget",
            "autodesk",
            "amd",
            "citrix",
            "intel",
            "chromium",
            "electron",
            "nvidia",
            "ubuntu",
            "mozilla",
            "android",
            "unity",
        ],
        "sentry:error_messages": ["TypeError", "integer division"],
        "sentry:releases": ["[!3]", "4"],
        "sentry:blacklisted_ips": ["127.0.0.1", "324098"],
        "filters:react-hydration-errors": False,
        "sentry:token": "9407f95000a711eea549a2ed703ef156",
        "quotas:spike-protection-disabled": False,
        "sentry:option-epoch": 11,
        "sentry:csp_ignored_sources_defaults": True,
        "sentry:csp_ignored_sources": "",
        "sentry:reprocessing_active": False,
        "filters:blacklisted_ips": "127.0.0.1\n324098",
        "filters:releases": "[!3]\n4",
        "filters:error_messages": "TypeError\ninteger division",
        "feedback:branding": True,
    },
    "digestsMinDelay": 300,
    "digestsMaxDelay": 1800,
    "subjectPrefix": "",
    "allowedDomains": ["*"],
    "resolveAge": 0,
    "dataScrubber": True,
    "dataScrubberDefaults": True,
    "safeFields": [],
    "storeCrashReports": None,
    "sensitiveFields": [],
    "subjectTemplate": "$shortID - $title",
    "securityToken": "9407f95000a711eea549a2ed703ef156",
    "securityTokenHeader": None,
    "verifySSL": False,
    "scrubIPAddresses": False,
    "scrapeJavaScript": True,
    "groupingConfig": "newstyle:2023-01-11",
    "groupingEnhancements": "",
    "groupingEnhancementsBase": None,
    "secondaryGroupingExpiry": 0,
    "secondaryGroupingConfig": None,
    "groupingAutoUpdate": True,
    "fingerprintingRules": "",
    "organization": {
        "id": "4504765715316736",
        "slug": "seijis-test-organization",
        "status": {"id": "active", "name": "active"},
        "name": "Seiji's Test Organization",
        "dateCreated": "2023-03-01T22:31:30.744571Z",
        "isEarlyAdopter": False,
        "require2FA": False,
        "requireEmailVerification": False,
        "avatar": {"avatarType": "letter_avatar", "avatarUuid": None},
        "features": [
            "performance-large-http-payload-detector",
            "performance-n-plus-one-db-queries-post-process-group",
            "profile-json-decode-main-thread-visible",
            "issue-list-prefetch-issue-on-hover",
            "business-to-team-promotion",
            "transaction-name-normalize",
            "integrations-deployment",
            "performance-render-blocking-asset-span-visible",
            "performance-file-io-main-thread-detector",
            "india-promotion",
            "performance-new-widget-designs",
            "performance-mep-bannerless-ui",
            "invite-members-rate-limits",
            "mep-rollout-flag",
            "performance-db-main-thread-detector",
            "bundle-plan-checkout",
            "performance-issues-m-n-plus-one-db-detector",
            "getting-started-doc-with-product-selection",
            "performance-consecutive-http-detector",
            "performance-slow-db-query-ingest",
            "performance-issues-all-events-tab",
            "performance-render-blocking-asset-span-post-process-group",
            "open-membership",
            "session-replay-errors-tab",
            "paid-to-free-promotion",
            "performance-transaction-name-only-search-indexed",
            "release-health-drop-sessions",
            "performance-view",
            "performance-consecutive-http-post-process-group",
            "transaction-name-normalize-legacy",
            "performance-issues-compressed-assets-detector",
            "session-replay-ui",
            "profile-file-io-main-thread-visible",
            "performance-n-plus-one-db-queries-ingest",
            "shared-issues",
            "performance-n-plus-one-api-calls-detector",
            "performance-consecutive-http-visible",
            "profile-image-decode-main-thread-post-process-group",
            "performance-m-n-plus-one-db-queries-post-process-group",
            "set-grouping-config",
            "performance-n-plus-one-api-calls-visible",
            "profile-file-io-main-thread-ingest",
            "dashboards-rh-widget",
            "auto-enable-codecov",
            "new-spike-protection",
            "transaction-metrics-extraction",
            "performance-m-n-plus-one-db-queries-visible",
            "performance-render-blocking-asset-span-ingest",
            "profiling-ga",
            "promotion-be-adoption-enabled",
            "crons-issue-platform",
            "profiling-billing",
            "performance-consecutive-db-queries-post-process-group",
            "issue-alert-fallback-targeting",
            "performance-issues-render-blocking-assets-detector",
            "performance-file-io-main-thread-post-process-group",
            "onboarding-sdk-selection",
            "device-classification",
            "performance-large-http-payload-ingest",
            "profile-json-decode-main-thread-post-process-group",
            "performance-onboarding-checklist",
            "anr-rate",
            "issue-platform",
            "performance-uncompressed-assets-ingest",
            "performance-slow-db-issue",
            "org-subdomains",
            "performance-db-main-thread-visible",
            "performance-span-histogram-view",
            "profile-file-io-main-thread-post-process-group",
            "performance-slow-db-query-post-process-group",
            "performance-slow-db-query-visible",
            "performance-consecutive-db-queries-visible",
            "profiling",
            "profile-image-decode-main-thread-visible",
            "performance-db-main-thread-post-process-group",
            "sql-format",
            "performance-metrics-backed-transaction-summary",
            "performance-uncompressed-assets-post-process-group",
            "profile-json-decode-main-thread-ingest",
            "metric-alert-chartcuterie",
            "performance-consecutive-db-queries-ingest",
            "streamline-targeting-context",
            "team-project-creation-all",
            "minute-resolution-sessions",
            "session-replay",
            "performance-uncompressed-assets-visible",
            "am2-billing",
            "performance-n-plus-one-db-queries-visible",
            "performance-n-plus-one-api-calls-post-process-group",
            "mobile-cpu-memory-in-transactions",
            "performance-issues-search",
            "symbol-sources",
            "onboarding",
            "sentry-pride-logo-footer",
            "session-replay-recording-scrubbing",
            "customer-domains",
            "transaction-name-mark-scrubbed-as-sanitized",
            "session-replay-sdk-errors-only",
            "monitors",
            "slack-overage-notifications",
            "performance-large-http-payload-post-process-group",
            "performance-large-http-payload-visible",
            "ondemand-budgets",
            "onboarding-project-deletion-on-back-click",
            "performance-n-plus-one-api-calls-ingest",
            "ds-sliding-window-org",
            "crons-timeline-listing-page",
            "advanced-search",
            "performance-consecutive-http-ingest",
            "discover-events-rate-limit",
            "project-stats",
            "performance-landing-page-stats-period",
            "integrations-stacktrace-link",
            "performance-m-n-plus-one-db-queries-ingest",
            "track-button-click-events",
            "performance-file-io-main-thread-visible",
            "event-attachments",
            "source-maps-debug-ids",
            "performance-file-io-main-thread-ingest",
            "dynamic-sampling",
            "alert-crash-free-metrics",
            "performance-db-main-thread-ingest",
            "device-class-synthesis",
            "open-ai-suggestion",
            "session-replay-index-subquery",
            "metrics-extraction",
            "performance-consecutive-db-issue",
            "promotion-mobperf-discount20",
            "performance-new-trends",
            "derive-code-mappings",
            "profile-image-decode-main-thread-ingest",
            "promotion-mobperf-gift50kerr",
        ],
        "links": {
            "organizationUrl": "https://seijis-test-organization.sentry.io",
            "regionUrl": "https://us.sentry.io",
        },
        "hasAuthProvider": False,
    },
    "plugins": [
        {
            "id": "asana",
            "name": "Asana",
            "slug": "asana",
            "shortName": "Asana",
            "type": "issue-tracking",
            "canDisable": True,
            "isTestable": False,
            "hasConfiguration": True,
            "metadata": {},
            "contexts": [],
            "status": "unknown",
            "assets": [],
            "doc": "",
            "firstPartyAlternative": None,
            "deprecationDate": None,
            "altIsSentryApp": None,
            "enabled": False,
            "version": "23.7.0.dev0",
            "author": {"name": "Sentry Team", "url": "https://github.com/getsentry/sentry"},
            "isDeprecated": False,
            "isHidden": False,
            "description": "\nImprove your productivity by creating tasks in Asana directly\nfrom Sentry issues. This integration also allows you to link Sentry\nissues to existing tasks in Asana.\n",
            "features": ["issue-basic"],
            "featureDescriptions": [
                {
                    "description": "Create and link Sentry issue groups directly to an Asana ticket in any of your\n            projects, providing a quick way to jump from a Sentry bug to tracked ticket!",
                    "featureGate": "issue-basic",
                },
                {
                    "description": "Link Sentry issues to existing Asana tickets.",
                    "featureGate": "issue-basic",
                },
            ],
            "resourceLinks": [
                {"title": "Report Issue", "url": "https://github.com/getsentry/sentry/issues"},
                {
                    "title": "View Source",
                    "url": "https://github.com/getsentry/sentry/tree/master/src/sentry_plugins",
                },
            ],
        },
    ],
    "platforms": [],
    "processingIssues": 0,
    "defaultEnvironment": None,
    "relayPiiConfig": None,
    "builtinSymbolSources": [
        "ios",
        "microsoft",
        "nuget",
        "autodesk",
        "amd",
        "citrix",
        "intel",
        "chromium",
        "electron",
        "nvidia",
        "ubuntu",
        "mozilla",
        "android",
        "unity",
    ],
    "dynamicSamplingBiases": [
        {"id": "boostEnvironments", "active": True},
        {"id": "boostLatestRelease", "active": True},
        {"id": "ignoreHealthChecks", "active": True},
        {"id": "boostKeyTransactions", "active": True},
        {"id": "boostLowVolumeTransactions", "active": True},
        {"id": "boostReplayId", "active": True},
        {"id": "recalibrationRule", "active": True},
    ],
    "eventProcessing": {"symbolicationDegraded": False},
    "symbolSources": '[{"secret_key":{"hidden-secret":True},"id":"60a033a8-dbf2-4b93-bb1a-daaa9acfb73a","layout":{"type":"native","casing":"default"},"name":"asdf","bucket":"asdf","region":"us-east-1","access_key":"asdf","type":"s3"},{"private_key":{"hidden-secret":True},"id":"b6ae6d66-67fe-4b1d-96c8-c8de9b3766be","layout":{"type":"native","casing":"default"},"name":"asdf","bucket":"asdf","client_email":"asdf@me.com","type":"gcs"},{"id":"15f4fcb4-6516-4880-bb71-a021fcc1a86c","name":"asdf","url":"asdf.com","layout":{"type":"native","casing":"default"},"type":"http"}]',
}


class ProjectExamples:
    BASE_KEY = [
        OpenApiExample(
            "Client key with rate limiting",
            value=key_with_rate_limiting,
            status_codes=["200", "201"],
            response_only=True,
        ),
    ]

    CREATE_PROJECT = [
        OpenApiExample(
            "Project successfully created",
            value=project,
            status_codes=["201"],
            response_only=True,
        ),
    ]

    LIST_CLIENT_KEYS = [
        OpenApiExample(
            "List Client Keys for a Project",
            value=[
                key_with_rate_limiting,
                key_wo_rate_limiting,
            ],
            status_codes=["200"],
            response_only=True,
        ),
    ]

    RETREVE_CLIENT_KEY = [
        OpenApiExample(
            "Retrieve an Existing Client Key",
            value=key_wo_rate_limiting,
            status_codes=["200"],
            response_only=True,
        ),
    ]

    RETRIEVE_PROJECT = [
        OpenApiExample(
            "Get detailed view about a Project",
            value=[detailed_project],
            status_codes=["200"],
            response_only=True,
        ),
    ]
