from drf_spectacular.utils import OpenApiExample


class TeamExamples:
    LIST_TEAM_PROJECTS = [
        OpenApiExample(
            "Get list of team's projects",
            value=[
                {
                    "team": {
                        "id": "2349234102",
                        "name": "Prime Mover",
                        "slug": "prime-mover",
                    },
                    "teams": [
                        {
                            "id": "2349234102",
                            "name": "Prime Mover",
                            "slug": "prime-mover",
                        },
                        {
                            "id": "47584447",
                            "name": "Powerful Abolitionist",
                            "slug": "powerful-abolitionist",
                        },
                    ],
                    "id": "6758470122493650",
                    "name": "the-spoiled-yoghurt",
                    "slug": "The Spoiled Yoghurt",
                    "isBookmarked": False,
                    "isMember": True,
                    "access": [
                        "project:read",
                        "event:read",
                        "team:read",
                        "alerts:read",
                        "org:read",
                        "event:write",
                        "project:releases",
                        "member:read",
                    ],
                    "hasAccess": True,
                    "dateCreated": "2023-03-29T15:25:21.344565Z",
                    "environments": ["production"],
                    "eventProcessing": {"symbolicationDegraded": False},
                    "features": [
                        "alert-filters",
                        "custom-inbound-filters",
                        "data-forwarding",
                        "discard-groups",
                        "minidump",
                        "race-free-group-creation",
                        "rate-limits",
                        "servicehooks",
                        "similarity-indexing",
                        "similarity-indexing-v2",
                        "similarity-view",
                        "similarity-view-v2",
                    ],
                    "firstEvent": None,
                    "firstTransactionEvent": True,
                    "hasSessions": False,
                    "hasProfiles": False,
                    "hasReplays": False,
                    "hasMonitors": False,
                    "hasMinifiedStackTrace": False,
                    "platform": "node-express",
                    "platforms": [],
                    "latestRelease": None,
                    "hasUserReports": False,
                    "latestDeploys": None,
                },
                {
                    "team": {
                        "id": "2349234102",
                        "name": "Prime Mover",
                        "slug": "prime-mover",
                    },
                    "teams": [
                        {
                            "id": "2349234102",
                            "name": "Prime Mover",
                            "slug": "prime-mover",
                        }
                    ],
                    "id": "1829334501859481",
                    "name": "Pump Station",
                    "slug": "pump-station",
                    "isBookmarked": False,
                    "isMember": True,
                    "access": [
                        "project:read",
                        "event:read",
                        "team:read",
                        "alerts:read",
                        "org:read",
                        "event:write",
                        "project:releases",
                        "member:read",
                    ],
                    "hasAccess": True,
                    "dateCreated": "2023-03-29T15:21:49.943746Z",
                    "environments": ["production"],
                    "eventProcessing": {"symbolicationDegraded": False},
                    "features": [
                        "alert-filters",
                        "custom-inbound-filters",
                        "data-forwarding",
                        "discard-groups",
                        "minidump",
                        "race-free-group-creation",
                        "rate-limits",
                        "servicehooks",
                        "similarity-indexing",
                        "similarity-indexing-v2",
                        "similarity-view",
                        "similarity-view-v2",
                    ],
                    "firstEvent": "2023-04-05T21:02:08.054000Z",
                    "firstTransactionEvent": False,
                    "hasSessions": False,
                    "hasProfiles": False,
                    "hasReplays": False,
                    "hasMonitors": False,
                    "hasMinifiedStackTrace": True,
                    "platform": "javascript",
                    "platforms": ["javascript"],
                    "latestRelease": None,
                    "hasUserReports": False,
                    "latestDeploys": None,
                },
            ],
            status_codes=["200"],
            response_only=True,
        )
    ]
