minVersion: '2.33.1'
releaseBranchPrefix: scraps/release
changelog:
  filePath: CHANGELOG.md
  policy: auto
statusProvider:
  name: github
  config:
    contexts:
      - scraps-package-verify
artifactProvider:
  name: github
  config:
    artifacts:
      Scraps package:
        - scraps-tarball
targets:
  - name: github
    tagPrefix: scraps@
  - name: npm
    access: public
versioning:
  policy: auto
