// TODO(seer-workflows): Replace with a real endpoint once the backend exists.
// Expected shape: `GET /organizations/{slug}/seer/autofix/completed-issues/`
// returning `CompletedAutofixIssue[]`.

import type {PlatformKey} from 'sentry/types/project';

import type {CompletedAutofixIssue} from './types';

const NOW = Date.now();
const hoursAgo = (h: number) => new Date(NOW - h * 60 * 60_000).toISOString();
const daysAgo = (d: number) => new Date(NOW - d * 24 * 60 * 60_000).toISOString();

const PROJECTS = {
  javascript: {slug: 'javascript', platform: 'javascript'},
  python: {slug: 'python-backend', platform: 'python'},
  mobile: {slug: 'mobile-ios', platform: 'apple-ios'},
} satisfies Record<string, {platform: PlatformKey; slug: string}>;

export const MOCK_COMPLETED_AUTOFIX_ISSUES: CompletedAutofixIssue[] = [
  // ── Awaiting your review (review_pr) — 2 rows ─────────────────────────────
  {
    id: '4001',
    shortId: 'JAVASCRIPT-AB1',
    title: "TypeError: Cannot read properties of undefined (reading 'map')",
    level: 'error',
    project: PROJECTS.javascript,
    trigger: 'night_shift',
    outcomes: ['root_cause', 'solution', 'code_changes', 'pr_opened'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: hoursAgo(1),
    lastSeen: hoursAgo(2),
    eventCount: 1284,
    userCount: 312,
    prUrl: 'https://github.com/example/repo/pull/4421',
  },
  {
    id: '4002',
    shortId: 'PYTHON-BACKEND-7C',
    title: "KeyError: 'organization_id' missing from request payload",
    level: 'fatal',
    project: PROJECTS.python,
    trigger: 'alert',
    outcomes: ['root_cause', 'solution', 'code_changes', 'pr_opened'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: hoursAgo(3),
    lastSeen: hoursAgo(4),
    eventCount: 92,
    userCount: 41,
    prUrl: 'https://github.com/example/repo/pull/4420',
  },

  // ── Merged PRs (prMerged) — 5 rows ────────────────────────────────────────
  {
    id: '4003',
    shortId: 'PYTHON-BACKEND-7D',
    title: 'OperationalError: deadlock detected in projects_project',
    level: 'fatal',
    project: PROJECTS.python,
    trigger: 'alert',
    outcomes: ['root_cause', 'solution', 'code_changes', 'pr_opened'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: hoursAgo(6),
    lastSeen: hoursAgo(7),
    eventCount: 211,
    userCount: 88,
    prUrl: 'https://github.com/example/repo/pull/4419',
    prMerged: true,
  },
  {
    id: '4004',
    shortId: 'JAVASCRIPT-AB2',
    title: 'ChunkLoadError: Loading chunk 482 failed',
    level: 'error',
    project: PROJECTS.javascript,
    trigger: 'post_process',
    outcomes: ['root_cause', 'solution', 'code_changes', 'pr_opened'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: daysAgo(1),
    lastSeen: hoursAgo(8),
    eventCount: 5642,
    userCount: 1108,
    prUrl: 'https://github.com/example/repo/pull/4408',
    prMerged: true,
  },
  {
    id: '4005',
    shortId: 'JAVASCRIPT-AB5',
    title: 'AbortError: The user aborted a request',
    level: 'warning',
    project: PROJECTS.javascript,
    trigger: 'night_shift',
    outcomes: ['root_cause', 'solution', 'code_changes', 'pr_opened'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: daysAgo(2),
    lastSeen: daysAgo(1),
    eventCount: 1820,
    userCount: 612,
    prUrl: 'https://github.com/example/repo/pull/4302',
    prMerged: true,
  },
  {
    id: '4006',
    shortId: 'JAVASCRIPT-AB6',
    title: 'NetworkError: Failed to fetch /api/v2/projects',
    level: 'error',
    project: PROJECTS.javascript,
    trigger: 'alert',
    outcomes: ['root_cause', 'solution', 'code_changes', 'pr_opened'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: daysAgo(3),
    lastSeen: daysAgo(2),
    eventCount: 4210,
    userCount: 1402,
    prUrl: 'https://github.com/example/repo/pull/4289',
    prMerged: true,
  },
  {
    id: '4007',
    shortId: 'JAVASCRIPT-AB7',
    title: 'SyntaxError: Unexpected token < in JSON at position 0',
    level: 'error',
    project: PROJECTS.javascript,
    trigger: 'manual',
    outcomes: ['root_cause', 'solution', 'code_changes', 'pr_opened'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: daysAgo(5),
    lastSeen: daysAgo(3),
    eventCount: 387,
    userCount: 142,
    prUrl: 'https://github.com/example/repo/pull/4251',
    prMerged: true,
  },

  // ── Code changes ready — 4 rows ───────────────────────────────────────────
  {
    id: '4008',
    shortId: 'PYTHON-BACKEND-7D',
    title: 'TimeoutError: Connection to redis timed out after 5s',
    level: 'error',
    project: PROJECTS.python,
    trigger: 'issue_summary',
    outcomes: ['root_cause', 'solution', 'code_changes'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: hoursAgo(5),
    lastSeen: hoursAgo(6),
    eventCount: 211,
    userCount: 88,
  },
  {
    id: '4009',
    shortId: 'MOBILE-IOS-3F',
    title: 'NSInvalidArgumentException in -[UIView setFrame:]',
    level: 'error',
    project: PROJECTS.mobile,
    trigger: 'manual',
    outcomes: ['root_cause', 'solution', 'code_changes'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: daysAgo(2),
    lastSeen: daysAgo(1),
    eventCount: 47,
    userCount: 22,
  },
  {
    id: '4010',
    shortId: 'JAVASCRIPT-AB8',
    title: "ReferenceError: 'tracker' is not defined",
    level: 'error',
    project: PROJECTS.javascript,
    trigger: 'post_process',
    outcomes: ['root_cause', 'solution', 'code_changes'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: daysAgo(4),
    lastSeen: daysAgo(2),
    eventCount: 156,
    userCount: 74,
  },
  {
    id: '4011',
    shortId: 'PYTHON-BACKEND-7G',
    title: "ValueError: invalid literal for int() with base 10: 'abc'",
    level: 'warning',
    project: PROJECTS.python,
    trigger: 'issue_summary',
    outcomes: ['root_cause', 'solution', 'code_changes'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: daysAgo(6),
    lastSeen: daysAgo(4),
    eventCount: 84,
    userCount: 36,
  },

  // ── Solution proposed — 4 rows ────────────────────────────────────────────
  {
    id: '4012',
    shortId: 'JAVASCRIPT-AB3',
    title: 'Sentry.captureException called with non-Error value',
    level: 'warning',
    project: PROJECTS.javascript,
    trigger: 'manual',
    outcomes: ['root_cause', 'solution'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: daysAgo(3),
    lastSeen: hoursAgo(12),
    eventCount: 803,
    userCount: 240,
  },
  {
    id: '4013',
    shortId: 'PYTHON-BACKEND-7E',
    title: 'IntegrityError: duplicate key value violates unique constraint',
    level: 'error',
    project: PROJECTS.python,
    trigger: 'alert',
    outcomes: ['root_cause', 'solution'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: daysAgo(4),
    lastSeen: daysAgo(2),
    eventCount: 31,
    userCount: 18,
  },
  {
    id: '4014',
    shortId: 'MOBILE-IOS-40',
    title: 'EXC_BAD_ACCESS in SignalingThread::Run',
    level: 'fatal',
    project: PROJECTS.mobile,
    trigger: 'post_process',
    outcomes: ['root_cause', 'solution'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: daysAgo(7),
    lastSeen: daysAgo(3),
    eventCount: 16,
    userCount: 9,
  },
  {
    id: '4015',
    shortId: 'PYTHON-BACKEND-7H',
    title: 'AssertionError: assertion failed in worker.process_chunk',
    level: 'error',
    project: PROJECTS.python,
    trigger: 'manual',
    outcomes: ['root_cause', 'solution'],
    autofixRunStatus: 'COMPLETED',
    autofixCompletedAt: daysAgo(8),
    lastSeen: daysAgo(5),
    eventCount: 23,
    userCount: 11,
  },

  // ── Awaiting your input (NEED_MORE_INFORMATION) — 3 rows ──────────────────
  {
    id: '4016',
    shortId: 'JAVASCRIPT-AB4',
    title: 'Hydration failed because the initial UI does not match the server',
    level: 'error',
    project: PROJECTS.javascript,
    trigger: 'issue_summary',
    outcomes: ['root_cause'],
    autofixRunStatus: 'NEED_MORE_INFORMATION',
    autofixCompletedAt: daysAgo(9),
    lastSeen: daysAgo(5),
    eventCount: 412,
    userCount: 187,
  },
  {
    id: '4017',
    shortId: 'PYTHON-BACKEND-7F',
    title: "AttributeError: 'NoneType' object has no attribute 'organization'",
    level: 'error',
    project: PROJECTS.python,
    trigger: 'manual',
    outcomes: ['root_cause'],
    autofixRunStatus: 'NEED_MORE_INFORMATION',
    autofixCompletedAt: daysAgo(12),
    lastSeen: daysAgo(7),
    eventCount: 58,
    userCount: 23,
  },
  {
    id: '4018',
    shortId: 'PYTHON-BACKEND-7I',
    title: 'MemoryError: Out of memory in event_processor',
    level: 'error',
    project: PROJECTS.python,
    trigger: 'alert',
    outcomes: ['root_cause'],
    autofixRunStatus: 'NEED_MORE_INFORMATION',
    autofixCompletedAt: daysAgo(14),
    lastSeen: daysAgo(9),
    eventCount: 19,
    userCount: 12,
  },

  // ── Errored (ERROR run status) — 2 rows ───────────────────────────────────
  {
    id: '4019',
    shortId: 'MOBILE-IOS-41',
    title: 'CoreDataError: persistent store coordinator missing',
    level: 'error',
    project: PROJECTS.mobile,
    trigger: 'issue_summary',
    outcomes: ['root_cause'],
    autofixRunStatus: 'ERROR',
    autofixCompletedAt: daysAgo(18),
    lastSeen: daysAgo(10),
    eventCount: 7,
    userCount: 4,
  },
  {
    id: '4020',
    shortId: 'JAVASCRIPT-AB9',
    title: 'RangeError: Maximum call stack size exceeded',
    level: 'fatal',
    project: PROJECTS.javascript,
    trigger: 'post_process',
    outcomes: ['root_cause'],
    autofixRunStatus: 'ERROR',
    autofixCompletedAt: daysAgo(21),
    lastSeen: daysAgo(12),
    eventCount: 51,
    userCount: 29,
  },
];
