export enum ReplayColumn {
  ACTIVITY = 'activity',
  BROWSER = 'browser',
  COUNT_DEAD_CLICKS = 'countDeadClicks',
  COUNT_DEAD_CLICKS_NO_HEADER = 'countDeadClicksNoHeader',
  COUNT_ERRORS = 'countErrors',
  COUNT_RAGE_CLICKS = 'countRageClicks',
  COUNT_RAGE_CLICKS_NO_HEADER = 'countRageClicksNoHeader',
  DURATION = 'duration',
  MOST_ERRONEOUS_REPLAYS = 'mostErroneousReplays',
  MOST_RAGE_CLICKS = 'mostRageClicks',
  MOST_DEAD_CLICKS = 'mostDeadClicks',
  OS = 'os',
  REPLAY = 'replay',
  SLOWEST_TRANSACTION = 'slowestTransaction',
}
