# Generated by Django 5.2.1 on 2025-09-03 18:57

from typing import int
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    initial = True

    dependencies = [
        ("sentry", "0972_commit_comparison_drop_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "organization_id",
                    sentry.db.models.fields.bounded.BoundedBigIntegerField(db_index=True),
                ),
                ("repository_id", sentry.db.models.fields.bounded.BoundedPositiveIntegerField()),
                ("key", models.CharField(max_length=64)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(null=True)),
                (
                    "author",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releasecommit_set",
                        to="sentry.commitauthor",
                    ),
                ),
            ],
            options={
                "db_table": "releases_commit",
            },
        ),
        migrations.CreateModel(
            name="CommitFileChange",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "organization_id",
                    sentry.db.models.fields.bounded.BoundedBigIntegerField(db_index=True),
                ),
                ("filename", models.TextField()),
                ("type", models.CharField(max_length=1)),
                (
                    "commit",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="releases.commit"
                    ),
                ),
            ],
            options={
                "db_table": "releases_commitfilechange",
            },
        ),
        migrations.AddIndex(
            model_name="commit",
            index=models.Index(
                fields=["repository_id", "date_added"], name="releases_co_reposit_a050ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commit",
            index=models.Index(
                fields=["author", "date_added"], name="releases_co_author__3d0b29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commit",
            index=models.Index(
                fields=["organization_id", "date_added"], name="releases_co_organiz_bcc54e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commit",
            unique_together={("repository_id", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="commitfilechange",
            unique_together={("commit", "filename")},
        ),
    ]
