"""
Context metadata for Sentry-defined attributes that are *not* part of
``sentry-conventions``.

``sentry-conventions`` describes the semantic telemetry vocabulary (what an
emitted attribute means, largely OTel-aligned). The trace-item search layer also
exposes query-layer aliases and product fields — e.g. ``span.description`` — that
are Sentry-defined (``source_type == sentry``) but aren't semantic conventions,
so they have no entry there.

This module is the home for their context. It mirrors
``sentry_conventions.attributes.ATTRIBUTE_METADATA`` by reusing ``AttributeMetadata``,
so the same context builder works on both. Unlike conventions, attributes here
resolve with ``isConvention=False``; clients distinguish them via ``source_type``.

Context here is attached whenever the attribute is returned by ``/attributes``.
``SENTRY_ALWAYS_INCLUDED_ATTRIBUTES`` (below) is the narrower set the endpoint
*also* force-includes in its response, for attributes that would otherwise be
paged out past the attribute-name limit.

Span and log descriptions are sourced from Seer's ``attributes_reference.py``
(``getsentry/seer``); the trailing ``Type: X`` hint is dropped since the type is
carried separately. Trace-metric descriptions aren't in Seer, so they're authored
here.
"""

from sentry_conventions.attributes import (
    AttributeMetadata,
    AttributeType,
    IsPii,
    PiiInfo,
    Visibility,
)

from sentry.search.eap.types import SupportedTraceItemType

_NO_PII = PiiInfo(isPii=IsPii.FALSE, reason=None)

_TRACE_BRIEF = (
    "A trace represents the record of an entire operation you want to measure or "
    "track (e.g. a page load), identified by the UUID generated by Sentry's SDK."
)


def _sentry_attribute(
    brief: str,
    *,
    attribute_type: AttributeType = AttributeType.STRING,
    example: str | None = None,
    additional_context: list[str] | None = None,
) -> AttributeMetadata:
    """Build an ``AttributeMetadata`` for a Sentry-defined (non-convention) attribute."""
    return AttributeMetadata(
        brief=brief,
        type=attribute_type,
        pii=_NO_PII,
        is_in_otel=False,
        visibility=Visibility.PUBLIC,
        example=example,
        additional_context=additional_context,
    )


# Keyed by public alias. Add an entry here to give a Sentry-defined attribute a
# description; its context is attached whenever `/attributes` returns it.
SENTRY_ATTRIBUTE_METADATA: dict[SupportedTraceItemType, dict[str, AttributeMetadata]] = {
    SupportedTraceItemType.SPANS: {
        "span.description": _sentry_attribute("Description of the span's operation."),
        "span.duration": _sentry_attribute(
            "The total time taken by the span.", attribute_type=AttributeType.DOUBLE
        ),
        "span.self_time": _sentry_attribute(
            "The duration of the span excluding the duration of its child spans.",
            attribute_type=AttributeType.DOUBLE,
        ),
        "is_transaction": _sentry_attribute(
            "Whether the span is also a transaction.", attribute_type=AttributeType.BOOLEAN
        ),
        "project": _sentry_attribute("The name of the project."),
        "project.id": _sentry_attribute(
            "The numeric ID of the project.", attribute_type=AttributeType.INTEGER
        ),
        "timestamp": _sentry_attribute("The timestamp marking when the span finished."),
        "trace": _sentry_attribute(_TRACE_BRIEF),
    },
    SupportedTraceItemType.LOGS: {
        "message": _sentry_attribute("The full log message body."),
        "severity": _sentry_attribute(
            "The severity level assigned to the log, indicating its impact "
            "(e.g. error, warn, or info)."
        ),
        "severity_number": _sentry_attribute(
            "Numeric severity level of the log entry (higher values indicate more severe events).",
            attribute_type=AttributeType.INTEGER,
        ),
        "project": _sentry_attribute("The name of the project."),
        "timestamp": _sentry_attribute("The timestamp of the log entry."),
        "trace": _sentry_attribute(_TRACE_BRIEF),
    },
    SupportedTraceItemType.TRACEMETRICS: {
        "metric.name": _sentry_attribute("The name of the metric."),
        "metric.type": _sentry_attribute(
            "The type of the metric (counter, gauge, or distribution)."
        ),
        "metric.unit": _sentry_attribute("The unit of the metric's value."),
        "value": _sentry_attribute(
            "The numeric value of the metric.", attribute_type=AttributeType.DOUBLE
        ),
        "project": _sentry_attribute("The name of the project."),
        "timestamp": _sentry_attribute("The timestamp of the metric."),
        "trace": _sentry_attribute(_TRACE_BRIEF),
    },
}


# Attributes the `/attributes` endpoint force-includes in its response even when
# the attribute-names RPC pages them out past its key limit. Kept deliberately
# narrow (it widens every no-substring response, including the frontend's), so it
# only covers attributes with a demonstrated paging problem rather than every
# described attribute. Each must be a key in SENTRY_ATTRIBUTE_METADATA.
SENTRY_ALWAYS_INCLUDED_ATTRIBUTES: dict[SupportedTraceItemType, frozenset[str]] = {
    SupportedTraceItemType.SPANS: frozenset({"span.description"}),
    SupportedTraceItemType.LOGS: frozenset(),
    SupportedTraceItemType.TRACEMETRICS: frozenset(),
}
