'use strict';

/**
 * Generates the StyleX theme and layout style modules for @sentry/scraps from
 * the JS theme, so StyleX components and Emotion components read the same
 * values.
 *
 * - theme/tokens.stylex.ts      defineVars: light values of theme-dependent tokens
 * - theme/constants.stylex.ts   defineConsts: theme-independent scales
 * - theme/darkTheme.tsx         createTheme: dark overrides of tokens.stylex.ts
 * - layout/generatedStyles.tsx  stylex.create: per-property layout styles
 *
 * Usage:
 *   pnpm gen:stylex-theme
 */
import {execFileSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
import * as path from 'node:path';

// eslint-disable-next-line boundaries/dependencies -- codegen script
import {darkTheme, lightTheme} from '../static/app/utils/theme/theme';

const SCRAPS = path.resolve(process.cwd(), 'static/packages/scraps/src');
const HEADER = `// AUTOGENERATED BY scripts/genStylexTheme.ts (pnpm gen:stylex-theme)
// DO NOT EDIT THIS FILE MANUALLY
`;

type Tree = Record<string, unknown>;

/** `['chonky', 'embossed', 'accent']` → `chonkyEmbossedAccent` */
function camelJoin(segments: string[]): string {
  return segments
    .map((s, i) => (i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1)))
    .join('');
}

/** Flattens a nested token tree into `{camelCasedPath: value}`, skipping non-CSS values. */
function flatten(tree: Tree, prefix: string[] = []): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, value] of Object.entries(tree)) {
    if (Array.isArray(value) || typeof value === 'function') {
      continue;
    }
    if (value && typeof value === 'object') {
      Object.assign(result, flatten(value as Tree, [...prefix, key]));
      continue;
    }
    result[camelJoin([...prefix, key])] = String(value);
  }
  return result;
}

function objectLiteral(values: Record<string, string | number>): string {
  return `{${Object.entries(values)
    .map(([k, v]) => `${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n')}}`;
}

// tokens.stylex.ts / darkTheme.tsx

// Theme-dependent groups. `theme.tokens.<group>.a.b` → `<group>.aB`.
const varGroups: Array<[name: string, light: Tree, dark: Tree, doc: string]> = [
  ...Object.keys(lightTheme.tokens).map(
    group =>
      [
        group,
        (lightTheme.tokens as unknown as Tree)[group] as Tree,
        (darkTheme.tokens as unknown as Tree)[group] as Tree,
        `theme.tokens.${group}`,
      ] as [string, Tree, Tree, string]
  ),
  [
    'colors',
    lightTheme.colors as unknown as Tree,
    darkTheme.colors as unknown as Tree,
    'theme.colors (deprecated palette)',
  ],
  [
    'shadow',
    lightTheme.shadow as unknown as Tree,
    darkTheme.shadow as unknown as Tree,
    'theme.shadow',
  ],
];

const tokensFile = `${HEADER}
import * as stylex from '@stylexjs/stylex';

${varGroups
  .map(
    ([name, light, _dark, doc]) =>
      `/** \`${doc}\`, as CSS variables. Light values; see darkTheme.tsx. */
export const ${name} = stylex.defineVars(${objectLiteral(flatten(light))});`
  )
  .join('\n\n')}
`;

const darkFile = `${HEADER}
import * as stylex from '@stylexjs/stylex';

import {${varGroups.map(([name]) => name).join(', ')}} from './tokens.stylex';

${varGroups
  .map(([name, light, dark]) => {
    const lightValues = flatten(light);
    const overrides = Object.fromEntries(
      Object.entries(flatten(dark)).filter(([k, v]) => lightValues[k] !== v)
    );
    return `const ${name}Dark = stylex.createTheme(${name}, ${objectLiteral(overrides)});`;
  })
  .join('\n\n')}

/**
 * Applied to the document root when the dark theme is active.
 */
export const stylexDarkTheme = [${varGroups.map(([name]) => `${name}Dark`).join(', ')}];
`;

// constants.stylex.ts

const px = (v: string | number) => (typeof v === 'number' ? `${v}px` : v);
const theme = lightTheme;

const constGroups: Record<string, Record<string, string | number>> = {
  space: theme.space,
  radius: theme.radius,
  borderWidth: theme.border,
  size: theme.size,
  fontSize: theme.font.size,
  fontFamily: theme.font.family,
  fontWeight: flatten(theme.font.weight as unknown as Tree),
  lineHeight: flatten(theme.font.lineHeight as unknown as Tree),
  zIndex: theme.zIndex,
  motion: Object.fromEntries(
    Object.entries(flatten(theme.motion as unknown as Tree)).filter(
      ([k]) => !k.startsWith('framer')
    )
  ),
  form: Object.fromEntries(
    Object.entries(flatten(theme.form as unknown as Tree)).map(([k, v]) => [
      k,
      /padding/.test(k) ? px(Number(v)) : v,
    ])
  ),
  breakpoints: theme.breakpoints,
  container: theme.container,
  /** `@media` at-rules for `[media.md]: …` keys, by viewport breakpoint. */
  media: Object.fromEntries(
    Object.entries(theme.breakpoints).map(([k, v]) => [k, `@media (min-width: ${v})`])
  ),
  /** `@container` at-rules for `[containerQuery.md]: …` keys, by container breakpoint. */
  containerQuery: Object.fromEntries(
    Object.entries(theme.container).map(([k, v]) => [k, `@container (min-width: ${v})`])
  ),
};

const constantsFile = `${HEADER}
import * as stylex from '@stylexjs/stylex';

${Object.entries(constGroups)
  .map(
    ([name, values]) =>
      `export const ${name} = stylex.defineConsts(${objectLiteral(values)});`
  )
  .join('\n\n')}
`;

// layout/generatedStyles.tsx

// Every CSS property a layout or text primitive can set from a prop.
const LAYOUT_PROPERTIES = [
  'containerType',
  'display',
  'position',
  'inset',
  'top',
  'bottom',
  'left',
  'right',
  'overflow',
  'overflowX',
  'overflowY',
  'overscrollBehavior',
  'pointerEvents',
  'cursor',
  'contain',
  'padding',
  'paddingTop',
  'paddingBottom',
  'paddingLeft',
  'paddingRight',
  'margin',
  'marginTop',
  'marginBottom',
  'marginLeft',
  'marginRight',
  'backgroundColor',
  'borderRadius',
  'width',
  'minWidth',
  'maxWidth',
  'height',
  'minHeight',
  'maxHeight',
  'gridArea',
  'gridRow',
  'gridColumn',
  'order',
  'flex',
  'flexGrow',
  'flexShrink',
  'flexBasis',
  'alignSelf',
  'justifySelf',
  // StyleX drops the `border*` shorthands, so borders are set as longhands.
  ...['border', 'borderTop', 'borderBottom', 'borderLeft', 'borderRight'].flatMap(
    side => [`${side}Width`, `${side}Style`, `${side}Color`] as const
  ),
  'visibility',
  'whiteSpace',
  'gap',
  'flexDirection',
  'flexWrap',
  'justifyContent',
  'alignItems',
  'alignContent',
  'justifyItems',
  'gridTemplateColumns',
  'gridTemplateRows',
  'gridTemplateAreas',
  'gridAutoColumns',
  'gridAutoRows',
  'gridAutoFlow',
  'boxShadow',
  'fontSize',
  'lineHeight',
  'textAlign',
] as string[];

// Responsive keys, in cascade order. `zero` is never needed as a breakpoint:
// when set it is always the first defined key, which applies unconditionally.
const BREAKPOINTS: Array<[key: string, query: string]> = [
  ...Object.entries(theme.container)
    .filter(([k]) => k !== 'zero')
    .map(([k, v]): [string, string] => [k, `@container (min-width: ${v})`]),
  ...Object.entries(theme.breakpoints).map(([k, v]): [string, string] => [
    `screen:${k}`,
    `@media (min-width: ${v})`,
  ]),
];

// StyleX orders `@media` rules by width but `@container` rules by their
// declaration text, so the variable names carry the breakpoint's position to
// keep the cascade mobile-first: `--sx-gap-01-3xs`, `--sx-gap-02-2xs`, …
const breakpointVarSuffix = Object.fromEntries(
  BREAKPOINTS.map(([key], i) => [
    key,
    `${String(i + 1).padStart(2, '0')}-${key.replace(':', '-')}`,
  ])
);

/** Must match `layoutVarName` in layout/stylexLayout.tsx. */
function layoutVarName(property: string, key?: string) {
  return key ? `--sx-${property}-${breakpointVarSuffix[key]}` : `--sx-${property}`;
}

const spaceTokens = Object.keys(theme.space);
const radiusTokens = Object.keys(theme.radius);
const identity = (values: string[]) => Object.fromEntries(values.map(v => [v, v]));
const member = (group: string, key: string) =>
  /^[A-Za-z_$][\w$]*$/.test(key) ? `${group}.${key}` : `${group}[${JSON.stringify(key)}]`;
const tokens = (values: string[], group: string) =>
  Object.fromEntries(values.map(v => [v, member(group, v)]));

// Static classes for common prop values, keyed `${prop}:${value}` with the
// value as written at the call site. Values in `expr` are TS expressions.
type FixedValues = {
  css: string;
  expr?: Record<string, string>;
  values?: Record<string, string>;
};
// Border variants as longhands, keyed like the other fixed values.
const BORDER_COLORS: Record<string, string> = {
  primary: 'border.primary',
  secondary: 'border.secondary',
  muted: 'border.secondary',
  ...Object.fromEntries(
    ['accent', 'danger', 'promotion', 'success', 'warning'].map(v => [
      v,
      `border.${v}Vibrant`,
    ])
  ),
};
const borderEntries = (side: string) => [
  `${JSON.stringify(`${side}:none`)}: {${side}Width: 0, ${side}Style: 'none'}`,
  ...Object.entries(BORDER_COLORS).map(
    ([variant, color]) =>
      `${JSON.stringify(`${side}:${variant}`)}: {${side}Width: '1px', ${side}Style: 'solid', ${side}Color: ${color}}`
  ),
];
const spaceExpr = (target: string, extra: Record<string, string> = {}) => ({
  css: target,
  expr: {...tokens(spaceTokens, 'space'), ...extra},
});
const FIXED: Record<string, FixedValues> = {
  display: {
    css: 'display',
    values: identity([
      'flex',
      'inline-flex',
      'none',
      'block',
      'inline-block',
      'inline',
      'grid',
      'inline-grid',
      'contents',
    ]),
  },
  position: {
    css: 'position',
    values: identity(['static', 'relative', 'absolute', 'fixed', 'sticky']),
  },
  direction: {
    css: 'flexDirection',
    values: identity(['row', 'row-reverse', 'column', 'column-reverse']),
  },
  wrap: {css: 'flexWrap', values: identity(['nowrap', 'wrap', 'wrap-reverse'])},
  flexAlign: {
    css: 'alignItems',
    values: {
      start: 'flex-start',
      end: 'flex-end',
      center: 'center',
      baseline: 'baseline',
      stretch: 'stretch',
    },
  },
  flexJustify: {
    css: 'justifyContent',
    values: {
      start: 'flex-start',
      end: 'flex-end',
      center: 'center',
      between: 'space-between',
      around: 'space-around',
      evenly: 'space-evenly',
      left: 'left',
      right: 'right',
    },
  },
  gridAlign: {
    css: 'alignItems',
    values: identity(['start', 'end', 'center', 'baseline', 'stretch']),
  },
  gridJustify: {
    css: 'justifyContent',
    values: {
      start: 'start',
      end: 'end',
      center: 'center',
      between: 'space-between',
      around: 'space-around',
      evenly: 'space-evenly',
      stretch: 'stretch',
    },
  },
  gridAlignContent: {
    css: 'alignContent',
    values: {
      start: 'start',
      end: 'end',
      center: 'center',
      between: 'space-between',
      around: 'space-around',
      evenly: 'space-evenly',
      stretch: 'stretch',
    },
  },
  justifyItems: {
    css: 'justifyItems',
    values: identity(['start', 'end', 'center', 'stretch']),
  },
  gap: spaceExpr('gap'),
  padding: spaceExpr('padding'),
  paddingTop: spaceExpr('paddingTop'),
  paddingBottom: spaceExpr('paddingBottom'),
  paddingLeft: spaceExpr('paddingLeft'),
  paddingRight: spaceExpr('paddingRight'),
  margin: spaceExpr('margin', {auto: `'auto'`}),
  marginTop: spaceExpr('marginTop', {auto: `'auto'`}),
  marginBottom: spaceExpr('marginBottom', {auto: `'auto'`}),
  marginLeft: spaceExpr('marginLeft', {auto: `'auto'`}),
  marginRight: spaceExpr('marginRight', {auto: `'auto'`}),
  radius: {css: 'borderRadius', expr: tokens(radiusTokens, 'radius')},
  background: {
    css: 'backgroundColor',
    expr: Object.fromEntries(
      ['primary', 'secondary', 'tertiary', 'overlay'].map(v => [v, `background.${v}`])
    ),
  },
  elevation: {
    css: 'boxShadow',
    expr: Object.fromEntries(['low', 'medium', 'high'].map(v => [v, `shadow.${v}`])),
  },
  overflow: {css: 'overflow', values: identity(['visible', 'hidden', 'scroll', 'auto'])},
  overflowX: {
    css: 'overflowX',
    values: identity(['visible', 'hidden', 'scroll', 'auto']),
  },
  overflowY: {
    css: 'overflowY',
    values: identity(['visible', 'hidden', 'scroll', 'auto']),
  },
  visibility: {css: 'visibility', values: identity(['visible', 'hidden', 'collapse'])},
  whiteSpace: {
    css: 'whiteSpace',
    values: identity(['nowrap', 'normal', 'pre', 'pre-line', 'pre-wrap', 'break-spaces']),
  },
  containerType: {
    css: 'containerType',
    values: identity(['inline-size', 'size', 'normal']),
  },
  pointerEvents: {css: 'pointerEvents', values: identity(['none', 'auto'])},
  cursor: {
    css: 'cursor',
    values: identity([
      'pointer',
      'default',
      'not-allowed',
      'text',
      'move',
      'help',
      'grab',
    ]),
  },
  flex: {
    css: 'flex',
    values: identity(['1', 'none', 'auto', '1 1 0', '1 1 auto', '0 0 auto']),
  },
  flexGrow: {css: 'flexGrow', values: identity(['0', '1'])},
  flexShrink: {css: 'flexShrink', values: identity(['0', '1'])},
  minWidth: {css: 'minWidth', values: identity(['0', '100%'])},
  minHeight: {css: 'minHeight', values: identity(['0', '100%'])},
  width: {css: 'width', values: identity(['100%', 'auto', 'max-content', 'fit-content'])},
  maxWidth: {css: 'maxWidth', values: identity(['100%', 'none'])},
  height: {css: 'height', values: identity(['100%', 'auto'])},
  maxHeight: {css: 'maxHeight', values: identity(['100%', 'none'])},
  alignSelf: {
    css: 'alignSelf',
    values: identity([
      'auto',
      'start',
      'end',
      'center',
      'stretch',
      'baseline',
      'flex-start',
      'flex-end',
    ]),
  },
  justifySelf: {
    css: 'justifySelf',
    values: identity([
      'auto',
      'start',
      'end',
      'center',
      'stretch',
      'flex-start',
      'flex-end',
    ]),
  },
  fontSize: {css: 'fontSize', expr: tokens(Object.keys(theme.font.size), 'fontSize')},
  density: {
    css: 'lineHeight',
    expr: tokens(Object.keys(theme.font.lineHeight), 'lineHeight'),
  },
  textAlign: {css: 'textAlign', values: identity(['left', 'center', 'right', 'justify'])},
  inset: {css: 'inset', values: identity(['0'])},
  top: {css: 'top', values: identity(['0'])},
  bottom: {css: 'bottom', values: identity(['0'])},
  left: {css: 'left', values: identity(['0'])},
  right: {css: 'right', values: identity(['0'])},
};

const fixedEntries: string[] = [
  'border',
  'borderTop',
  'borderBottom',
  'borderLeft',
  'borderRight',
].flatMap(borderEntries);
for (const [prop, {css, values, expr}] of Object.entries(FIXED)) {
  for (const [value, cssValue] of Object.entries(values ?? {})) {
    fixedEntries.push(
      `${JSON.stringify(`${prop}:${value}`)}: {${css}: ${JSON.stringify(cssValue)}}`
    );
  }
  for (const [value, cssExpr] of Object.entries(expr ?? {})) {
    fixedEntries.push(`${JSON.stringify(`${prop}:${value}`)}: {${css}: ${cssExpr}}`);
  }
}

const layoutFile = `${HEADER}
import * as stylex from '@stylexjs/stylex';

import {border, background, shadow} from '@sentry/scraps/theme/tokens.stylex';
import {fontSize, lineHeight, radius, space} from '@sentry/scraps/theme/constants.stylex';

/**
 * One style per CSS property, reading its value from the inline custom
 * property \`--sx-\${property}\` (see \`layoutVarName\`).
 *
 * These are plain classes rather than StyleX dynamic styles: a dynamic style
 * compiles to a function and an \`@property\` rule per variable, which across
 * every property and breakpoint costs ~3x the JS and CSS.
 */
export const baseStyles = stylex.create({
${LAYOUT_PROPERTIES.map(p => `  ${p}: {${p}: 'var(--sx-${p})'},`).join('\n')}
});

/**
 * One style per CSS property and responsive key, keyed \`\${property}@\${key}\`,
 * reading \`--sx-\${property}-\${key}\`. Each applies only inside its breakpoint's
 * query, so several can be combined for one property.
 */
export const breakpointStyles = stylex.create({
${LAYOUT_PROPERTIES.flatMap(p =>
  BREAKPOINTS.map(
    ([key, query]) =>
      `  ${JSON.stringify(`${p}@${key}`)}: {${p}: {default: null, ${JSON.stringify(query)}: 'var(${layoutVarName(p, key)})'}},`
  )
).join('\n')}
});

/**
 * Static classes for common prop values, keyed \`\${prop}:\${value}\` with the
 * value as written at the call site, so they need no inline CSS variables.
 */
export const fixedStyles = stylex.create({
${fixedEntries.map(e => `  ${e},`).join('\n')}
});

/**
 * Variable name suffix per responsive key: StyleX orders \`@container\` rules by
 * their declaration text, so the suffix carries the breakpoint's position.
 */
export const breakpointVarSuffix: Record<string, string> = ${JSON.stringify(breakpointVarSuffix)};

export type LayoutProperty = keyof typeof baseStyles;
export type ResponsiveKey = ${BREAKPOINTS.map(([k]) => JSON.stringify(k)).join(' | ')};
`;

const outputs: Array<[string, string]> = [
  [path.join(SCRAPS, 'theme/tokens.stylex.ts'), tokensFile],
  [path.join(SCRAPS, 'theme/darkTheme.tsx'), darkFile],
  [path.join(SCRAPS, 'theme/constants.stylex.ts'), constantsFile],
  [path.join(SCRAPS, 'layout/generatedStyles.tsx'), layoutFile],
];
for (const [file, contents] of outputs) {
  writeFileSync(file, contents);
}
execFileSync('pnpm', ['oxfmt', ...outputs.map(([file]) => file)], {stdio: 'ignore'});

for (const [file] of outputs) {
  console.log(`Wrote ${path.relative(process.cwd(), file)}`);
}
