#!/usr/bin/env bash
# Sentry route viewer — substitutes URL params and prints resolved routes.
#
# Usage:
#   ./scripts/routes.sh
#   BASE_URL=https://sentry.io ORG_ID=acme ./scripts/routes.sh
#   ./scripts/routes.sh | grep issues
#
# All param values can be overridden via environment variables.

BASE_URL="${BASE_URL:-http://dev.getsentry.net:7999}"

# Param defaults
ORG_ID="${ORG_ID:-sentry}"
PROJECT_ID="${PROJECT_ID:-javascript}"
GROUP_ID="${GROUP_ID:-6844521666}"
EVENT_ID="${EVENT_ID:-a4265e9e}"
EVENT_SLUG="${EVENT_SLUG:-my-project:abc123}"
TRACE_SLUG="${TRACE_SLUG:-10683c2584e2475e85e66ee601679a27}"
TAG_KEY="${TAG_KEY:-environment}"
RELEASE="${RELEASE:-1.0.0}"
MEMBER_ID="${MEMBER_ID:-1}"
TOKEN="${TOKEN:-abc123}"
SHARE_ID="${SHARE_ID:-abc123}"
TEAM_ID="${TEAM_ID:-design-engineering}"
KEY_ID="${KEY_ID:-1}"
AUTH_ID="${AUTH_ID:-1}"
TOKEN_ID="${TOKEN_ID:-1}"
APP_ID="${APP_ID:-1}"
APP_SLUG="${APP_SLUG:-my-sentry-app}"
API_KEY="${API_KEY:-1}"
DATA_EXPORT_ID="${DATA_EXPORT_ID:-1}"
DATA_FORWARDER_ID="${DATA_FORWARDER_ID:-1}"
DASHBOARD_ID="${DASHBOARD_ID:-316394}"
TEMPLATE_ID="${TEMPLATE_ID:-1}"
WIDGET_ID="${WIDGET_ID:-1}"
WIDGET_INDEX="${WIDGET_INDEX:-0}"
RULE_ID="${RULE_ID:-1}"
ALERT_ID="${ALERT_ID:-416}"
DETECTOR_ID="${DETECTOR_ID:-1}"
MONITOR_SLUG="${MONITOR_SLUG:-my-monitor}"
REPLAY_SLUG="${REPLAY_SLUG:-abc123}"
PLATFORM="${PLATFORM:-javascript}"
PLUGIN_ID="${PLUGIN_ID:-github}"
INTEGRATION_SLUG="${INTEGRATION_SLUG:-github}"
INTEGRATION_ID="${INTEGRATION_ID:-1}"
PROVIDER_KEY="${PROVIDER_KEY:-github}"
STEP="${STEP:-welcome}"
FINE_TUNE_TYPE="${FINE_TUNE_TYPE:-email}"
SCRUBBING_ID="${SCRUBBING_ID:-1}"
BUNDLE_ID="${BUNDLE_ID:-1}"
FILTER_TYPE="${FILTER_TYPE:-data-filters}"
HOOK_ID="${HOOK_ID:-1}"
SENTRY_APP_SLUG="${SENTRY_APP_SLUG:-my-sentry-app}"
NOTIFICATION_SOURCE="${NOTIFICATION_SOURCE:-email}"
ARTIFACT_ID="${ARTIFACT_ID:-1}"
HEAD_ARTIFACT_ID="${HEAD_ARTIFACT_ID:-2}"
BASE_ARTIFACT_ID="${BASE_ARTIFACT_ID:-1}"
SNAPSHOT_ID="${SNAPSHOT_ID:-1}"
REPO_ORG="${REPO_ORG:-my-org}"
REPO_NAME="${REPO_NAME:-my-repo}"
PR_ID="${PR_ID:-123}"
VIEW_ID="${VIEW_ID:-1}"
SEARCH_ID="${SEARCH_ID:-1}"
USER_ID="${USER_ID:-1}"
AUTH_SLUG="${AUTH_SLUG:-1}"

sub() {
  local r="$1"
  r="${r//:orgId/$ORG_ID}"
  r="${r//:projectId/$PROJECT_ID}"
  r="${r//:groupId/$GROUP_ID}"
  r="${r//:eventId/$EVENT_ID}"
  r="${r//:eventSlug/$EVENT_SLUG}"
  r="${r//:traceSlug/$TRACE_SLUG}"
  r="${r//:tagKey/$TAG_KEY}"
  r="${r//:release/$RELEASE}"
  r="${r//:memberId/$MEMBER_ID}"
  r="${r//:token/$TOKEN}"
  r="${r//:shareId/$SHARE_ID}"
  r="${r//:teamId/$TEAM_ID}"
  r="${r//:keyId/$KEY_ID}"
  r="${r//:authId/$AUTH_ID}"
  r="${r//:tokenId/$TOKEN_ID}"
  r="${r//:appId/$APP_ID}"
  r="${r//:appSlug/$APP_SLUG}"
  r="${r//:apiKey/$API_KEY}"
  r="${r//:dataExportId/$DATA_EXPORT_ID}"
  r="${r//:dataForwarderId/$DATA_FORWARDER_ID}"
  r="${r//:dashboardId/$DASHBOARD_ID}"
  r="${r//:templateId/$TEMPLATE_ID}"
  r="${r//:widgetId/$WIDGET_ID}"
  r="${r//:widgetIndex/$WIDGET_INDEX}"
  r="${r//:ruleId/$RULE_ID}"
  r="${r//:alertId/$ALERT_ID}"
  r="${r//:detectorId/$DETECTOR_ID}"
  r="${r//:monitorSlug/$MONITOR_SLUG}"
  r="${r//:replaySlug/$REPLAY_SLUG}"
  r="${r//:platform/$PLATFORM}"
  r="${r//:pluginId/$PLUGIN_ID}"
  r="${r//:integrationSlug/$INTEGRATION_SLUG}"
  r="${r//:integrationId/$INTEGRATION_ID}"
  r="${r//:providerKey/$PROVIDER_KEY}"
  r="${r//:step/$STEP}"
  r="${r//:fineTuneType/$FINE_TUNE_TYPE}"
  r="${r//:scrubbingId/$SCRUBBING_ID}"
  r="${r//:bundleId/$BUNDLE_ID}"
  r="${r//:filterType/$FILTER_TYPE}"
  r="${r//:hookId/$HOOK_ID}"
  r="${r//:sentryAppSlug/$SENTRY_APP_SLUG}"
  r="${r//:notificationSource/$NOTIFICATION_SOURCE}"
  r="${r//:artifactId/$ARTIFACT_ID}"
  r="${r//:headArtifactId/$HEAD_ARTIFACT_ID}"
  r="${r//:baseArtifactId/$BASE_ARTIFACT_ID}"
  r="${r//:snapshotId/$SNAPSHOT_ID}"
  r="${r//:repoOrg/$REPO_ORG}"
  r="${r//:repoName/$REPO_NAME}"
  r="${r//:prId/$PR_ID}"
  r="${r//:viewId/$VIEW_ID}"
  r="${r//:searchId/$SEARCH_ID}"
  r="${r//:id/$USER_ID}"
  r="${r//:installationId/$INTEGRATION_ID}"
  # strip optional marker and wildcards
  r="${r/\?/}"
  r="${r//\*/}"
  echo "${BASE_URL}${r}"
}

routes=(
  # ── Auth ──────────────────────────────────────────────────────────────────
  "/auth/login/"

  # ── Root / misc ───────────────────────────────────────────────────────────
  "/accept/:orgId/:memberId/:token/"
  "/accept/:memberId/:token/"
  "/accept-transfer/"
  "/extensions/external-install/:integrationSlug/:installationId"
  "/extensions/:integrationSlug/link/"
  "/sentry-apps/:sentryAppSlug/external-install/"
  "/share/issue/:shareId/"
  "/organizations/:orgId/share/issue/:shareId/"
  "/unsubscribe/project/:id/"
  "/unsubscribe/:orgId/project/:id/"
  "/unsubscribe/issue/:id/"
  "/unsubscribe/:orgId/issue/:id/"
  "/organizations/new/"
  "/data-export/:dataExportId"
  "/disabled-member/"
  "/restore/"
  "/organizations/:orgId/restore/"
  "/join-request/"
  "/join-request/:orgId/"
  "/relocation/"
  "/relocation/:step/"
  "/onboarding/"
  "/onboarding/:step/"
  "/onboarding/:orgId/"
  "/onboarding/:orgId/:step/"
  "/stories/"
  "/debug/notifications/:notificationSource/"

  # ── Settings ──────────────────────────────────────────────────────────────
  "/settings/"
  "/settings/account/"
  "/settings/account/details/"
  "/settings/account/notifications/"
  "/settings/account/notifications/:fineTuneType/"
  "/settings/account/emails/"
  "/settings/account/merge-accounts/"
  "/settings/account/authorizations/"
  "/settings/account/security/"
  "/settings/account/security/session-history/"
  "/settings/account/security/mfa/:authId/"
  "/settings/account/security/mfa/:authId/enroll/"
  "/settings/account/subscriptions/"
  "/settings/account/identities/"
  "/settings/account/api/auth-tokens/"
  "/settings/account/api/auth-tokens/new-token/"
  "/settings/account/api/auth-tokens/:tokenId/"
  "/settings/account/api/applications/"
  "/settings/account/api/applications/:appId/"
  "/settings/account/close-account/"
  "/settings/:orgId/"
  "/settings/:orgId/organization/"
  "/settings/:orgId/projects/"
  "/settings/:orgId/api-keys/"
  "/settings/:orgId/api-keys/:apiKey/"
  "/settings/:orgId/audit-log/"
  "/settings/:orgId/auth/"
  "/settings/:orgId/members/"
  "/settings/:orgId/members/requests"
  "/settings/:orgId/members/:memberId/"
  "/settings/:orgId/relay/"
  "/settings/:orgId/repos/"
  "/settings/:orgId/security-and-privacy/"
  "/settings/:orgId/security-and-privacy/advanced-data-scrubbing/:scrubbingId/"
  "/settings/:orgId/teams/"
  "/settings/:orgId/teams/:teamId/"
  "/settings/:orgId/teams/:teamId/members/"
  "/settings/:orgId/teams/:teamId/notifications/"
  "/settings/:orgId/teams/:teamId/projects/"
  "/settings/:orgId/teams/:teamId/settings/"
  "/settings/:orgId/integrations/"
  "/settings/:orgId/integrations/:integrationSlug"
  "/settings/:orgId/integrations/:providerKey/:integrationId/"
  "/settings/:orgId/developer-settings/"
  "/settings/:orgId/developer-settings/new-public/"
  "/settings/:orgId/developer-settings/new-internal/"
  "/settings/:orgId/developer-settings/:appSlug/"
  "/settings/:orgId/developer-settings/:appSlug/dashboard/"
  "/settings/:orgId/auth-tokens/"
  "/settings/:orgId/auth-tokens/new-token/"
  "/settings/:orgId/auth-tokens/:tokenId/"
  "/settings/:orgId/early-features/"
  "/settings/:orgId/dynamic-sampling/"
  "/settings/:orgId/feature-flags/"
  "/settings/:orgId/feature-flags/change-tracking/"
  "/settings/:orgId/feature-flags/change-tracking/new-provider/"
  "/settings/:orgId/stats/"
  "/settings/:orgId/data-forwarding/"
  "/settings/:orgId/data-forwarding/setup/"
  "/settings/:orgId/data-forwarding/:dataForwarderId/edit/"
  "/settings/:orgId/console-sdk-invites/"
  "/settings/:orgId/projects/:projectId/"
  "/settings/:orgId/projects/:projectId/teams/"
  "/settings/:orgId/projects/:projectId/alerts/"
  "/settings/:orgId/projects/:projectId/alerts/rules/"
  "/settings/:orgId/projects/:projectId/alerts/rules/:ruleId/"
  "/settings/:orgId/projects/:projectId/tags/"
  "/settings/:orgId/projects/:projectId/environments/"
  "/settings/:orgId/projects/:projectId/environments/hidden/"
  "/settings/:orgId/projects/:projectId/ownership/"
  "/settings/:orgId/projects/:projectId/seer/"
  "/settings/:orgId/projects/:projectId/user-feedback/"
  "/settings/:orgId/projects/:projectId/toolbar/"
  "/settings/:orgId/projects/:projectId/filters/"
  "/settings/:orgId/projects/:projectId/filters/:filterType/"
  "/settings/:orgId/projects/:projectId/security-and-privacy/"
  "/settings/:orgId/projects/:projectId/security-and-privacy/advanced-data-scrubbing/:scrubbingId/"
  "/settings/:orgId/projects/:projectId/issue-grouping/"
  "/settings/:orgId/projects/:projectId/debug-symbols/"
  "/settings/:orgId/projects/:projectId/proguard/"
  "/settings/:orgId/projects/:projectId/source-maps/"
  "/settings/:orgId/projects/:projectId/source-maps/:bundleId/"
  "/settings/:orgId/projects/:projectId/performance/"
  "/settings/:orgId/projects/:projectId/dynamic-sampling/"
  "/settings/:orgId/projects/:projectId/replays/"
  "/settings/:orgId/projects/:projectId/playstation/"
  "/settings/:orgId/projects/:projectId/mobile-builds/"
  "/settings/:orgId/projects/:projectId/keys/"
  "/settings/:orgId/projects/:projectId/keys/:keyId/"
  "/settings/:orgId/projects/:projectId/loader-script/"
  "/settings/:orgId/projects/:projectId/release-tracking/"
  "/settings/:orgId/projects/:projectId/security-headers/"
  "/settings/:orgId/projects/:projectId/security-headers/csp/"
  "/settings/:orgId/projects/:projectId/security-headers/expect-ct/"
  "/settings/:orgId/projects/:projectId/security-headers/hpkp/"
  "/settings/:orgId/projects/:projectId/csp/"
  "/settings/:orgId/projects/:projectId/plugins/"
  "/settings/:orgId/projects/:projectId/plugins/:pluginId/"
  "/settings/:orgId/projects/:projectId/issue-tracking/"
  "/settings/:orgId/projects/:projectId/hooks/"
  "/settings/:orgId/projects/:projectId/hooks/new/"
  "/settings/:orgId/projects/:projectId/hooks/:hookId/"

  # ── Projects ──────────────────────────────────────────────────────────────
  "/projects/"
  "/projects/new/"
  "/projects/:projectId/"
  "/projects/:projectId/events/:eventId/"
  "/projects/:projectId/getting-started/"
  "/getting-started/:projectId/"
  "/getting-started/:projectId/:platform/"

  # ── Dashboards ────────────────────────────────────────────────────────────
  "/dashboards/"
  "/organizations/:orgId/dashboards/"
  "/dashboards/new/"
  "/dashboards/new/from-seer/"
  "/dashboards/new/:templateId"
  "/dashboards/:dashboardId/"
  "/organizations/:orgId/dashboards/:dashboardId/"
  "/dashboards/:dashboardId/widget-builder/widget/new/"
  "/dashboards/:dashboardId/widget-builder/widget/:widgetIndex/edit/"
  "/dashboards/:dashboardId/widget/:widgetId/"

  # ── Alerts ────────────────────────────────────────────────────────────────
  "/alerts/"
  "/organizations/:orgId/alerts/"
  "/alerts/rules/"
  "/alerts/rules/details/:ruleId/"
  "/alerts/metric-rules/"
  "/alerts/uptime-rules/"
  "/alerts/crons-rules/"
  "/alerts/new/"
  "/alerts/wizard/"
  "/alerts/:projectId/new/"
  "/alerts/:projectId/wizard/"
  "/alerts/:projectId/:alertId/"
  "/alerts/:projectId/:ruleId/details/"

  # ── Monitors ──────────────────────────────────────────────────────────────
  "/monitors/"
  "/monitors/my-monitors/"
  "/monitors/errors/"
  "/monitors/metrics/"
  "/monitors/crons/"
  "/monitors/uptime/"
  "/monitors/mobile-builds/"

  # ── Replays ───────────────────────────────────────────────────────────────
  "/replays/"
  "/replays/selectors/"
  "/replays/:replaySlug/"

  # ── Releases ──────────────────────────────────────────────────────────────
  "/releases/"
  "/releases/new-events/"
  "/releases/all-events/"
  "/releases/:release/"
  "/releases/:release/commits/"
  "/releases/:release/files-changed/"
  "/releases/:release/builds/"

  # ── Discover ──────────────────────────────────────────────────────────────
  "/discover/"
  "/discover/homepage/"
  "/discover/queries/"
  "/discover/results/"
  "/discover/:eventSlug/"

  # ── Performance / Insights ────────────────────────────────────────────────
  "/performance/"
  "/traces/"
  "/profiling/"
  "/profiling/summary/:projectId/"
  "/profiling/profile/:projectId/"
  "/profiling/profile/:projectId/flamegraph/"
  "/profiling/profile/:projectId/differential-flamegraph/"
  "/profiling/profile/:projectId/:eventId/"
  "/profiling/profile/:projectId/:eventId/flamegraph/"

  # Insights domain views  (base: /insights/)
  "/insights/"
  "/insights/frontend/"
  "/insights/frontend/http/"
  "/insights/frontend/pageloads/"
  "/insights/frontend/pageloads/overview/"
  "/insights/frontend/assets/"
  "/insights/frontend/assets/spans/span/:groupId/"
  "/insights/frontend/uptime/"
  "/insights/backend/"
  "/insights/backend/http/"
  "/insights/backend/database/"
  "/insights/backend/database/spans/span/:groupId/"
  "/insights/backend/caches/"
  "/insights/backend/caches/destination/"
  "/insights/backend/queues/"
  "/insights/backend/queues/destination/"
  "/insights/backend/sessions/"
  "/insights/backend/uptime/"
  "/insights/backend/crons/"
  "/insights/mobile/"
  "/insights/mobile/mobile-vitals/"
  "/insights/mobile/mobile-vitals/details/"
  "/insights/mobile/screens/"
  "/insights/mobile/app-startup/"
  "/insights/mobile/ui/"
  "/insights/mobile/screen-rendering/"
  "/insights/mcp/"
  "/insights/mcp/tools/"
  "/insights/mcp/resources/"
  "/insights/mcp/prompts/"
  "/insights/ai-agents/"
  "/insights/ai-agents/models/"
  "/insights/ai-agents/tools/"
  "/insights/conversations/"

  # ── Explore ───────────────────────────────────────────────────────────────
  "/explore/"
  "/explore/profiling/"
  "/explore/traces/"
  "/explore/replays/"
  "/explore/discover/"
  "/explore/releases/"
  "/explore/logs/"
  "/explore/metrics/"
  "/explore/conversations/"
  "/explore/saved-queries/"

  # ── Pre-prod / App bundles ────────────────────────────────────────────────
  "/preprod/"
  "/preprod/size/:artifactId/"
  "/preprod/install/:artifactId/"
  "/preprod/size/compare/"
  "/preprod/:projectId/:artifactId/"
  "/preprod/:projectId/:artifactId/install/"
  "/preprod/:projectId/compare/:headArtifactId/"
  "/preprod/:projectId/compare/:headArtifactId/:baseArtifactId/"
  "/preprod/snapshots/:snapshotId/"

  # ── Pull requests ─────────────────────────────────────────────────────────
  "/pull/"
  "/pull/:repoOrg/:repoName/:prId/"

  # ── Feedback ──────────────────────────────────────────────────────────────
  "/feedback/"

  # ── Issues ────────────────────────────────────────────────────────────────
  "/issues/"
  "/issues/:groupId/"
  "/issues/:groupId/tags/"
  "/issues/:groupId/tags/:tagKey/"
  "/issues/:groupId/events/:eventId/tags/"
  "/issues/:groupId/events/:eventId/tags/:tagKey/"
  "/issues/:groupId/events/:eventId/"
  "/issues/views/"
  "/issues/views/:viewId/"
  "/issues/searches/:searchId/"
  "/issues/feedback/"
  "/issues/alerts/"

  # ── Manage (staff) ────────────────────────────────────────────────────────
  "/manage/"
  "/manage/relays/"
  "/manage/organizations/"
  "/manage/projects/"
  "/manage/settings/"
  "/manage/users/"
  "/manage/users/:id"
  "/manage/status/mail/"
  "/manage/status/environment/"
  "/manage/status/packages/"
  "/manage/status/warnings/"

  # ── Legacy org routes ─────────────────────────────────────────────────────
  "/organizations/:orgId/teams/new/"
  "/organizations/:orgId/"
  "/:orgId/:projectId/getting-started/"
  "/:orgId/:projectId/getting-started/:platform/"
  "/:orgId/:projectId/"
  "/:orgId/"
)

for route in "${routes[@]}"; do
  sub "$route"
done
