#!/bin/bash -eu
python -m pip install pip==8.1.1

make install-python install-python-tests install-yarn dev-postgres

python -m pip install codecov

pip install mysqlclient
# echo 'create database sentry;' | mysql -uroot

# psql -c 'create database sentry;' -U postgres

echo "create keyspace sentry with replication = {'class' : 'SimpleStrategy', 'replication_factor': 1};" | cqlsh --cqlversion=3.1.7
echo 'create table nodestore (key text primary key, value blob, flags int);' | cqlsh -k sentry --cqlversion=3.1.7
