from sentry.search.eap import constants
from sentry.search.eap.columns import ResolvedAttribute, datetime_processor
from sentry.search.eap.common_columns import COMMON_COLUMNS

PREPROD_SIZE_ATTRIBUTE_DEFINITIONS = {
    column.public_alias: column
    for column in COMMON_COLUMNS
    + [
        ResolvedAttribute(
            public_alias="preprod_artifact_id",
            internal_name="preprod_artifact_id",
            search_type="integer",
        ),
        ResolvedAttribute(
            public_alias="size_metric_id",
            internal_name="size_metric_id",
            search_type="integer",
        ),
        ResolvedAttribute(
            public_alias="sub_item_type",
            internal_name="sub_item_type",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="metrics_artifact_type",
            internal_name="metrics_artifact_type",
            search_type="integer",
        ),
        ResolvedAttribute(
            public_alias="max_install_size",
            internal_name="max_install_size",
            search_type="integer",
        ),
        ResolvedAttribute(
            public_alias="max_download_size",
            internal_name="max_download_size",
            search_type="integer",
        ),
        ResolvedAttribute(
            public_alias="min_install_size",
            internal_name="min_install_size",
            search_type="integer",
        ),
        ResolvedAttribute(
            public_alias="min_download_size",
            internal_name="min_download_size",
            search_type="integer",
        ),
        ResolvedAttribute(
            public_alias="artifact_type",
            internal_name="artifact_type",
            search_type="integer",
        ),
        ResolvedAttribute(
            public_alias="artifact_state",
            internal_name="artifact_state",
            search_type="integer",
        ),
        ResolvedAttribute(
            public_alias="app_id",
            internal_name="app_id",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="app_name",
            internal_name="app_name",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="build_version",
            internal_name="build_version",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="build_number",
            internal_name="build_number",
            search_type="integer",
        ),
        ResolvedAttribute(
            public_alias="main_binary_identifier",
            internal_name="main_binary_identifier",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="artifact_date_built",
            internal_name="artifact_date_built",
            search_type="integer",
        ),
        ResolvedAttribute(
            public_alias="build_configuration_name",
            internal_name="build_configuration_name",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="git_head_sha",
            internal_name="git_head_sha",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="git_base_sha",
            internal_name="git_base_sha",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="git_provider",
            internal_name="git_provider",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="git_head_repo_name",
            internal_name="git_head_repo_name",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="git_base_repo_name",
            internal_name="git_base_repo_name",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="git_head_ref",
            internal_name="git_head_ref",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="git_base_ref",
            internal_name="git_base_ref",
            search_type="string",
        ),
        ResolvedAttribute(
            public_alias="git_pr_number",
            internal_name="git_pr_number",
            search_type="integer",
        ),
        ResolvedAttribute(
            public_alias="timestamp",
            internal_name="sentry.timestamp",
            internal_type=constants.DOUBLE,
            search_type="string",
            processor=datetime_processor,
        ),
    ]
}
