// AUTOGENERATED BY @DESIGN-ENGINEERING
// DO NOT EDIT THIS FILE MANUALLY

export const typography = {
  font: {
    size: {
      /**
       * A named fontSize value evaluating to “11px”
       */
      xs: '11px',
      /**
       * A named fontSize value evaluating to “12px”
       */
      sm: '12px',
      /**
       * A named fontSize value evaluating to “14px”
       */
      md: '14px',
      /**
       * A named fontSize value evaluating to “16px”
       */
      lg: '16px',
      /**
       * A named fontSize value evaluating to “20px”
       */
      xl: '20px',
      /**
       * A named fontSize value evaluating to “24px”
       */
      '2xl': '24px',
      /**
       * A named fontSize value evaluating to “32px”
       */
      '3xl': '32px',
      /**
       * A named fontSize value evaluating to “40px”
       */
      '4xl': '40px',
    },
    weight: {
      sans: {
        /**
         * The regular font weight for text using the sans font family.
         */
        regular: 400,
        /**
         * The medium font weight for text using the sans font family.
         */
        medium: 500,
      },
      mono: {
        /**
         * The regular font weight for text using the mono font family.
         */
        regular: 425,
        /**
         * The medium font weight for text using the mono font family.
         */
        medium: 500,
      },
    },
    family: {
      /**
       * Sans-serif font family for headings and body copy
       */
      sans: "Rubik, 'Avenir Next', sans-serif",
      /**
       * Monospace font family for code samples
       */
      mono: "'Roboto Mono', Monaco, Consolas, 'Courier New', monospace",
    },
    lineHeight: {
      /**
       * A named lineHeight value evaluating to “1”
       */
      compressed: '1',
      /**
       * A named lineHeight value evaluating to “1.2”
       */
      default: '1.2',
      /**
       * A named lineHeight value evaluating to “1.4”
       */
      comfortable: '1.4',
      /**
       * A named lineHeight value evaluating to “1rem”
       */
      fixed: '1rem',
    },
  },
};
