/**
 * MANUALLY UPDATED FILE.
 * Keep this file in sync with getsentry/conf/urls/app.py in getsentry/getsentry
 *
 * This file is the sibling to knownSentryApiUrls.generated.ts.
 */

export type KnownGetsentryApiUrls =
  | '/audit-logs/'
  | '/beacons/'
  | '/beacons/$beaconId/'
  | '/beacons/$beaconId/checkins/'
  | '/beacons/$beaconId/related-beacons/'
  | '/billing-plans/'
  | '/billingadmins/'
  | '/broadcasts/'
  | '/broadcasts/$broadcastId/'
  | '/copilot/'
  | '/copilot/webhook/'
  | '/customers/'
  | '/customers/$organizationIdOrSlug/'
  | '/customers/$organizationIdOrSlug/balancechanges/'
  | '/customers/$organizationIdOrSlug/billing-config/'
  | '/customers/$organizationIdOrSlug/billing-details/'
  | '/customers/$organizationIdOrSlug/billing-seats/current/'
  | '/customers/$organizationIdOrSlug/charges/'
  | '/customers/$organizationIdOrSlug/charges/$chargeId/'
  | '/customers/$organizationIdOrSlug/history/'
  | '/customers/$organizationIdOrSlug/history/$historyId/'
  | '/customers/$organizationIdOrSlug/history/current/'
  | '/customers/$organizationIdOrSlug/invoices/'
  | '/customers/$organizationIdOrSlug/invoices/$invoiceId/'
  | '/customers/$organizationIdOrSlug/invoices/$invoiceId/close/'
  | '/customers/$organizationIdOrSlug/invoices/$invoiceId/effective-at/'
  | '/customers/$organizationIdOrSlug/invoices/$invoiceId/retry-payment/'
  | '/customers/$organizationIdOrSlug/members/'
  | '/customers/$organizationIdOrSlug/migrate-google-domain/'
  | '/customers/$organizationIdOrSlug/ondemand-budgets/'
  | '/customers/$organizationIdOrSlug/plan-migrations/'
  | '/customers/$organizationIdOrSlug/policies/'
  | '/customers/$organizationIdOrSlug/product-trial/'
  | '/customers/$organizationIdOrSlug/projects/$projectIdOrSlug/stats/'
  | '/customers/$organizationIdOrSlug/provision-subscription/'
  | '/customers/$organizationIdOrSlug/recurring-credits/'
  | '/customers/$organizationIdOrSlug/redeem-promo/'
  | '/customers/$organizationIdOrSlug/send-weekly-email/'
  | '/customers/$organizationIdOrSlug/spend-notifications/'
  | '/customers/$organizationIdOrSlug/stats/'
  | '/customers/$organizationIdOrSlug/subscription/'
  | '/customers/$organizationIdOrSlug/subscription/next-bill/'
  | '/customers/$organizationIdOrSlug/subscription/preview/'
  | '/customers/$organizationIdOrSlug/subscription/usage-logs/'
  | '/customers/$organizationIdOrSlug/usage/'
  | '/internal-stats/$organizationIdOrSlug/integrations/'
  | '/internal-stats/$organizationIdOrSlug/onboarding-tasks/'
  | '/internal-stats/$organizationIdOrSlug/platforms/'
  | '/invoices/'
  | '/invoices/$invoiceId/'
  | '/invoices/$invoiceId/close/'
  | '/invoices/$invoiceId/effective-at/'
  | '/invoices/$invoiceId/retry-payment/'
  | '/organizations/$organizationIdOrSlug/codecov-jwt/'
  | '/organizations/$organizationIdOrSlug/issues/force-auto-assignment/'
  | '/organizations/$organizationIdOrSlug/monitor-count/'
  | '/organizations/$organizationIdOrSlug/partnership-agreements/'
  | '/organizations/$organizationIdOrSlug/payments/$paymentId/new/'
  | '/organizations/$organizationIdOrSlug/promotions/$promoSlug/claim/'
  | '/organizations/$organizationIdOrSlug/promotions/$promoSlug/decline/'
  | '/organizations/$organizationIdOrSlug/promotions/trigger-check/'
  | '/organizations/$organizationIdOrSlug/spike-projection/projects/$projectIdOrSlug/'
  | '/organizations/$organizationIdOrSlug/spikes/projects/$projectIdOrSlug/'
  | '/policies/'
  | '/policies/$policySlug/'
  | '/policies/$policySlug/revisions/'
  | '/policies/$policySlug/revisions/$version/'
  | '/promocodes-external/$code'
  | '/promocodes/'
  | '/promocodes/$code/'
  | '/promocodes/$code/claimants/'
  | '/signup/'
  | '/users/$userId/customers/'
  | '/users/$userId/merge-accounts/';
