import {injectGlobal} from 'emotion';

import rubikRegular from '../../fonts/rubik-regular.woff';
import rubikMedium from '../../fonts/rubik-medium.woff';
import sentrySimpleWoff from '../../fonts/sentry-simple.woff';
import sentrySimpleWoff2 from '../../fonts/sentry-simple.woff2';

injectGlobal`
  @font-face {
    font-family: 'Rubik';
    src: url(${rubikRegular}) format('woff2'),
      url(${rubikRegular}) format('woff');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'Rubik';
    src: url(${rubikMedium}) format('woff2'),
      url(${rubikMedium}) format('woff');
    font-weight: bold;
    font-style: normal;
  }

  // Sentry icon font
  @font-face {
    font-family: 'sentry-simple';
    src: url(${sentrySimpleWoff}) format('woff'),
      url(${sentrySimpleWoff2}) format('woff2');
    font-weight: normal;
    font-style: normal;
  }

  [class^='icon-'],
  [class*=' icon-'],
  .icon {
    font-family: 'sentry-simple';
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;

    /* Better Font Rendering =========== */
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
  .icon-support:before {
    content: '\\e910';
  }

  .icon-processing {
    position: relative;
    left: -3px;

    &:before {
      display: inline-block;
      content: '\\e60b';
      position: relative;
      top: 2px;
      -ms-transform: rotate(45deg);
      -moz-transform: rotate(45deg);
      -webkit-transform: rotate(45deg);
      -o-transform: rotate(45deg);
      transform: rotate(45deg);
    }
    &:after {
      display: block;
      position: absolute;
      font-size: 10px;
      width: 10px;
      height: 10px;
      line-height: 10px;
      content: '\\e60b';
      top: -4px;
      right: -6px;
      -ms-transform: rotate(-20deg);
      -moz-transform: rotate(-20deg);
      -webkit-transform: rotate(-20deg);
      -o-transform: rotate(-20deg);
      transform: rotate(-20deg);
    }

    &.play {
      &:before {
        .clockwise;
      }
      &:after {
        .counter-clockwise;
      }
    }
  }

  @-webkit-keyframes clockwise {
    from {
      -ms-transform: rotate(0deg);
      -moz-transform: rotate(0deg);
      -webkit-transform: rotate(0deg);
      -o-transform: rotate(0deg);
      transform: rotate(0deg);
    }
    to {
      -ms-transform: rotate(360deg);
      -moz-transform: rotate(360deg);
      -webkit-transform: rotate(360deg);
      -o-transform: rotate(360deg);
      transform: rotate(360deg);
    }
  }
  @keyframes clockwise {
    from {
      -ms-transform: rotate(0deg);
      -moz-transform: rotate(0deg);
      -webkit-transform: rotate(0deg);
      -o-transform: rotate(0deg);
      transform: rotate(0deg);
    }
    to {
      -ms-transform: rotate(360deg);
      -moz-transform: rotate(360deg);
      -webkit-transform: rotate(360deg);
      -o-transform: rotate(360deg);
      transform: rotate(360deg);
    }
  }

  @-webkit-keyframes counter-clockwise {
    from {
      -ms-transform: rotate(-20deg);
      -moz-transform: rotate(-20deg);
      -webkit-transform: rotate(-20deg);
      -o-transform: rotate(-20deg);
      transform: rotate(-20deg);
    }
    to {
      -ms-transform: rotate(-380deg);
      -moz-transform: rotate(-380deg);
      -webkit-transform: rotate(-380deg);
      -o-transform: rotate(-380deg);
      transform: rotate(-380deg);
    }
  }
  @keyframes counter-clockwise {
    from {
      -ms-transform: rotate(-20deg);
      -moz-transform: rotate(-20deg);
      -webkit-transform: rotate(-20deg);
      -o-transform: rotate(-20deg);
      transform: rotate(-20deg);
    }
    to {
      -ms-transform: rotate(-380deg);
      -moz-transform: rotate(-380deg);
      -webkit-transform: rotate(-380deg);
      -o-transform: rotate(-380deg);
      transform: rotate(-380deg);
    }
  }

  .clockwise {
    -webkit-animation: clockwise 2s linear infinite;
    -moz-animation: clockwise 2s linear infinite;
    -ms-animation: clockwise 2s linear infinite;
    -o-animation: clockwise 2s linear infinite;
    animation: clockwise 2s linear infinite;
  }

  .counter-clockwise {
    -webkit-animation: counter-clockwise 1s linear infinite;
    -moz-animation: counter-clockwise 1s linear infinite;
    -ms-animation: counter-clockwise 1s linear infinite;
    -o-animation: counter-clockwise 1s linear infinite;
    animation: counter-clockwise 1s linear infinite;
  }

  // [[IMPORTANT]] Everything after this line is autogenerated

  .icon-apple:before {
    content: '\\E912';
  }
  .icon-support:before {
    content: '\\E910';
  }
  .icon-wrench:before {
    content: '\\E90d';
  }
  .icon-hash:before {
    content: '\\E90c';
  }
  .icon-git-commit:before {
    content: '\\E911';
  }
  .icon-code:before {
    content: '\\E905';
  }
  .icon-markdown:before {
    content: '\\E900';
  }
  .icon-triangle:before {
    content: '\\E604';
  }
  .icon-anchor:before {
    content: '\\E61d';
  }
  .icon-soundoff:before {
    content: '\\E607';
  }
  .icon-alert:before {
    content: '\\E906';
  }
  .icon-sentry-logo:before {
    content: '\\E61a';
  }
  .icon-sentry-logo-full:before {
    content: '\\E623';
  }
  .icon-mark-github:before {
    content: '\\E621';
  }
  .icon-close2:before {
    content: '\\E61e';
  }
  .icon-calendar:before {
    content: '\\E603';
  }
  .icon-play:before {
    content: '\\E61c';
  }
  .icon-bookmark-2:before {
    content: '\\E620';
  }
  .icon-ellipsis:before {
    content: '\\E617';
  }
  .icon-tag:before {
    content: '\\E618';
  }
  .icon-toggle:before {
    content: '\\E619';
  }
  .icon-search:before {
    content: '\\E601';
  }
  .icon-envelope:before {
    content: '\\E605';
  }
  .icon-trash:before {
    content: '\\E606';
  }
  .icon-settings:before {
    content: '\\E60b';
  }
  .icon-user:before {
    content: '\\E608';
  }
  .icon-comments:before {
    content: '\\E609';
  }
  .icon-checkmark:before {
    content: '\\E60a';
  }
  .icon-clock:before {
    content: '\\E60c';
  }
  .icon-x:before {
    content: '\\E61b';
  }
  .icon-users:before {
    content: '\\E612';
  }
  .icon-pause:before {
    content: '\\E614';
  }
  .icon-exclamation:before {
    content: '\\E615';
  }
  .icon-bookmark:before {
    content: '\\E613';
  }
  .icon-book:before {
    content: '\\E600';
  }
  .icon-question:before {
    content: '\\E602';
  }
  .icon-mouse-pointer:before {
    content: '\\E90a';
  }
  .icon-console:before {
    content: '\\E909';
  }
  .icon-star-outline:before {
    content: '\\E903';
  }
  .icon-star-solid:before {
    content: '\\E904';
  }
  .icon-code2:before {
    content: '\\E622';
  }
  .icon-exit:before {
    content: '\\E90e';
  }
  .icon-close:before {
    content: '\\E90f';
  }
  .icon-av_timer:before {
    content: '\\E902';
  }
  .icon-filter:before {
    content: '\\E61f';
  }
  .icon-circle-check:before {
    content: '\\E042';
  }
  .icon-circle-cross:before {
    content: '\\E043';
  }
  .icon-globe:before {
    content: '\\E078';
  }
  .icon-ban:before {
    content: '\\E107';
  }
  .icon-open:before {
    content: '\\E128';
  }
  .icon-more:before {
    content: '\\E901';
  }
  .icon-add:before {
    content: '\\E624';
  }
  .icon-bell:before {
    content: '\\E006';
  }
  .icon-lock:before {
    content: '\\E007';
  }
  .icon-unlock:before {
    content: '\\E008';
  }
  .icon-signal:before {
    content: '\\E011';
  }
  .icon-skip-back:before {
    content: '\\E050';
  }
  .icon-skip-forward:before {
    content: '\\E056';
  }
  .icon-plus:before {
    content: '\\E114';
  }
  .icon-minus:before {
    content: '\\E115';
  }
  .icon-folder:before {
    content: '\\E907';
  }
  .icon-location:before {
    content: '\\E90b';
  }
  .icon-eye:before {
    content: '\\E60d';
  }
  .icon-browser:before {
    content: '\\E616';
  }
  .icon-refresh:before {
    content: '\\E908';
  }
  .icon-home:before {
    content: '\\E625';
  }
  .icon-arrow-left:before {
    content: '\\E60e';
  }
  .icon-arrow-down:before {
    content: '\\E60f';
  }
  .icon-arrow-up:before {
    content: '\\E610';
  }
  .icon-arrow-right:before {
    content: '\\E611';
  }
`;
