from sentry.data_export.models import ExportedData
from sentry.discover.models import DiscoverSavedQuery
from sentry.incidents.models import (
    AlertRuleActivity,
    AlertRuleTriggerAction,
    IncidentActivity,
    IncidentSeen,
    IncidentSnapshot,
    IncidentSubscription,
    TimeSeriesSnapshot,
)
from sentry.models import (
    Activity,
    Actor,
    ApiApplication,
    ApiAuthorization,
    ApiGrant,
    ApiKey,
    ApiToken,
    AssistantActivity,
    AuditLogEntry,
    AuthProvider,
    AuthProviderDefaultTeams,
    Broadcast,
    BroadcastSeen,
    Dashboard,
    GroupAssignee,
    GroupBookmark,
    GroupOwner,
    GroupSeen,
    GroupShare,
    GroupSubscription,
    Identity,
    IdentityProvider,
    MonitorCheckIn,
    MonitorLocation,
    NotificationSetting,
    Organization,
    OrganizationAccessRequest,
    OrganizationMember,
    OrganizationOnboardingTask,
    Project,
    ProjectBookmark,
    ProjectTransactionThreshold,
    ProjectTransactionThresholdOverride,
    PromptsActivity,
    RecentSearch,
    Release,
    RuleActivity,
    SavedSearch,
    SentryApp,
    SentryAppAvatar,
    SentryAppComponent,
    SentryAppInstallation,
    SentryAppInstallationForProvider,
    SentryAppInstallationToken,
    ServiceHook,
    Team,
    User,
    UserOption,
)
from tests.sentry.hybrid_cloud import (
    validate_models_have_silos,
    validate_no_cross_silo_foreign_keys,
)


class any_model:
    def __eq__(self, other):
        return True

    def __le__(self, other):
        return False

    def __ge__(self, other):
        return False

    def __hash__(self):
        return 1


decorator_exemptions = {}
fk_emeptions = {
    (Activity, User),
    (ApiAuthorization, ApiApplication),
    (ApiAuthorization, User),
    (ApiGrant, User),
    (ApiGrant, ApiApplication),
    (ApiGrant, Organization),
    (ApiKey, Organization),
    (AssistantActivity, User),
    (AuditLogEntry, Organization),
    (OrganizationMember, User),
    (AuthProviderDefaultTeams, Team),
    (AuthProvider, Organization),
    (SentryAppAvatar, SentryApp),
    (BroadcastSeen, Broadcast),
    (BroadcastSeen, User),
    (User, Dashboard),
    (GroupAssignee, User),
    (User, GroupAssignee),
    (GroupBookmark, User),
    (User, GroupBookmark),
    (Release, User),
    (User, Release),
    (GroupOwner, User),
    (User, GroupOwner),
    (GroupSeen, User),
    (User, GroupSeen),
    (GroupShare, User),
    (User, GroupShare),
    (GroupSubscription, User),
    (User, GroupSubscription),
    (Identity, IdentityProvider),
    (IdentityProvider, Identity),
    (Identity, User),
    (User, Identity),
    (SentryApp, Organization),
    (Organization, SentryApp),
    (SentryAppComponent, SentryApp),
    (SentryApp, SentryAppComponent),
    (SentryAppInstallation, Organization),
    (Organization, SentryAppInstallation),
    (SentryAppInstallation, ApiGrant),
    (ApiGrant, SentryAppInstallation),
    (SentryAppInstallationForProvider, SentryAppInstallation),
    (SentryAppInstallation, SentryAppInstallationForProvider),
    (SentryAppInstallationToken, ApiToken),
    (ApiToken, SentryAppInstallationToken),
    (SentryAppInstallationToken, SentryAppInstallation),
    (SentryAppInstallation, SentryAppInstallationToken),
    (MonitorCheckIn, MonitorLocation),
    (MonitorLocation, MonitorCheckIn),
    (NotificationSetting, Actor),
    (Actor, NotificationSetting),
    (UserOption, Project),
    (Project, UserOption),
    (UserOption, Organization),
    (Organization, UserOption),
    (OrganizationAccessRequest, User),
    (User, OrganizationAccessRequest),
    (OrganizationOnboardingTask, User),
    (User, OrganizationOnboardingTask),
    (ProjectBookmark, User),
    (User, ProjectBookmark),
    (PromptsActivity, User),
    (User, PromptsActivity),
    (RecentSearch, User),
    (User, RecentSearch),
    (RuleActivity, User),
    (User, RuleActivity),
    (SavedSearch, User),
    (User, SavedSearch),
    (ServiceHook, ApiApplication),
    (ApiApplication, ServiceHook),
    (ProjectTransactionThresholdOverride, User),
    (User, ProjectTransactionThresholdOverride),
    (ProjectTransactionThreshold, User),
    (User, ProjectTransactionThreshold),
    (User, Actor),
    (Actor, User),
    (IncidentSeen, User),
    (User, IncidentSeen),
    (IncidentSnapshot, TimeSeriesSnapshot),
    (TimeSeriesSnapshot, IncidentSnapshot),
    (IncidentActivity, User),
    (User, IncidentActivity),
    (IncidentSubscription, User),
    (User, IncidentSubscription),
    (AlertRuleTriggerAction, SentryApp),
    (SentryApp, AlertRuleTriggerAction),
    (AlertRuleActivity, User),
    (User, AlertRuleActivity),
    (DiscoverSavedQuery, User),
    (User, DiscoverSavedQuery),
    (ExportedData, User),
    (User, ExportedData),
}


def test_models_have_silos():
    validate_models_have_silos(decorator_exemptions)


def test_silo_foreign_keys():
    validate_no_cross_silo_foreign_keys(fk_emeptions)
