export enum MCPReferrer {
  MCP_PROMPT_DURATION_WIDGET = 'api.insights.mcp.prompt-duration-widget',
  MCP_PROMPT_ERROR_RATE_WIDGET = 'api.insights.mcp.prompt-error-rate-widget',
  MCP_PROMPT_TABLE = 'api.insights.mcp.prompt-table',
  MCP_PROMPT_TRAFFIC_WIDGET = 'api.insights.mcp.prompt-traffic-widget',
  MCP_RESOURCE_DURATION_WIDGET = 'api.insights.mcp.resource-duration-widget',
  MCP_RESOURCE_ERROR_RATE_WIDGET = 'api.insights.mcp.resource-error-rate-widget',
  MCP_RESOURCE_TABLE = 'api.insights.mcp.resource-table',
  MCP_RESOURCE_TRAFFIC_WIDGET = 'api.insights.mcp.resource-traffic-widget',
  MCP_TOOL_DURATION_WIDGET = 'api.insights.mcp.tool-duration-widget',
  MCP_TOOL_ERROR_RATE_WIDGET = 'api.insights.mcp.tool-error-rate-widget',
  MCP_TOOL_TABLE = 'api.insights.mcp.tool-table',
  MCP_TOOL_TRAFFIC_WIDGET = 'api.insights.mcp.tool-traffic-widget',
  MCP_TRAFFIC_BY_CLIENT_WIDGET = 'api.insights.mcp.traffic-by-client-widget',
  MCP_TRAFFIC_WIDGET = 'api.insights.mcp.traffic-widget',
  MCP_TRANSPORT_WIDGET = 'api.insights.mcp.transport-widget',
  MCP_OVERVIEW_TABLE = 'api.insights.mcp.overview-table',
}
