name: jest balancer
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15 * *'
jobs:
  jest-balance:
    # Buckle up, this may take a while
    timeout-minutes: 60
    # Make sure this matches the runner that runs frontend tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: ./.github/actions/setup-node-pnpm

      - name: jest balancer
        env:
          GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          GITHUB_PR_REF: ${{ github.event.pull_request.head.ref || github.ref }}
        run: JEST_TEST_BALANCER=1 pnpm run test:ci

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4.6.2
        with:
          name: jest-balance.json
          path: tests/js/test-balancer/jest-balance.json
